/****************************************************************************
 * arch/arm/src/stm32c5/hardware/stm32c5xx_pinmap.h
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

#ifndef __ARCH_ARM_SRC_STM32C5_HARDWARE_STM32C5XX_PINMAP_H
#define __ARCH_ARM_SRC_STM32C5_HARDWARE_STM32C5XX_PINMAP_H

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <nuttx/config.h>

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* Alternate Pin Functions.  This map contains every GPIO alternate
 * function available on the supported device package:
 *
 *   STM32C5 devices
 *
 * It is derived from the ST device package pinout data.  It also
 * contains the peripheral analog pins represented by the NuttX GPIO
 * pin-map interface.
 *
 * Alternative pin selections are provided with a numeric suffix like _1,
 * _2, etc.  Drivers use the selection without the numeric suffix; board.h
 * must map that name to the pin used by the board.  For example:
 *
 * #define GPIO_FDCAN1_RX GPIO_FDCAN1_RX_1
 *
 * Pull resistors, output type, and slew rate are board-specific and are not
 * encoded here.  Timer channels have separate input and output names to
 * match the NuttX timer driver contracts.
 */

/* Analog-to-digital converters */

#define GPIO_ADC1_IN0_1              (GPIO_ANALOG | GPIO_PORTA | GPIO_PIN0)
#define GPIO_ADC1_IN1_1              (GPIO_ANALOG | GPIO_PORTA | GPIO_PIN1)
#define GPIO_ADC1_IN2_1              (GPIO_ANALOG | GPIO_PORTA | GPIO_PIN2)
#define GPIO_ADC1_IN3_1              (GPIO_ANALOG | GPIO_PORTA | GPIO_PIN3)
#define GPIO_ADC1_IN4_1              (GPIO_ANALOG | GPIO_PORTA | GPIO_PIN4)
#define GPIO_ADC1_IN5_1              (GPIO_ANALOG | GPIO_PORTA | GPIO_PIN5)
#define GPIO_ADC1_IN6_1              (GPIO_ANALOG | GPIO_PORTA | GPIO_PIN6)
#define GPIO_ADC1_IN7_1              (GPIO_ANALOG | GPIO_PORTA | GPIO_PIN7)
#define GPIO_ADC1_IN8_1              (GPIO_ANALOG | GPIO_PORTC | GPIO_PIN0)
#define GPIO_ADC1_IN9_1              (GPIO_ANALOG | GPIO_PORTC | GPIO_PIN1)
#define GPIO_ADC1_IN10_1             (GPIO_ANALOG | GPIO_PORTC | GPIO_PIN2)
#define GPIO_ADC1_IN11_1             (GPIO_ANALOG | GPIO_PORTC | GPIO_PIN3)
#define GPIO_ADC2_IN0_1              (GPIO_ANALOG | GPIO_PORTA | GPIO_PIN0)
#define GPIO_ADC2_IN1_1              (GPIO_ANALOG | GPIO_PORTA | GPIO_PIN1)
#define GPIO_ADC2_IN2_1              (GPIO_ANALOG | GPIO_PORTA | GPIO_PIN2)
#define GPIO_ADC2_IN3_1              (GPIO_ANALOG | GPIO_PORTA | GPIO_PIN3)
#define GPIO_ADC2_IN4_1              (GPIO_ANALOG | GPIO_PORTC | GPIO_PIN4)
#define GPIO_ADC2_IN5_1              (GPIO_ANALOG | GPIO_PORTC | GPIO_PIN5)
#define GPIO_ADC2_IN6_1              (GPIO_ANALOG | GPIO_PORTB | GPIO_PIN0)
#define GPIO_ADC2_IN7_1              (GPIO_ANALOG | GPIO_PORTB | GPIO_PIN1)
#define GPIO_ADC2_IN8_1              (GPIO_ANALOG | GPIO_PORTB | GPIO_PIN2)
#define GPIO_ADC2_IN9_1              (GPIO_ANALOG | GPIO_PORTC | GPIO_PIN1)
#define GPIO_ADC2_IN10_1             (GPIO_ANALOG | GPIO_PORTC | GPIO_PIN2)
#define GPIO_ADC2_IN11_1             (GPIO_ANALOG | GPIO_PORTC | GPIO_PIN3)

/* Audio clock input */

#define GPIO_AUDIOCLK_1              (GPIO_ALT | GPIO_AF5 | GPIO_PORTC | GPIO_PIN9)

/* Comparators */

#define GPIO_COMP1_INM_1             (GPIO_ANALOG | GPIO_PORTA | GPIO_PIN5)
#define GPIO_COMP1_INM_2             (GPIO_ANALOG | GPIO_PORTB | GPIO_PIN1)
#define GPIO_COMP1_INM_3             (GPIO_ANALOG | GPIO_PORTC | GPIO_PIN4)
#define GPIO_COMP1_INP_1             (GPIO_ANALOG | GPIO_PORTA | GPIO_PIN0)
#define GPIO_COMP1_INP_2             (GPIO_ANALOG | GPIO_PORTB | GPIO_PIN0)
#define GPIO_COMP1_INP_3             (GPIO_ANALOG | GPIO_PORTB | GPIO_PIN2)
#define GPIO_COMP1_OUT_1             (GPIO_ALT | GPIO_AF14 | GPIO_PORTA | GPIO_PIN3)
#define GPIO_COMP1_OUT_2             (GPIO_ALT | GPIO_AF14 | GPIO_PORTA | GPIO_PIN13)
#define GPIO_COMP1_OUT_3             (GPIO_ALT | GPIO_AF14 | GPIO_PORTB | GPIO_PIN1)
#define GPIO_COMP1_OUT_4             (GPIO_ALT | GPIO_AF14 | GPIO_PORTC | GPIO_PIN5)

/* Clock recovery system */

#define GPIO_CRS_SYNC_1              (GPIO_ALT | GPIO_AF10 | GPIO_PORTB | GPIO_PIN3)

/* Digital-to-analog converters */

#define GPIO_DAC1_OUT1_1             (GPIO_ANALOG | GPIO_PORTA | GPIO_PIN4)

/* Debug support */

#define GPIO_JTCK_SWCLK_1            (GPIO_ALT | GPIO_AF0 | GPIO_PORTA | GPIO_PIN14)
#define GPIO_JTDI_1                  (GPIO_ALT | GPIO_AF0 | GPIO_PORTA | GPIO_PIN15)
#define GPIO_JTDO_TRACESWO_1         (GPIO_ALT | GPIO_AF0 | GPIO_PORTB | GPIO_PIN3)
#define GPIO_JTMS_SWDIO_1            (GPIO_ALT | GPIO_AF0 | GPIO_PORTA | GPIO_PIN13)
#define GPIO_NJTRST_1                (GPIO_ALT | GPIO_AF0 | GPIO_PORTB | GPIO_PIN4)
#define GPIO_TRACECLK_1              (GPIO_ALT | GPIO_AF0 | GPIO_PORTE | GPIO_PIN2)
#define GPIO_TRACED0_1               (GPIO_ALT | GPIO_AF0 | GPIO_PORTC | GPIO_PIN1)
#define GPIO_TRACED1_1               (GPIO_ALT | GPIO_AF0 | GPIO_PORTC | GPIO_PIN8)
#define GPIO_TRACED2_1               (GPIO_ALT | GPIO_AF0 | GPIO_PORTD | GPIO_PIN2)
#define GPIO_TRACED3_1               (GPIO_ALT | GPIO_AF0 | GPIO_PORTC | GPIO_PIN12)

/* Flexible data-rate CAN */

#define GPIO_FDCAN1_RX_1             (GPIO_ALT | GPIO_AF9 | GPIO_PORTA | GPIO_PIN11)
#define GPIO_FDCAN1_RX_2             (GPIO_ALT | GPIO_AF9 | GPIO_PORTB | GPIO_PIN5)
#define GPIO_FDCAN1_RX_3             (GPIO_ALT | GPIO_AF9 | GPIO_PORTB | GPIO_PIN8)
#define GPIO_FDCAN1_RX_4             (GPIO_ALT | GPIO_AF9 | GPIO_PORTB | GPIO_PIN12)
#define GPIO_FDCAN1_RX_5             (GPIO_ALT | GPIO_AF9 | GPIO_PORTC | GPIO_PIN14)
#define GPIO_FDCAN1_RX_6             (GPIO_ALT | GPIO_AF9 | GPIO_PORTH | GPIO_PIN2)
#define GPIO_FDCAN1_TX_1             (GPIO_ALT | GPIO_AF9 | GPIO_PORTA | GPIO_PIN12)
#define GPIO_FDCAN1_TX_2             (GPIO_ALT | GPIO_AF9 | GPIO_PORTB | GPIO_PIN6)
#define GPIO_FDCAN1_TX_3             (GPIO_ALT | GPIO_AF9 | GPIO_PORTB | GPIO_PIN7)
#define GPIO_FDCAN1_TX_4             (GPIO_ALT | GPIO_AF9 | GPIO_PORTB | GPIO_PIN9)
#define GPIO_FDCAN1_TX_5             (GPIO_ALT | GPIO_AF9 | GPIO_PORTB | GPIO_PIN13)
#define GPIO_FDCAN1_TX_6             (GPIO_ALT | GPIO_AF9 | GPIO_PORTC | GPIO_PIN13)

/* Inter-integrated circuit interfaces */

#define GPIO_I2C1_SCL_1              (GPIO_ALT | GPIO_AF9 | GPIO_PORTA | GPIO_PIN8)
#define GPIO_I2C1_SCL_2              (GPIO_ALT | GPIO_AF4 | GPIO_PORTB | GPIO_PIN6)
#define GPIO_I2C1_SCL_3              (GPIO_ALT | GPIO_AF4 | GPIO_PORTB | GPIO_PIN8)
#define GPIO_I2C1_SCL_4              (GPIO_ALT | GPIO_AF4 | GPIO_PORTH | GPIO_PIN1)
#define GPIO_I2C1_SDA_1              (GPIO_ALT | GPIO_AF4 | GPIO_PORTB | GPIO_PIN7)
#define GPIO_I2C1_SDA_2              (GPIO_ALT | GPIO_AF4 | GPIO_PORTB | GPIO_PIN9)
#define GPIO_I2C1_SDA_3              (GPIO_ALT | GPIO_AF9 | GPIO_PORTC | GPIO_PIN9)
#define GPIO_I2C1_SDA_4              (GPIO_ALT | GPIO_AF4 | GPIO_PORTH | GPIO_PIN0)
#define GPIO_I2C1_SMBA_1             (GPIO_ALT | GPIO_AF9 | GPIO_PORTA | GPIO_PIN9)
#define GPIO_I2C1_SMBA_2             (GPIO_ALT | GPIO_AF4 | GPIO_PORTB | GPIO_PIN5)
#define GPIO_I2C2_SCL_1              (GPIO_ALT | GPIO_AF8 | GPIO_PORTA | GPIO_PIN11)
#define GPIO_I2C2_SCL_2              (GPIO_ALT | GPIO_AF9 | GPIO_PORTB | GPIO_PIN3)
#define GPIO_I2C2_SCL_3              (GPIO_ALT | GPIO_AF4 | GPIO_PORTB | GPIO_PIN10)
#define GPIO_I2C2_SDA_1              (GPIO_ALT | GPIO_AF8 | GPIO_PORTA | GPIO_PIN12)
#define GPIO_I2C2_SDA_2              (GPIO_ALT | GPIO_AF4 | GPIO_PORTB | GPIO_PIN3)
#define GPIO_I2C2_SDA_3              (GPIO_ALT | GPIO_AF9 | GPIO_PORTB | GPIO_PIN4)
#define GPIO_I2C2_SDA_4              (GPIO_ALT | GPIO_AF4 | GPIO_PORTB | GPIO_PIN12)
#define GPIO_I2C2_SMBA_1             (GPIO_ALT | GPIO_AF4 | GPIO_PORTA | GPIO_PIN15)
#define GPIO_I2C2_SMBA_2             (GPIO_ALT | GPIO_AF4 | GPIO_PORTB | GPIO_PIN13)

/* Inter-IC sound interfaces */

#define GPIO_I2S1_CK_1               (GPIO_ALT | GPIO_AF5 | GPIO_PORTA | GPIO_PIN5)
#define GPIO_I2S1_CK_2               (GPIO_ALT | GPIO_AF5 | GPIO_PORTB | GPIO_PIN3)
#define GPIO_I2S1_MCK_1              (GPIO_ALT | GPIO_AF5 | GPIO_PORTC | GPIO_PIN4)
#define GPIO_I2S1_SDI_1              (GPIO_ALT | GPIO_AF5 | GPIO_PORTA | GPIO_PIN6)
#define GPIO_I2S1_SDI_2              (GPIO_ALT | GPIO_AF5 | GPIO_PORTB | GPIO_PIN4)
#define GPIO_I2S1_SDO_1              (GPIO_ALT | GPIO_AF5 | GPIO_PORTA | GPIO_PIN7)
#define GPIO_I2S1_SDO_2              (GPIO_ALT | GPIO_AF5 | GPIO_PORTB | GPIO_PIN5)
#define GPIO_I2S1_SDO_3              (GPIO_ALT | GPIO_AF6 | GPIO_PORTB | GPIO_PIN15)
#define GPIO_I2S1_WS_1               (GPIO_ALT | GPIO_AF5 | GPIO_PORTA | GPIO_PIN4)
#define GPIO_I2S1_WS_2               (GPIO_ALT | GPIO_AF5 | GPIO_PORTA | GPIO_PIN15)
#define GPIO_I2S2_CK_1               (GPIO_ALT | GPIO_AF6 | GPIO_PORTA | GPIO_PIN5)
#define GPIO_I2S2_CK_2               (GPIO_ALT | GPIO_AF5 | GPIO_PORTA | GPIO_PIN9)
#define GPIO_I2S2_CK_3               (GPIO_ALT | GPIO_AF5 | GPIO_PORTA | GPIO_PIN12)
#define GPIO_I2S2_CK_4               (GPIO_ALT | GPIO_AF6 | GPIO_PORTB | GPIO_PIN2)
#define GPIO_I2S2_CK_5               (GPIO_ALT | GPIO_AF5 | GPIO_PORTB | GPIO_PIN10)
#define GPIO_I2S2_CK_6               (GPIO_ALT | GPIO_AF5 | GPIO_PORTB | GPIO_PIN13)
#define GPIO_I2S2_MCK_1              (GPIO_ALT | GPIO_AF5 | GPIO_PORTC | GPIO_PIN6)
#define GPIO_I2S2_SDI_1              (GPIO_ALT | GPIO_AF6 | GPIO_PORTA | GPIO_PIN7)
#define GPIO_I2S2_SDI_2              (GPIO_ALT | GPIO_AF5 | GPIO_PORTB | GPIO_PIN14)
#define GPIO_I2S2_SDI_3              (GPIO_ALT | GPIO_AF5 | GPIO_PORTC | GPIO_PIN2)
#define GPIO_I2S2_SDO_1              (GPIO_ALT | GPIO_AF6 | GPIO_PORTA | GPIO_PIN8)
#define GPIO_I2S2_SDO_2              (GPIO_ALT | GPIO_AF5 | GPIO_PORTB | GPIO_PIN15)
#define GPIO_I2S2_SDO_3              (GPIO_ALT | GPIO_AF5 | GPIO_PORTC | GPIO_PIN1)
#define GPIO_I2S2_SDO_4              (GPIO_ALT | GPIO_AF5 | GPIO_PORTC | GPIO_PIN3)
#define GPIO_I2S2_WS_1               (GPIO_ALT | GPIO_AF9 | GPIO_PORTA | GPIO_PIN0)
#define GPIO_I2S2_WS_2               (GPIO_ALT | GPIO_AF5 | GPIO_PORTA | GPIO_PIN3)
#define GPIO_I2S2_WS_3               (GPIO_ALT | GPIO_AF5 | GPIO_PORTA | GPIO_PIN11)
#define GPIO_I2S2_WS_4               (GPIO_ALT | GPIO_AF5 | GPIO_PORTB | GPIO_PIN1)
#define GPIO_I2S2_WS_5               (GPIO_ALT | GPIO_AF7 | GPIO_PORTB | GPIO_PIN4)
#define GPIO_I2S2_WS_6               (GPIO_ALT | GPIO_AF5 | GPIO_PORTB | GPIO_PIN9)
#define GPIO_I2S2_WS_7               (GPIO_ALT | GPIO_AF5 | GPIO_PORTB | GPIO_PIN12)
#define GPIO_I2S3_CK_1               (GPIO_ALT | GPIO_AF4 | GPIO_PORTB | GPIO_PIN1)
#define GPIO_I2S3_CK_2               (GPIO_ALT | GPIO_AF6 | GPIO_PORTB | GPIO_PIN3)
#define GPIO_I2S3_CK_3               (GPIO_ALT | GPIO_AF6 | GPIO_PORTB | GPIO_PIN7)
#define GPIO_I2S3_CK_4               (GPIO_ALT | GPIO_AF6 | GPIO_PORTB | GPIO_PIN9)
#define GPIO_I2S3_CK_5               (GPIO_ALT | GPIO_AF6 | GPIO_PORTC | GPIO_PIN10)
#define GPIO_I2S3_CK_6               (GPIO_ALT | GPIO_AF5 | GPIO_PORTE | GPIO_PIN2)
#define GPIO_I2S3_MCK_1              (GPIO_ALT | GPIO_AF6 | GPIO_PORTC | GPIO_PIN7)
#define GPIO_I2S3_SDI_1              (GPIO_ALT | GPIO_AF5 | GPIO_PORTB | GPIO_PIN0)
#define GPIO_I2S3_SDI_2              (GPIO_ALT | GPIO_AF6 | GPIO_PORTB | GPIO_PIN4)
#define GPIO_I2S3_SDI_3              (GPIO_ALT | GPIO_AF6 | GPIO_PORTB | GPIO_PIN6)
#define GPIO_I2S3_SDI_4              (GPIO_ALT | GPIO_AF6 | GPIO_PORTC | GPIO_PIN11)
#define GPIO_I2S3_SDO_1              (GPIO_ALT | GPIO_AF6 | GPIO_PORTA | GPIO_PIN3)
#define GPIO_I2S3_SDO_2              (GPIO_ALT | GPIO_AF4 | GPIO_PORTA | GPIO_PIN4)
#define GPIO_I2S3_SDO_3              (GPIO_ALT | GPIO_AF7 | GPIO_PORTB | GPIO_PIN2)
#define GPIO_I2S3_SDO_4              (GPIO_ALT | GPIO_AF7 | GPIO_PORTB | GPIO_PIN5)
#define GPIO_I2S3_SDO_5              (GPIO_ALT | GPIO_AF7 | GPIO_PORTB | GPIO_PIN15)
#define GPIO_I2S3_SDO_6              (GPIO_ALT | GPIO_AF6 | GPIO_PORTC | GPIO_PIN12)
#define GPIO_I2S3_WS_1               (GPIO_ALT | GPIO_AF6 | GPIO_PORTA | GPIO_PIN4)
#define GPIO_I2S3_WS_2               (GPIO_ALT | GPIO_AF6 | GPIO_PORTA | GPIO_PIN15)
#define GPIO_I2S3_WS_3               (GPIO_ALT | GPIO_AF6 | GPIO_PORTB | GPIO_PIN8)

/* Improved inter-integrated circuit interfaces */

#define GPIO_I3C1_SCL_1              (GPIO_ALT | GPIO_AF2 | GPIO_PORTA | GPIO_PIN9)
#define GPIO_I3C1_SCL_2              (GPIO_ALT | GPIO_AF3 | GPIO_PORTB | GPIO_PIN4)
#define GPIO_I3C1_SCL_3              (GPIO_ALT | GPIO_AF3 | GPIO_PORTB | GPIO_PIN6)
#define GPIO_I3C1_SCL_4              (GPIO_ALT | GPIO_AF3 | GPIO_PORTB | GPIO_PIN8)
#define GPIO_I3C1_SCL_5              (GPIO_ALT | GPIO_AF4 | GPIO_PORTC | GPIO_PIN10)
#define GPIO_I3C1_SDA_1              (GPIO_ALT | GPIO_AF2 | GPIO_PORTA | GPIO_PIN8)
#define GPIO_I3C1_SDA_2              (GPIO_ALT | GPIO_AF3 | GPIO_PORTB | GPIO_PIN5)
#define GPIO_I3C1_SDA_3              (GPIO_ALT | GPIO_AF3 | GPIO_PORTB | GPIO_PIN7)
#define GPIO_I3C1_SDA_4              (GPIO_ALT | GPIO_AF3 | GPIO_PORTB | GPIO_PIN9)
#define GPIO_I3C1_SDA_5              (GPIO_ALT | GPIO_AF4 | GPIO_PORTC | GPIO_PIN11)

/* Low-power timers */

#define GPIO_LPTIM1_CH1_1            (GPIO_ALT | GPIO_AF5 | GPIO_PORTB | GPIO_PIN2)
#define GPIO_LPTIM1_CH1_2            (GPIO_ALT | GPIO_AF3 | GPIO_PORTB | GPIO_PIN13)
#define GPIO_LPTIM1_CH2_1            (GPIO_ALT | GPIO_AF4 | GPIO_PORTB | GPIO_PIN4)
#define GPIO_LPTIM1_ETR_1            (GPIO_ALT | GPIO_AF3 | GPIO_PORTA | GPIO_PIN15)
#define GPIO_LPTIM1_IN1_1            (GPIO_ALT | GPIO_AF5 | GPIO_PORTA | GPIO_PIN1)
#define GPIO_LPTIM1_IN1_2            (GPIO_ALT | GPIO_AF3 | GPIO_PORTB | GPIO_PIN10)
#define GPIO_LPTIM1_IN2_1            (GPIO_ALT | GPIO_AF5 | GPIO_PORTA | GPIO_PIN2)
#define GPIO_LPTIM1_IN2_2            (GPIO_ALT | GPIO_AF1 | GPIO_PORTE | GPIO_PIN2)
#define GPIO_LPTIM1_IN2_3            (GPIO_ALT | GPIO_AF3 | GPIO_PORTH | GPIO_PIN2)

/* Low-power UART */

#define GPIO_LPUART1_CTS_1           (GPIO_ALT | GPIO_AF8 | GPIO_PORTA | GPIO_PIN7)
#define GPIO_LPUART1_CTS_2           (GPIO_ALT | GPIO_AF3 | GPIO_PORTA | GPIO_PIN11)
#define GPIO_LPUART1_CTS_3           (GPIO_ALT | GPIO_AF8 | GPIO_PORTB | GPIO_PIN4)
#define GPIO_LPUART1_RTS_DE_1        (GPIO_ALT | GPIO_AF8 | GPIO_PORTA | GPIO_PIN6)
#define GPIO_LPUART1_RTS_DE_2        (GPIO_ALT | GPIO_AF3 | GPIO_PORTA | GPIO_PIN12)
#define GPIO_LPUART1_RTS_DE_3        (GPIO_ALT | GPIO_AF8 | GPIO_PORTB | GPIO_PIN5)
#define GPIO_LPUART1_RX_1            (GPIO_ALT | GPIO_AF3 | GPIO_PORTA | GPIO_PIN2)
#define GPIO_LPUART1_RX_2            (GPIO_ALT | GPIO_AF3 | GPIO_PORTA | GPIO_PIN10)
#define GPIO_LPUART1_RX_3            (GPIO_ALT | GPIO_AF8 | GPIO_PORTB | GPIO_PIN7)
#define GPIO_LPUART1_RX_4            (GPIO_ALT | GPIO_AF8 | GPIO_PORTB | GPIO_PIN13)
#define GPIO_LPUART1_TX_1            (GPIO_ALT | GPIO_AF3 | GPIO_PORTA | GPIO_PIN3)
#define GPIO_LPUART1_TX_2            (GPIO_ALT | GPIO_AF3 | GPIO_PORTA | GPIO_PIN9)
#define GPIO_LPUART1_TX_3            (GPIO_ALT | GPIO_AF8 | GPIO_PORTB | GPIO_PIN3)
#define GPIO_LPUART1_TX_4            (GPIO_ALT | GPIO_AF8 | GPIO_PORTB | GPIO_PIN6)
#define GPIO_LPUART1_TX_5            (GPIO_ALT | GPIO_AF3 | GPIO_PORTC | GPIO_PIN3)

/* Clock outputs */

#define GPIO_LSCO_1                  (GPIO_ANALOG | GPIO_PORTB | GPIO_PIN2)
#define GPIO_MCO1_1                  (GPIO_ALT | GPIO_AF0 | GPIO_PORTA | GPIO_PIN8)
#define GPIO_MCO1_2                  (GPIO_ALT | GPIO_AF0 | GPIO_PORTH | GPIO_PIN2)
#define GPIO_MCO2_1                  (GPIO_ALT | GPIO_AF0 | GPIO_PORTA | GPIO_PIN9)
#define GPIO_MCO2_2                  (GPIO_ALT | GPIO_AF0 | GPIO_PORTC | GPIO_PIN9)

/* Power control */

#define GPIO_CSLEEP_1                (GPIO_ALT | GPIO_AF0 | GPIO_PORTC | GPIO_PIN2)
#define GPIO_CSTOP_1                 (GPIO_ALT | GPIO_AF0 | GPIO_PORTC | GPIO_PIN3)
#define GPIO_PVD_IN_1                (GPIO_ANALOG | GPIO_PORTB | GPIO_PIN15)

/* Real-time clock */

#define GPIO_RTC_OUT2_1              (GPIO_ALT | GPIO_AF0 | GPIO_PORTB | GPIO_PIN2)
#define GPIO_RTC_REFIN_1             (GPIO_ALT | GPIO_AF0 | GPIO_PORTB | GPIO_PIN15)
#define GPIO_RTC_TS_1                (GPIO_ANALOG | GPIO_PORTC | GPIO_PIN13)

/* Serial peripheral interfaces */

#define GPIO_SPI1_MISO_1             (GPIO_ALT | GPIO_AF5 | GPIO_PORTA | GPIO_PIN6)
#define GPIO_SPI1_MISO_2             (GPIO_ALT | GPIO_AF5 | GPIO_PORTB | GPIO_PIN4)
#define GPIO_SPI1_MOSI_1             (GPIO_ALT | GPIO_AF5 | GPIO_PORTA | GPIO_PIN7)
#define GPIO_SPI1_MOSI_2             (GPIO_ALT | GPIO_AF5 | GPIO_PORTB | GPIO_PIN5)
#define GPIO_SPI1_MOSI_3             (GPIO_ALT | GPIO_AF6 | GPIO_PORTB | GPIO_PIN15)
#define GPIO_SPI1_NSS_1              (GPIO_ALT | GPIO_AF5 | GPIO_PORTA | GPIO_PIN4)
#define GPIO_SPI1_NSS_2              (GPIO_ALT | GPIO_AF5 | GPIO_PORTA | GPIO_PIN15)
#define GPIO_SPI1_RDY_1              (GPIO_ALT | GPIO_AF5 | GPIO_PORTA | GPIO_PIN8)
#define GPIO_SPI1_RDY_2              (GPIO_ALT | GPIO_AF4 | GPIO_PORTB | GPIO_PIN2)
#define GPIO_SPI1_SCK_1              (GPIO_ALT | GPIO_AF5 | GPIO_PORTA | GPIO_PIN5)
#define GPIO_SPI1_SCK_2              (GPIO_ALT | GPIO_AF5 | GPIO_PORTB | GPIO_PIN3)
#define GPIO_SPI2_MISO_1             (GPIO_ALT | GPIO_AF6 | GPIO_PORTA | GPIO_PIN7)
#define GPIO_SPI2_MISO_2             (GPIO_ALT | GPIO_AF5 | GPIO_PORTB | GPIO_PIN14)
#define GPIO_SPI2_MISO_3             (GPIO_ALT | GPIO_AF5 | GPIO_PORTC | GPIO_PIN2)
#define GPIO_SPI2_MOSI_1             (GPIO_ALT | GPIO_AF6 | GPIO_PORTA | GPIO_PIN8)
#define GPIO_SPI2_MOSI_2             (GPIO_ALT | GPIO_AF5 | GPIO_PORTB | GPIO_PIN15)
#define GPIO_SPI2_MOSI_3             (GPIO_ALT | GPIO_AF5 | GPIO_PORTC | GPIO_PIN1)
#define GPIO_SPI2_MOSI_4             (GPIO_ALT | GPIO_AF5 | GPIO_PORTC | GPIO_PIN3)
#define GPIO_SPI2_NSS_1              (GPIO_ALT | GPIO_AF9 | GPIO_PORTA | GPIO_PIN0)
#define GPIO_SPI2_NSS_2              (GPIO_ALT | GPIO_AF5 | GPIO_PORTA | GPIO_PIN3)
#define GPIO_SPI2_NSS_3              (GPIO_ALT | GPIO_AF5 | GPIO_PORTA | GPIO_PIN11)
#define GPIO_SPI2_NSS_4              (GPIO_ALT | GPIO_AF5 | GPIO_PORTB | GPIO_PIN1)
#define GPIO_SPI2_NSS_5              (GPIO_ALT | GPIO_AF7 | GPIO_PORTB | GPIO_PIN4)
#define GPIO_SPI2_NSS_6              (GPIO_ALT | GPIO_AF5 | GPIO_PORTB | GPIO_PIN9)
#define GPIO_SPI2_NSS_7              (GPIO_ALT | GPIO_AF5 | GPIO_PORTB | GPIO_PIN12)
#define GPIO_SPI2_RDY_1              (GPIO_ALT | GPIO_AF5 | GPIO_PORTA | GPIO_PIN0)
#define GPIO_SPI2_RDY_2              (GPIO_ALT | GPIO_AF7 | GPIO_PORTC | GPIO_PIN0)
#define GPIO_SPI2_SCK_1              (GPIO_ALT | GPIO_AF6 | GPIO_PORTA | GPIO_PIN5)
#define GPIO_SPI2_SCK_2              (GPIO_ALT | GPIO_AF5 | GPIO_PORTA | GPIO_PIN9)
#define GPIO_SPI2_SCK_3              (GPIO_ALT | GPIO_AF5 | GPIO_PORTA | GPIO_PIN12)
#define GPIO_SPI2_SCK_4              (GPIO_ALT | GPIO_AF6 | GPIO_PORTB | GPIO_PIN2)
#define GPIO_SPI2_SCK_5              (GPIO_ALT | GPIO_AF5 | GPIO_PORTB | GPIO_PIN10)
#define GPIO_SPI2_SCK_6              (GPIO_ALT | GPIO_AF5 | GPIO_PORTB | GPIO_PIN13)
#define GPIO_SPI3_MISO_1             (GPIO_ALT | GPIO_AF5 | GPIO_PORTB | GPIO_PIN0)
#define GPIO_SPI3_MISO_2             (GPIO_ALT | GPIO_AF6 | GPIO_PORTB | GPIO_PIN4)
#define GPIO_SPI3_MISO_3             (GPIO_ALT | GPIO_AF6 | GPIO_PORTB | GPIO_PIN6)
#define GPIO_SPI3_MISO_4             (GPIO_ALT | GPIO_AF6 | GPIO_PORTC | GPIO_PIN11)
#define GPIO_SPI3_MOSI_1             (GPIO_ALT | GPIO_AF6 | GPIO_PORTA | GPIO_PIN3)
#define GPIO_SPI3_MOSI_2             (GPIO_ALT | GPIO_AF4 | GPIO_PORTA | GPIO_PIN4)
#define GPIO_SPI3_MOSI_3             (GPIO_ALT | GPIO_AF7 | GPIO_PORTB | GPIO_PIN2)
#define GPIO_SPI3_MOSI_4             (GPIO_ALT | GPIO_AF7 | GPIO_PORTB | GPIO_PIN5)
#define GPIO_SPI3_MOSI_5             (GPIO_ALT | GPIO_AF7 | GPIO_PORTB | GPIO_PIN15)
#define GPIO_SPI3_MOSI_6             (GPIO_ALT | GPIO_AF6 | GPIO_PORTC | GPIO_PIN12)
#define GPIO_SPI3_NSS_1              (GPIO_ALT | GPIO_AF6 | GPIO_PORTA | GPIO_PIN4)
#define GPIO_SPI3_NSS_2              (GPIO_ALT | GPIO_AF6 | GPIO_PORTA | GPIO_PIN15)
#define GPIO_SPI3_NSS_3              (GPIO_ALT | GPIO_AF6 | GPIO_PORTB | GPIO_PIN8)
#define GPIO_SPI3_RDY_1              (GPIO_ALT | GPIO_AF6 | GPIO_PORTA | GPIO_PIN0)
#define GPIO_SPI3_SCK_1              (GPIO_ALT | GPIO_AF4 | GPIO_PORTB | GPIO_PIN1)
#define GPIO_SPI3_SCK_2              (GPIO_ALT | GPIO_AF6 | GPIO_PORTB | GPIO_PIN3)
#define GPIO_SPI3_SCK_3              (GPIO_ALT | GPIO_AF6 | GPIO_PORTB | GPIO_PIN7)
#define GPIO_SPI3_SCK_4              (GPIO_ALT | GPIO_AF6 | GPIO_PORTB | GPIO_PIN9)
#define GPIO_SPI3_SCK_5              (GPIO_ALT | GPIO_AF6 | GPIO_PORTC | GPIO_PIN10)
#define GPIO_SPI3_SCK_6              (GPIO_ALT | GPIO_AF5 | GPIO_PORTE | GPIO_PIN2)

/* Timers */

#define GPIO_TIM1_BKIN_1             (GPIO_ALT | GPIO_AF1 | GPIO_PORTA | GPIO_PIN6)
#define GPIO_TIM1_BKIN_2             (GPIO_ALT | GPIO_AF1 | GPIO_PORTB | GPIO_PIN12)
#define GPIO_TIM1_CH1IN_1            (GPIO_ALT | GPIO_AF1 | GPIO_FLOAT | GPIO_PORTA | GPIO_PIN8)
#define GPIO_TIM1_CH1NOUT_1          (GPIO_ALT | GPIO_AF1 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN7)
#define GPIO_TIM1_CH1NOUT_2          (GPIO_ALT | GPIO_AF1 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN13)
#define GPIO_TIM1_CH1OUT_1           (GPIO_ALT | GPIO_AF1 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN8)
#define GPIO_TIM1_CH2IN_1            (GPIO_ALT | GPIO_AF1 | GPIO_FLOAT | GPIO_PORTA | GPIO_PIN9)
#define GPIO_TIM1_CH2NOUT_1          (GPIO_ALT | GPIO_AF2 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN15)
#define GPIO_TIM1_CH2NOUT_2          (GPIO_ALT | GPIO_AF1 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN0)
#define GPIO_TIM1_CH2NOUT_3          (GPIO_ALT | GPIO_AF1 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN14)
#define GPIO_TIM1_CH2OUT_1           (GPIO_ALT | GPIO_AF1 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN9)
#define GPIO_TIM1_CH3IN_1            (GPIO_ALT | GPIO_AF2 | GPIO_FLOAT | GPIO_PORTA | GPIO_PIN5)
#define GPIO_TIM1_CH3IN_2            (GPIO_ALT | GPIO_AF1 | GPIO_FLOAT | GPIO_PORTA | GPIO_PIN10)
#define GPIO_TIM1_CH3NOUT_1          (GPIO_ALT | GPIO_AF1 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN1)
#define GPIO_TIM1_CH3NOUT_2          (GPIO_ALT | GPIO_AF1 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN15)
#define GPIO_TIM1_CH3OUT_1           (GPIO_ALT | GPIO_AF2 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN5)
#define GPIO_TIM1_CH3OUT_2           (GPIO_ALT | GPIO_AF1 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN10)
#define GPIO_TIM1_CH4IN_1            (GPIO_ALT | GPIO_AF1 | GPIO_FLOAT | GPIO_PORTA | GPIO_PIN11)
#define GPIO_TIM1_CH4NOUT_1          (GPIO_ALT | GPIO_AF1 | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN5)
#define GPIO_TIM1_CH4OUT_1           (GPIO_ALT | GPIO_AF1 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN11)
#define GPIO_TIM1_ETR_1              (GPIO_ALT | GPIO_AF1 | GPIO_PORTA | GPIO_PIN12)
#define GPIO_TIM2_CH1IN_1            (GPIO_ALT | GPIO_AF1 | GPIO_FLOAT | GPIO_PORTA | GPIO_PIN0)
#define GPIO_TIM2_CH1IN_2            (GPIO_ALT | GPIO_AF1 | GPIO_FLOAT | GPIO_PORTA | GPIO_PIN5)
#define GPIO_TIM2_CH1IN_3            (GPIO_ALT | GPIO_AF1 | GPIO_FLOAT | GPIO_PORTA | GPIO_PIN15)
#define GPIO_TIM2_CH1OUT_1           (GPIO_ALT | GPIO_AF1 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN0)
#define GPIO_TIM2_CH1OUT_2           (GPIO_ALT | GPIO_AF1 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN5)
#define GPIO_TIM2_CH1OUT_3           (GPIO_ALT | GPIO_AF1 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN15)
#define GPIO_TIM2_CH2IN_1            (GPIO_ALT | GPIO_AF1 | GPIO_FLOAT | GPIO_PORTA | GPIO_PIN1)
#define GPIO_TIM2_CH2IN_2            (GPIO_ALT | GPIO_AF1 | GPIO_FLOAT | GPIO_PORTB | GPIO_PIN3)
#define GPIO_TIM2_CH2OUT_1           (GPIO_ALT | GPIO_AF1 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN1)
#define GPIO_TIM2_CH2OUT_2           (GPIO_ALT | GPIO_AF1 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN3)
#define GPIO_TIM2_CH3IN_1            (GPIO_ALT | GPIO_AF1 | GPIO_FLOAT | GPIO_PORTA | GPIO_PIN2)
#define GPIO_TIM2_CH3IN_2            (GPIO_ALT | GPIO_AF1 | GPIO_FLOAT | GPIO_PORTB | GPIO_PIN10)
#define GPIO_TIM2_CH3OUT_1           (GPIO_ALT | GPIO_AF1 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN2)
#define GPIO_TIM2_CH3OUT_2           (GPIO_ALT | GPIO_AF1 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN10)
#define GPIO_TIM2_CH4IN_1            (GPIO_ALT | GPIO_AF1 | GPIO_FLOAT | GPIO_PORTA | GPIO_PIN3)
#define GPIO_TIM2_CH4IN_2            (GPIO_ALT | GPIO_AF14 | GPIO_FLOAT | GPIO_PORTA | GPIO_PIN8)
#define GPIO_TIM2_CH4IN_3            (GPIO_ALT | GPIO_AF1 | GPIO_FLOAT | GPIO_PORTC | GPIO_PIN4)
#define GPIO_TIM2_CH4OUT_1           (GPIO_ALT | GPIO_AF1 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN3)
#define GPIO_TIM2_CH4OUT_2           (GPIO_ALT | GPIO_AF14 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN8)
#define GPIO_TIM2_CH4OUT_3           (GPIO_ALT | GPIO_AF1 | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN4)
#define GPIO_TIM2_ETR_1              (GPIO_ALT | GPIO_AF14 | GPIO_PORTA | GPIO_PIN0)
#define GPIO_TIM2_ETR_2              (GPIO_ALT | GPIO_AF14 | GPIO_PORTA | GPIO_PIN5)
#define GPIO_TIM2_ETR_3              (GPIO_ALT | GPIO_AF14 | GPIO_PORTA | GPIO_PIN15)
#define GPIO_TIM5_CH1IN_1            (GPIO_ALT | GPIO_AF2 | GPIO_FLOAT | GPIO_PORTA | GPIO_PIN0)
#define GPIO_TIM5_CH1IN_2            (GPIO_ALT | GPIO_AF2 | GPIO_FLOAT | GPIO_PORTA | GPIO_PIN6)
#define GPIO_TIM5_CH1IN_3            (GPIO_ALT | GPIO_AF2 | GPIO_FLOAT | GPIO_PORTB | GPIO_PIN4)
#define GPIO_TIM5_CH1IN_4            (GPIO_ALT | GPIO_AF2 | GPIO_FLOAT | GPIO_PORTC | GPIO_PIN6)
#define GPIO_TIM5_CH1OUT_1           (GPIO_ALT | GPIO_AF2 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN0)
#define GPIO_TIM5_CH1OUT_2           (GPIO_ALT | GPIO_AF2 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN6)
#define GPIO_TIM5_CH1OUT_3           (GPIO_ALT | GPIO_AF2 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN4)
#define GPIO_TIM5_CH1OUT_4           (GPIO_ALT | GPIO_AF2 | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN6)
#define GPIO_TIM5_CH2IN_1            (GPIO_ALT | GPIO_AF2 | GPIO_FLOAT | GPIO_PORTA | GPIO_PIN1)
#define GPIO_TIM5_CH2IN_2            (GPIO_ALT | GPIO_AF2 | GPIO_FLOAT | GPIO_PORTA | GPIO_PIN7)
#define GPIO_TIM5_CH2IN_3            (GPIO_ALT | GPIO_AF2 | GPIO_FLOAT | GPIO_PORTB | GPIO_PIN5)
#define GPIO_TIM5_CH2IN_4            (GPIO_ALT | GPIO_AF2 | GPIO_FLOAT | GPIO_PORTC | GPIO_PIN7)
#define GPIO_TIM5_CH2OUT_1           (GPIO_ALT | GPIO_AF2 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN1)
#define GPIO_TIM5_CH2OUT_2           (GPIO_ALT | GPIO_AF2 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN7)
#define GPIO_TIM5_CH2OUT_3           (GPIO_ALT | GPIO_AF2 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN5)
#define GPIO_TIM5_CH2OUT_4           (GPIO_ALT | GPIO_AF2 | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN7)
#define GPIO_TIM5_CH3IN_1            (GPIO_ALT | GPIO_AF2 | GPIO_FLOAT | GPIO_PORTA | GPIO_PIN2)
#define GPIO_TIM5_CH3IN_2            (GPIO_ALT | GPIO_AF2 | GPIO_FLOAT | GPIO_PORTB | GPIO_PIN0)
#define GPIO_TIM5_CH3IN_3            (GPIO_ALT | GPIO_AF3 | GPIO_FLOAT | GPIO_PORTB | GPIO_PIN3)
#define GPIO_TIM5_CH3IN_4            (GPIO_ALT | GPIO_AF2 | GPIO_FLOAT | GPIO_PORTC | GPIO_PIN8)
#define GPIO_TIM5_CH3OUT_1           (GPIO_ALT | GPIO_AF2 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN2)
#define GPIO_TIM5_CH3OUT_2           (GPIO_ALT | GPIO_AF2 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN0)
#define GPIO_TIM5_CH3OUT_3           (GPIO_ALT | GPIO_AF3 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN3)
#define GPIO_TIM5_CH3OUT_4           (GPIO_ALT | GPIO_AF2 | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN8)
#define GPIO_TIM5_CH4IN_1            (GPIO_ALT | GPIO_AF2 | GPIO_FLOAT | GPIO_PORTA | GPIO_PIN3)
#define GPIO_TIM5_CH4IN_2            (GPIO_ALT | GPIO_AF8 | GPIO_FLOAT | GPIO_PORTA | GPIO_PIN8)
#define GPIO_TIM5_CH4IN_3            (GPIO_ALT | GPIO_AF2 | GPIO_FLOAT | GPIO_PORTB | GPIO_PIN1)
#define GPIO_TIM5_CH4IN_4            (GPIO_ALT | GPIO_AF2 | GPIO_FLOAT | GPIO_PORTC | GPIO_PIN9)
#define GPIO_TIM5_CH4OUT_1           (GPIO_ALT | GPIO_AF2 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN3)
#define GPIO_TIM5_CH4OUT_2           (GPIO_ALT | GPIO_AF8 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN8)
#define GPIO_TIM5_CH4OUT_3           (GPIO_ALT | GPIO_AF2 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN1)
#define GPIO_TIM5_CH4OUT_4           (GPIO_ALT | GPIO_AF2 | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN9)
#define GPIO_TIM5_ETR_1              (GPIO_ALT | GPIO_AF2 | GPIO_PORTA | GPIO_PIN4)
#define GPIO_TIM5_ETR_2              (GPIO_ALT | GPIO_AF8 | GPIO_PORTA | GPIO_PIN9)
#define GPIO_TIM8_BKIN_1             (GPIO_ALT | GPIO_AF3 | GPIO_PORTA | GPIO_PIN1)
#define GPIO_TIM8_BKIN_2             (GPIO_ALT | GPIO_AF3 | GPIO_PORTA | GPIO_PIN6)
#define GPIO_TIM8_BKIN_3             (GPIO_ALT | GPIO_AF3 | GPIO_PORTC | GPIO_PIN4)
#define GPIO_TIM8_BKIN2_1            (GPIO_ALT | GPIO_AF3 | GPIO_PORTA | GPIO_PIN8)
#define GPIO_TIM8_BKIN2_2            (GPIO_ALT | GPIO_AF3 | GPIO_PORTC | GPIO_PIN5)
#define GPIO_TIM8_CH1IN_1            (GPIO_ALT | GPIO_AF13 | GPIO_FLOAT | GPIO_PORTB | GPIO_PIN3)
#define GPIO_TIM8_CH1IN_2            (GPIO_ALT | GPIO_AF2 | GPIO_FLOAT | GPIO_PORTB | GPIO_PIN10)
#define GPIO_TIM8_CH1IN_3            (GPIO_ALT | GPIO_AF3 | GPIO_FLOAT | GPIO_PORTC | GPIO_PIN6)
#define GPIO_TIM8_CH1NOUT_1          (GPIO_ALT | GPIO_AF3 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN5)
#define GPIO_TIM8_CH1NOUT_2          (GPIO_ALT | GPIO_AF3 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN7)
#define GPIO_TIM8_CH1NOUT_3          (GPIO_ALT | GPIO_AF3 | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN10)
#define GPIO_TIM8_CH1OUT_1           (GPIO_ALT | GPIO_AF13 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN3)
#define GPIO_TIM8_CH1OUT_2           (GPIO_ALT | GPIO_AF2 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN10)
#define GPIO_TIM8_CH1OUT_3           (GPIO_ALT | GPIO_AF3 | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN6)
#define GPIO_TIM8_CH2IN_1            (GPIO_ALT | GPIO_AF13 | GPIO_FLOAT | GPIO_PORTB | GPIO_PIN4)
#define GPIO_TIM8_CH2IN_2            (GPIO_ALT | GPIO_AF2 | GPIO_FLOAT | GPIO_PORTB | GPIO_PIN13)
#define GPIO_TIM8_CH2IN_3            (GPIO_ALT | GPIO_AF3 | GPIO_FLOAT | GPIO_PORTC | GPIO_PIN7)
#define GPIO_TIM8_CH2NOUT_1          (GPIO_ALT | GPIO_AF13 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN9)
#define GPIO_TIM8_CH2NOUT_2          (GPIO_ALT | GPIO_AF3 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN0)
#define GPIO_TIM8_CH2NOUT_3          (GPIO_ALT | GPIO_AF3 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN14)
#define GPIO_TIM8_CH2NOUT_4          (GPIO_ALT | GPIO_AF3 | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN11)
#define GPIO_TIM8_CH2OUT_1           (GPIO_ALT | GPIO_AF13 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN4)
#define GPIO_TIM8_CH2OUT_2           (GPIO_ALT | GPIO_AF2 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN13)
#define GPIO_TIM8_CH2OUT_3           (GPIO_ALT | GPIO_AF3 | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN7)
#define GPIO_TIM8_CH3IN_1            (GPIO_ALT | GPIO_AF13 | GPIO_FLOAT | GPIO_PORTB | GPIO_PIN5)
#define GPIO_TIM8_CH3IN_2            (GPIO_ALT | GPIO_AF2 | GPIO_FLOAT | GPIO_PORTB | GPIO_PIN12)
#define GPIO_TIM8_CH3IN_3            (GPIO_ALT | GPIO_AF3 | GPIO_FLOAT | GPIO_PORTC | GPIO_PIN8)
#define GPIO_TIM8_CH3NOUT_1          (GPIO_ALT | GPIO_AF3 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN1)
#define GPIO_TIM8_CH3NOUT_2          (GPIO_ALT | GPIO_AF3 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN15)
#define GPIO_TIM8_CH3NOUT_3          (GPIO_ALT | GPIO_AF3 | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN12)
#define GPIO_TIM8_CH3OUT_1           (GPIO_ALT | GPIO_AF13 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN5)
#define GPIO_TIM8_CH3OUT_2           (GPIO_ALT | GPIO_AF2 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN12)
#define GPIO_TIM8_CH3OUT_3           (GPIO_ALT | GPIO_AF3 | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN8)
#define GPIO_TIM8_CH4IN_1            (GPIO_ALT | GPIO_AF13 | GPIO_FLOAT | GPIO_PORTB | GPIO_PIN6)
#define GPIO_TIM8_CH4IN_2            (GPIO_ALT | GPIO_AF3 | GPIO_FLOAT | GPIO_PORTC | GPIO_PIN9)
#define GPIO_TIM8_CH4NOUT_1          (GPIO_ALT | GPIO_AF13 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN15)
#define GPIO_TIM8_CH4NOUT_2          (GPIO_ALT | GPIO_AF3 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN2)
#define GPIO_TIM8_CH4OUT_1           (GPIO_ALT | GPIO_AF13 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN6)
#define GPIO_TIM8_CH4OUT_2           (GPIO_ALT | GPIO_AF3 | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN9)
#define GPIO_TIM8_ETR_1              (GPIO_ALT | GPIO_AF3 | GPIO_PORTA | GPIO_PIN0)
#define GPIO_TIM12_CH1IN_1           (GPIO_ALT | GPIO_AF2 | GPIO_FLOAT | GPIO_PORTB | GPIO_PIN14)
#define GPIO_TIM12_CH1IN_2           (GPIO_ALT | GPIO_AF2 | GPIO_FLOAT | GPIO_PORTC | GPIO_PIN14)
#define GPIO_TIM12_CH1OUT_1          (GPIO_ALT | GPIO_AF2 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN14)
#define GPIO_TIM12_CH1OUT_2          (GPIO_ALT | GPIO_AF2 | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN14)
#define GPIO_TIM12_CH2IN_1           (GPIO_ALT | GPIO_AF2 | GPIO_FLOAT | GPIO_PORTB | GPIO_PIN15)
#define GPIO_TIM12_CH2IN_2           (GPIO_ALT | GPIO_AF2 | GPIO_FLOAT | GPIO_PORTC | GPIO_PIN15)
#define GPIO_TIM12_CH2OUT_1          (GPIO_ALT | GPIO_AF2 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN15)
#define GPIO_TIM12_CH2OUT_2          (GPIO_ALT | GPIO_AF2 | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN15)
#define GPIO_TIM15_BKIN_1            (GPIO_ALT | GPIO_AF4 | GPIO_PORTA | GPIO_PIN0)
#define GPIO_TIM15_BKIN_2            (GPIO_ALT | GPIO_AF4 | GPIO_PORTD | GPIO_PIN2)
#define GPIO_TIM15_CH1IN_1           (GPIO_ALT | GPIO_AF4 | GPIO_FLOAT | GPIO_PORTA | GPIO_PIN2)
#define GPIO_TIM15_CH1IN_2           (GPIO_ALT | GPIO_AF4 | GPIO_FLOAT | GPIO_PORTA | GPIO_PIN7)
#define GPIO_TIM15_CH1IN_3           (GPIO_ALT | GPIO_AF2 | GPIO_FLOAT | GPIO_PORTC | GPIO_PIN12)
#define GPIO_TIM15_CH1NOUT_1         (GPIO_ALT | GPIO_AF4 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN1)
#define GPIO_TIM15_CH1NOUT_2         (GPIO_ALT | GPIO_AF4 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN9)
#define GPIO_TIM15_CH1OUT_1          (GPIO_ALT | GPIO_AF4 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN2)
#define GPIO_TIM15_CH1OUT_2          (GPIO_ALT | GPIO_AF4 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN7)
#define GPIO_TIM15_CH1OUT_3          (GPIO_ALT | GPIO_AF2 | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN12)
#define GPIO_TIM15_CH2IN_1           (GPIO_ALT | GPIO_AF4 | GPIO_FLOAT | GPIO_PORTA | GPIO_PIN3)
#define GPIO_TIM15_CH2IN_2           (GPIO_ALT | GPIO_AF4 | GPIO_FLOAT | GPIO_PORTA | GPIO_PIN8)
#define GPIO_TIM15_CH2OUT_1          (GPIO_ALT | GPIO_AF4 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN3)
#define GPIO_TIM15_CH2OUT_2          (GPIO_ALT | GPIO_AF4 | GPIO_PUSHPULL | GPIO_PORTA | GPIO_PIN8)
#define GPIO_TIM16_BKIN_1            (GPIO_ALT | GPIO_AF10 | GPIO_PORTB | GPIO_PIN4)
#define GPIO_TIM16_BKIN_2            (GPIO_ALT | GPIO_AF10 | GPIO_PORTC | GPIO_PIN0)
#define GPIO_TIM16_CH1IN_1           (GPIO_ALT | GPIO_AF10 | GPIO_FLOAT | GPIO_PORTB | GPIO_PIN7)
#define GPIO_TIM16_CH1IN_2           (GPIO_ALT | GPIO_AF10 | GPIO_FLOAT | GPIO_PORTC | GPIO_PIN4)
#define GPIO_TIM16_CH1NOUT_1         (GPIO_ALT | GPIO_AF10 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN6)
#define GPIO_TIM16_CH1NOUT_2         (GPIO_ALT | GPIO_AF10 | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN5)
#define GPIO_TIM16_CH1OUT_1          (GPIO_ALT | GPIO_AF10 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN7)
#define GPIO_TIM16_CH1OUT_2          (GPIO_ALT | GPIO_AF10 | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN4)
#define GPIO_TIM17_BKIN_1            (GPIO_ALT | GPIO_AF1 | GPIO_PORTB | GPIO_PIN5)
#define GPIO_TIM17_CH1IN_1           (GPIO_ALT | GPIO_AF1 | GPIO_FLOAT | GPIO_PORTB | GPIO_PIN8)
#define GPIO_TIM17_CH1IN_2           (GPIO_ALT | GPIO_AF1 | GPIO_FLOAT | GPIO_PORTC | GPIO_PIN2)
#define GPIO_TIM17_CH1NOUT_1         (GPIO_ALT | GPIO_AF1 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN7)
#define GPIO_TIM17_CH1NOUT_2         (GPIO_ALT | GPIO_AF1 | GPIO_PUSHPULL | GPIO_PORTH | GPIO_PIN2)
#define GPIO_TIM17_CH1OUT_1          (GPIO_ALT | GPIO_AF1 | GPIO_PUSHPULL | GPIO_PORTB | GPIO_PIN8)
#define GPIO_TIM17_CH1OUT_2          (GPIO_ALT | GPIO_AF1 | GPIO_PUSHPULL | GPIO_PORTC | GPIO_PIN2)

/* Universal asynchronous receiver/transmitters */

#define GPIO_UART4_CTS_1             (GPIO_ALT | GPIO_AF8 | GPIO_PORTB | GPIO_PIN0)
#define GPIO_UART4_CTS_2             (GPIO_ALT | GPIO_AF8 | GPIO_PORTB | GPIO_PIN15)
#define GPIO_UART4_RTS_DE_1          (GPIO_ALT | GPIO_AF8 | GPIO_PORTA | GPIO_PIN15)
#define GPIO_UART4_RTS_DE_2          (GPIO_ALT | GPIO_AF8 | GPIO_PORTB | GPIO_PIN14)
#define GPIO_UART4_RX_1              (GPIO_ALT | GPIO_AF8 | GPIO_PORTA | GPIO_PIN1)
#define GPIO_UART4_RX_2              (GPIO_ALT | GPIO_AF6 | GPIO_PORTA | GPIO_PIN11)
#define GPIO_UART4_RX_3              (GPIO_ALT | GPIO_AF8 | GPIO_PORTB | GPIO_PIN8)
#define GPIO_UART4_RX_4              (GPIO_ALT | GPIO_AF8 | GPIO_PORTC | GPIO_PIN11)
#define GPIO_UART4_TX_1              (GPIO_ALT | GPIO_AF8 | GPIO_PORTA | GPIO_PIN0)
#define GPIO_UART4_TX_2              (GPIO_ALT | GPIO_AF6 | GPIO_PORTA | GPIO_PIN12)
#define GPIO_UART4_TX_3              (GPIO_ALT | GPIO_AF8 | GPIO_PORTB | GPIO_PIN9)
#define GPIO_UART4_TX_4              (GPIO_ALT | GPIO_AF8 | GPIO_PORTC | GPIO_PIN10)
#define GPIO_UART5_CTS_1             (GPIO_ALT | GPIO_AF14 | GPIO_PORTB | GPIO_PIN4)
#define GPIO_UART5_CTS_2             (GPIO_ALT | GPIO_AF8 | GPIO_PORTC | GPIO_PIN9)
#define GPIO_UART5_RTS_DE_1          (GPIO_ALT | GPIO_AF14 | GPIO_PORTB | GPIO_PIN3)
#define GPIO_UART5_RTS_DE_2          (GPIO_ALT | GPIO_AF8 | GPIO_PORTC | GPIO_PIN8)
#define GPIO_UART5_RX_1              (GPIO_ALT | GPIO_AF14 | GPIO_PORTB | GPIO_PIN5)
#define GPIO_UART5_RX_2              (GPIO_ALT | GPIO_AF14 | GPIO_PORTB | GPIO_PIN12)
#define GPIO_UART5_RX_3              (GPIO_ALT | GPIO_AF14 | GPIO_PORTB | GPIO_PIN15)
#define GPIO_UART5_RX_4              (GPIO_ALT | GPIO_AF8 | GPIO_PORTD | GPIO_PIN2)
#define GPIO_UART5_TX_1              (GPIO_ALT | GPIO_AF14 | GPIO_PORTB | GPIO_PIN6)
#define GPIO_UART5_TX_2              (GPIO_ALT | GPIO_AF14 | GPIO_PORTB | GPIO_PIN13)
#define GPIO_UART5_TX_3              (GPIO_ALT | GPIO_AF8 | GPIO_PORTC | GPIO_PIN12)

/* Universal synchronous/asynchronous receiver/transmitters */

#define GPIO_USART1_CK_1             (GPIO_ALT | GPIO_AF7 | GPIO_PORTA | GPIO_PIN8)
#define GPIO_USART1_CTS_1            (GPIO_ALT | GPIO_AF7 | GPIO_PORTA | GPIO_PIN5)
#define GPIO_USART1_CTS_2            (GPIO_ALT | GPIO_AF7 | GPIO_PORTA | GPIO_PIN11)
#define GPIO_USART1_NSS_1            (GPIO_ALT | GPIO_AF7 | GPIO_PORTA | GPIO_PIN5)
#define GPIO_USART1_NSS_2            (GPIO_ALT | GPIO_AF7 | GPIO_PORTA | GPIO_PIN11)
#define GPIO_USART1_RTS_DE_1         (GPIO_ALT | GPIO_AF7 | GPIO_PORTA | GPIO_PIN12)
#define GPIO_USART1_RX_1             (GPIO_ALT | GPIO_AF7 | GPIO_PORTA | GPIO_PIN7)
#define GPIO_USART1_RX_2             (GPIO_ALT | GPIO_AF7 | GPIO_PORTA | GPIO_PIN10)
#define GPIO_USART1_RX_3             (GPIO_ALT | GPIO_AF7 | GPIO_PORTB | GPIO_PIN7)
#define GPIO_USART1_RX_4             (GPIO_ALT | GPIO_AF4 | GPIO_PORTB | GPIO_PIN15)
#define GPIO_USART1_TX_1             (GPIO_ALT | GPIO_AF7 | GPIO_PORTA | GPIO_PIN6)
#define GPIO_USART1_TX_2             (GPIO_ALT | GPIO_AF7 | GPIO_PORTA | GPIO_PIN9)
#define GPIO_USART1_TX_3             (GPIO_ALT | GPIO_AF11 | GPIO_PORTA | GPIO_PIN15)
#define GPIO_USART1_TX_4             (GPIO_ALT | GPIO_AF7 | GPIO_PORTB | GPIO_PIN6)
#define GPIO_USART1_TX_5             (GPIO_ALT | GPIO_AF4 | GPIO_PORTB | GPIO_PIN14)
#define GPIO_USART2_CK_1             (GPIO_ALT | GPIO_AF7 | GPIO_PORTA | GPIO_PIN4)
#define GPIO_USART2_CK_2             (GPIO_ALT | GPIO_AF7 | GPIO_PORTA | GPIO_PIN15)
#define GPIO_USART2_CTS_1            (GPIO_ALT | GPIO_AF7 | GPIO_PORTA | GPIO_PIN0)
#define GPIO_USART2_NSS_1            (GPIO_ALT | GPIO_AF7 | GPIO_PORTA | GPIO_PIN0)
#define GPIO_USART2_RTS_DE_1         (GPIO_ALT | GPIO_AF7 | GPIO_PORTA | GPIO_PIN1)
#define GPIO_USART2_RX_1             (GPIO_ALT | GPIO_AF7 | GPIO_PORTA | GPIO_PIN3)
#define GPIO_USART2_RX_2             (GPIO_ALT | GPIO_AF4 | GPIO_PORTA | GPIO_PIN12)
#define GPIO_USART2_TX_1             (GPIO_ALT | GPIO_AF7 | GPIO_PORTA | GPIO_PIN2)
#define GPIO_USART2_TX_2             (GPIO_ALT | GPIO_AF4 | GPIO_PORTA | GPIO_PIN11)
#define GPIO_USART2_TX_3             (GPIO_ALT | GPIO_AF7 | GPIO_PORTB | GPIO_PIN0)
#define GPIO_USART3_CK_1             (GPIO_ALT | GPIO_AF11 | GPIO_PORTB | GPIO_PIN5)
#define GPIO_USART3_CK_2             (GPIO_ALT | GPIO_AF7 | GPIO_PORTB | GPIO_PIN12)
#define GPIO_USART3_CK_3             (GPIO_ALT | GPIO_AF7 | GPIO_PORTC | GPIO_PIN12)
#define GPIO_USART3_CTS_1            (GPIO_ALT | GPIO_AF11 | GPIO_PORTB | GPIO_PIN6)
#define GPIO_USART3_CTS_2            (GPIO_ALT | GPIO_AF7 | GPIO_PORTB | GPIO_PIN13)
#define GPIO_USART3_NSS_1            (GPIO_ALT | GPIO_AF11 | GPIO_PORTB | GPIO_PIN6)
#define GPIO_USART3_NSS_2            (GPIO_ALT | GPIO_AF7 | GPIO_PORTB | GPIO_PIN13)
#define GPIO_USART3_RTS_DE_1         (GPIO_ALT | GPIO_AF11 | GPIO_PORTB | GPIO_PIN7)
#define GPIO_USART3_RTS_DE_2         (GPIO_ALT | GPIO_AF7 | GPIO_PORTB | GPIO_PIN14)
#define GPIO_USART3_RX_1             (GPIO_ALT | GPIO_AF7 | GPIO_PORTB | GPIO_PIN1)
#define GPIO_USART3_RX_2             (GPIO_ALT | GPIO_AF11 | GPIO_PORTB | GPIO_PIN4)
#define GPIO_USART3_RX_3             (GPIO_ALT | GPIO_AF7 | GPIO_PORTC | GPIO_PIN4)
#define GPIO_USART3_RX_4             (GPIO_ALT | GPIO_AF7 | GPIO_PORTC | GPIO_PIN11)
#define GPIO_USART3_TX_1             (GPIO_ALT | GPIO_AF11 | GPIO_PORTB | GPIO_PIN3)
#define GPIO_USART3_TX_2             (GPIO_ALT | GPIO_AF7 | GPIO_PORTB | GPIO_PIN10)
#define GPIO_USART3_TX_3             (GPIO_ALT | GPIO_AF7 | GPIO_PORTC | GPIO_PIN10)

/* USB full-speed interface */

#define GPIO_USB_DM_1                (GPIO_ANALOG | GPIO_PORTA | GPIO_PIN11)
#define GPIO_USB_DP_1                (GPIO_ANALOG | GPIO_PORTA | GPIO_PIN12)

#endif /* __ARCH_ARM_SRC_STM32C5_HARDWARE_STM32C5XX_PINMAP_H */
