############################################################################
# tools/imxrt1180/Makefile.host
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.  The
# ASF licenses this file to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance with the
# License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
# License for the specific language governing permissions and limitations
# under the License.
#
############################################################################

-include $(TOPDIR)/Make.defs
all: mkahab
default: mkahab
.PHONY: clean

# Add CFLAGS=-g on the make command line to build debug versions

CFLAGS = -g -O2 -Wall -Wextra -std=c99

# mkahab - assemble the unsigned RT1180 AHAB container + flash.bin
#          entirely natively (no Python/pip/network dependency); see
#          mkahab.c for details.

mkahab: mkahab.c sha256.c sha256.h
	@gcc $(CFLAGS) -o mkahab mkahab.c sha256.c

clean:
ifneq ($(CONFIG_WINDOWS_NATIVE),y)
	$(Q) rm -rf *.dSYM
endif
	$(call DELFILE, mkahab)
	$(call DELFILE, mkahab.exe)
	$(call CLEAN)
