/****************************************************************************
 * arch/arm/src/n32h7/hardware/n32h76x_dmamux.h
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 ****************************************************************************/

 #ifndef __ARCH_ARM_SRC_N32H7_HARDWARE_N32H76X_DMAMUX_H
 #define __ARCH_ARM_SRC_N32H7_HARDWARE_N32H76X_DMAMUX_H

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <nuttx/config.h>
#include "n32h7_dma.h"
#include "n32h7_dmamux.h"

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* ==========================================================================
 * DMAMUX1 Request Mapping (REQ)
 * ==========================================================================
 */

/* Internal Request Generators */
#define DMAMUX1_REQ_GEN0        1
#define DMAMUX1_REQ_GEN1        2
#define DMAMUX1_REQ_GEN2        3
#define DMAMUX1_REQ_GEN3        4
#define DMAMUX1_REQ_GEN4        5
#define DMAMUX1_REQ_GEN5        6
#define DMAMUX1_REQ_GEN6        7
#define DMAMUX1_REQ_GEN7        8

/* ADCs */
#define DMAMUX1_REQ_ADC1        9
#define DMAMUX1_REQ_ADC2        10
#define DMAMUX1_REQ_ADC3        11

/* SHRTIM */
#define DMAMUX1_REQ_SHRTIM1_DMA0 12
#define DMAMUX1_REQ_SHRTIM1_DMA1 13
#define DMAMUX1_REQ_SHRTIM1_DMA2 14
#define DMAMUX1_REQ_SHRTIM1_DMA3 15
#define DMAMUX1_REQ_SHRTIM1_DMA4 16
#define DMAMUX1_REQ_SHRTIM1_DMA5 17
#define DMAMUX1_REQ_SHRTIM1_DMA6 18
#define DMAMUX1_REQ_SHRTIM2_DMA0 19
#define DMAMUX1_REQ_SHRTIM2_DMA1 20
#define DMAMUX1_REQ_SHRTIM2_DMA2 21
#define DMAMUX1_REQ_SHRTIM2_DMA3 22
#define DMAMUX1_REQ_SHRTIM2_DMA4 23
#define DMAMUX1_REQ_SHRTIM2_DMA5 24
#define DMAMUX1_REQ_SHRTIM2_DMA6 25

/* ATIM */
#define DMAMUX1_REQ_ATIM1_UP    26
#define DMAMUX1_REQ_ATIM1_CH1   27
#define DMAMUX1_REQ_ATIM1_CH2   28
#define DMAMUX1_REQ_ATIM1_CH3   29
#define DMAMUX1_REQ_ATIM1_CH4   30
#define DMAMUX1_REQ_ATIM1_COM   31
#define DMAMUX1_REQ_ATIM1_TRG   32
#define DMAMUX1_REQ_ATIM2_UP    33
#define DMAMUX1_REQ_ATIM2_CH1   34
#define DMAMUX1_REQ_ATIM2_CH2   35
#define DMAMUX1_REQ_ATIM2_CH3   36
#define DMAMUX1_REQ_ATIM2_CH4   37
#define DMAMUX1_REQ_ATIM2_COM   38
#define DMAMUX1_REQ_ATIM2_TRG   39
#define DMAMUX1_REQ_ATIM3_UP    40
#define DMAMUX1_REQ_ATIM3_CH1   41
#define DMAMUX1_REQ_ATIM3_CH2   42
#define DMAMUX1_REQ_ATIM3_CH3   43
#define DMAMUX1_REQ_ATIM3_CH4   44
#define DMAMUX1_REQ_ATIM3_COM   45
#define DMAMUX1_REQ_ATIM3_TRG   46
#define DMAMUX1_REQ_ATIM4_UP    47
#define DMAMUX1_REQ_ATIM4_CH1   48
#define DMAMUX1_REQ_ATIM4_CH2   49
#define DMAMUX1_REQ_ATIM4_CH3   50
#define DMAMUX1_REQ_ATIM4_CH4   51
#define DMAMUX1_REQ_ATIM4_COM   52
#define DMAMUX1_REQ_ATIM4_TRG   53

/* GTIMA */
#define DMAMUX1_REQ_GTIMA1_CH1  54
#define DMAMUX1_REQ_GTIMA1_CH2  55
#define DMAMUX1_REQ_GTIMA1_CH3  56
#define DMAMUX1_REQ_GTIMA1_CH4  57
#define DMAMUX1_REQ_GTIMA1_TRG  58
#define DMAMUX1_REQ_GTIMA1_UP   59
#define DMAMUX1_REQ_GTIMA2_CH1  60
#define DMAMUX1_REQ_GTIMA2_CH2  61
#define DMAMUX1_REQ_GTIMA2_CH3  62
#define DMAMUX1_REQ_GTIMA2_CH4  63
#define DMAMUX1_REQ_GTIMA2_TRG  64
#define DMAMUX1_REQ_GTIMA2_UP   65
#define DMAMUX1_REQ_GTIMA3_CH1  66
#define DMAMUX1_REQ_GTIMA3_CH2  67
#define DMAMUX1_REQ_GTIMA3_CH3  68
#define DMAMUX1_REQ_GTIMA3_CH4  69
#define DMAMUX1_REQ_GTIMA3_TRG  70
#define DMAMUX1_REQ_GTIMA3_UP   71
#define DMAMUX1_REQ_GTIMA4_CH1  72
#define DMAMUX1_REQ_GTIMA4_CH2  73
#define DMAMUX1_REQ_GTIMA4_CH3  74
#define DMAMUX1_REQ_GTIMA4_CH4  75
#define DMAMUX1_REQ_GTIMA4_TRG  76
#define DMAMUX1_REQ_GTIMA4_UP   77
#define DMAMUX1_REQ_GTIMA5_CH1  78
#define DMAMUX1_REQ_GTIMA5_CH2  79
#define DMAMUX1_REQ_GTIMA5_CH3  80
#define DMAMUX1_REQ_GTIMA5_CH4  81
#define DMAMUX1_REQ_GTIMA5_TRG  82
#define DMAMUX1_REQ_GTIMA5_UP   83
#define DMAMUX1_REQ_GTIMA6_CH1  84
#define DMAMUX1_REQ_GTIMA6_CH2  85
#define DMAMUX1_REQ_GTIMA6_CH3  86
#define DMAMUX1_REQ_GTIMA6_CH4  87
#define DMAMUX1_REQ_GTIMA6_TRG  88
#define DMAMUX1_REQ_GTIMA6_UP   89
#define DMAMUX1_REQ_GTIMA7_CH1  90
#define DMAMUX1_REQ_GTIMA7_CH2  91
#define DMAMUX1_REQ_GTIMA7_CH3  92
#define DMAMUX1_REQ_GTIMA7_CH4  93
#define DMAMUX1_REQ_GTIMA7_TRG  94
#define DMAMUX1_REQ_GTIMA7_UP   95

/* GTIMB */
#define DMAMUX1_REQ_GTIMB1_CH1  96
#define DMAMUX1_REQ_GTIMB1_CH2  97
#define DMAMUX1_REQ_GTIMB1_CH3  98
#define DMAMUX1_REQ_GTIMB1_CH4  99
#define DMAMUX1_REQ_GTIMB1_TRG  100
#define DMAMUX1_REQ_GTIMB1_UP   101
#define DMAMUX1_REQ_GTIMB2_CH1  102
#define DMAMUX1_REQ_GTIMB2_CH2  103
#define DMAMUX1_REQ_GTIMB2_CH3  104
#define DMAMUX1_REQ_GTIMB2_CH4  105
#define DMAMUX1_REQ_GTIMB2_TRG  106
#define DMAMUX1_REQ_GTIMB2_UP   107
#define DMAMUX1_REQ_GTIMB3_CH1  108
#define DMAMUX1_REQ_GTIMB3_CH2  109
#define DMAMUX1_REQ_GTIMB3_CH3  110
#define DMAMUX1_REQ_GTIMB3_CH4  111
#define DMAMUX1_REQ_GTIMB3_TRG  112
#define DMAMUX1_REQ_GTIMB3_UP   113

/* I2C */
#define DMAMUX1_REQ_I2C1_RX     114
#define DMAMUX1_REQ_I2C1_TX     115
#define DMAMUX1_REQ_I2C2_RX     116
#define DMAMUX1_REQ_I2C2_TX     117
#define DMAMUX1_REQ_I2C3_RX     118
#define DMAMUX1_REQ_I2C3_TX     119
#define DMAMUX1_REQ_I2C4_RX     120
#define DMAMUX1_REQ_I2C4_TX     121
#define DMAMUX1_REQ_I2C5_RX     122
#define DMAMUX1_REQ_I2C5_TX     123
#define DMAMUX1_REQ_I2C6_RX     124
#define DMAMUX1_REQ_I2C6_TX     125
#define DMAMUX1_REQ_I2C7_RX     126
#define DMAMUX1_REQ_I2C7_TX     127
#define DMAMUX1_REQ_I2C8_RX     128
#define DMAMUX1_REQ_I2C8_TX     129
#define DMAMUX1_REQ_I2C9_RX     130
#define DMAMUX1_REQ_I2C9_TX     131
#define DMAMUX1_REQ_I2C10_RX    132
#define DMAMUX1_REQ_I2C10_TX    133

/* USART */
#define DMAMUX1_REQ_USART1_RX   134
#define DMAMUX1_REQ_USART1_TX   135
#define DMAMUX1_REQ_USART2_RX   136
#define DMAMUX1_REQ_USART2_TX   137
#define DMAMUX1_REQ_USART3_RX   138
#define DMAMUX1_REQ_USART3_TX   139
#define DMAMUX1_REQ_USART4_RX   140
#define DMAMUX1_REQ_USART4_TX   141
#define DMAMUX1_REQ_USART5_RX   142
#define DMAMUX1_REQ_USART5_TX   143
#define DMAMUX1_REQ_USART6_RX   144
#define DMAMUX1_REQ_USART6_TX   145
#define DMAMUX1_REQ_USART7_RX   146
#define DMAMUX1_REQ_USART7_TX   147
#define DMAMUX1_REQ_USART8_RX   148
#define DMAMUX1_REQ_USART8_TX   149

/* UART */
#define DMAMUX1_REQ_UART9_RX    150
#define DMAMUX1_REQ_UART9_TX    151
#define DMAMUX1_REQ_UART10_RX   152
#define DMAMUX1_REQ_UART10_TX   153
#define DMAMUX1_REQ_UART11_RX   154
#define DMAMUX1_REQ_UART11_TX   155
#define DMAMUX1_REQ_UART12_RX   156
#define DMAMUX1_REQ_UART12_TX   157
#define DMAMUX1_REQ_UART13_RX   158
#define DMAMUX1_REQ_UART13_TX   159
#define DMAMUX1_REQ_UART14_RX   160
#define DMAMUX1_REQ_UART14_TX   161
#define DMAMUX1_REQ_UART15_RX   162
#define DMAMUX1_REQ_UART15_TX   163

/* SPI */
#define DMAMUX1_REQ_SPI1_RX     164
#define DMAMUX1_REQ_SPI1_TX     173
#define DMAMUX1_REQ_SPI2_RX     166
#define DMAMUX1_REQ_SPI2_TX     175
#define DMAMUX1_REQ_SPI3_RX     168
#define DMAMUX1_REQ_SPI3_TX     177
#define DMAMUX1_REQ_SPI4_RX     170
#define DMAMUX1_REQ_SPI4_TX     179
#define DMAMUX1_REQ_SPI5_RX     172
#define DMAMUX1_REQ_SPI5_TX     181
#define DMAMUX1_REQ_SPI6_RX     174
#define DMAMUX1_REQ_SPI6_TX     183
#define DMAMUX1_REQ_SPI7_RX     176
#define DMAMUX1_REQ_SPI7_TX     185

/* I2S */
#define DMAMUX1_REQ_I2S1_RX     165
#define DMAMUX1_REQ_I2S1_TX     174
#define DMAMUX1_REQ_I2S2_RX     167
#define DMAMUX1_REQ_I2S2_TX     176
#define DMAMUX1_REQ_I2S3_RX     169
#define DMAMUX1_REQ_I2S3_TX     178
#define DMAMUX1_REQ_I2S4_RX     171
#define DMAMUX1_REQ_I2S4_TX     180

/* LPUART */
#define DMAMUX1_REQ_LPUART1_RX  186
#define DMAMUX1_REQ_LPUART1_TX  187
#define DMAMUX1_REQ_LPUART2_RX  188
#define DMAMUX1_REQ_LPUART2_TX  189

/* DSMU */
#define DMAMUX1_REQ_DSMU0       192
#define DMAMUX1_REQ_DSMU1       193
#define DMAMUX1_REQ_DSMU2       194
#define DMAMUX1_REQ_DSMU3       195

/* FDCAN */
#define DMAMUX1_REQ_FDCAN1      196
#define DMAMUX1_REQ_FDCAN2      197
#define DMAMUX1_REQ_FDCAN3      198
#define DMAMUX1_REQ_FDCAN4      199
#define DMAMUX1_REQ_FDCAN5      200
#define DMAMUX1_REQ_FDCAN6      201
#define DMAMUX1_REQ_FDCAN7      202
#define DMAMUX1_REQ_FDCAN8      203

/* CORDIC */
#define DMAMUX1_REQ_CORDIC_RD   204
#define DMAMUX1_REQ_CORDIC_WR   205

/* FMAU */
#define DMAMUX1_REQ_FMAU_RD     206
#define DMAMUX1_REQ_FMAU_WR     207

/* BTIM */
#define DMAMUX1_REQ_BTIM1       208
#define DMAMUX1_REQ_BTIM2       209
#define DMAMUX1_REQ_BTIM3       210
#define DMAMUX1_REQ_BTIM4       211

/* GTIMB */
#define DMAMUX1_REQ_GTIMB1_COM  212
#define DMAMUX1_REQ_GTIMB2_COM  213
#define DMAMUX1_REQ_GTIMB3_COM  214

/* DAC */
#define DMAMUX1_REQ_DAC12_0     190
#define DMAMUX1_REQ_DAC12_1     191
#define DMAMUX1_REQ_DAC34_0     215
#define DMAMUX1_REQ_DAC34_1     216
#define DMAMUX1_REQ_DAC56_0     217
#define DMAMUX1_REQ_DAC56_1     218

/* ==========================================================================
 * DMAMUX1 Trigger Mapping (TRG)
 * ==========================================================================
 */

#define DMAMUX1_TRG_EVT0_7       0
#define DMAMUX1_TRG_EVT8_15      1
#define DMAMUX1_TRG_EVT16_23     2

#define DMAMUX1_TRG_LPTIMER1_OUT 3
#define DMAMUX1_TRG_LPTIMER2_OUT 4
#define DMAMUX1_TRG_LPTIMER3_OUT 5
#define DMAMUX1_TRG_LPTIMER4_OUT 6
#define DMAMUX1_TRG_LPTIMER5_OUT 7

#define DMAMUX1_TRG_IOM_EXTI0    8

#define DMAMUX1_TRG_FDCAN1_IRQ0  9
#define DMAMUX1_TRG_FDCAN2_IRQ0 10
#define DMAMUX1_TRG_FDCAN3_IRQ0 11
#define DMAMUX1_TRG_FDCAN4_IRQ0 12
#define DMAMUX1_TRG_FDCAN5_IRQ0 13
#define DMAMUX1_TRG_FDCAN6_IRQ0 14
#define DMAMUX1_TRG_FDCAN7_IRQ0 15
#define DMAMUX1_TRG_FDCAN8_IRQ0 16

#define DMAMUX1_TRG_FDCAN1_IRQ1 17
#define DMAMUX1_TRG_FDCAN2_IRQ1 18
#define DMAMUX1_TRG_FDCAN3_IRQ1 19
#define DMAMUX1_TRG_FDCAN4_IRQ1 20
#define DMAMUX1_TRG_FDCAN5_IRQ1 21
#define DMAMUX1_TRG_FDCAN6_IRQ1 22
#define DMAMUX1_TRG_FDCAN7_IRQ1 23
#define DMAMUX1_TRG_FDCAN8_IRQ1 24

/* ==========================================================================
 * DMAMUX1 Synchronization Mapping (SYNC)
 * ==========================================================================
 */

#define DMAMUX1_SYNC_EVT0_7       0
#define DMAMUX1_SYNC_EVT8_15      1
#define DMAMUX1_SYNC_EVT16_23     2

#define DMAMUX1_SYNC_LPTIMER1_OUT 3
#define DMAMUX1_SYNC_LPTIMER2_OUT 4
#define DMAMUX1_SYNC_LPTIMER3_OUT 5
#define DMAMUX1_SYNC_LPTIMER4_OUT 6
#define DMAMUX1_SYNC_LPTIMER5_OUT 7

#define DMAMUX1_SYNC_IOM_EXTI0    8

/* ==========================================================================
 * DMAMUX2 Request Mapping (REQ)
 * ==========================================================================
 */

#define DMAMUX2_REQ_GEN0        1
#define DMAMUX2_REQ_GEN1        2
#define DMAMUX2_REQ_GEN2        3
#define DMAMUX2_REQ_GEN3        4
#define DMAMUX2_REQ_GEN4        5
#define DMAMUX2_REQ_GEN5        6
#define DMAMUX2_REQ_GEN6        7
#define DMAMUX2_REQ_GEN7        8

#define DMAMUX2_REQ_GEN8        9
#define DMAMUX2_REQ_GEN9        10
#define DMAMUX2_REQ_GEN10       11
#define DMAMUX2_REQ_GEN11       12
#define DMAMUX2_REQ_GEN12       13
#define DMAMUX2_REQ_GEN13       14
#define DMAMUX2_REQ_GEN14       15
#define DMAMUX2_REQ_GEN15       16

#define DMAMUX2_REQ_XSPI1_TX    25
#define DMAMUX2_REQ_XSPI1_RX    26
#define DMAMUX2_REQ_XSPI2_TX    27
#define DMAMUX2_REQ_XSPI2_RX    28

/* ==========================================================================
 * DMAMUX2 Trigger Mapping (TRG)
 * ==========================================================================
 */

#define DMAMUX2_TRG_DMA1_INT_TFR0 0
#define DMAMUX2_TRG_DMA1_INT_TFR1 1
#define DMAMUX2_TRG_DMA1_INT_TFR2 2
#define DMAMUX2_TRG_DMA1_INT_TFR3 3
#define DMAMUX2_TRG_DMA1_INT_TFR4 4
#define DMAMUX2_TRG_DMA1_INT_TFR5 5
#define DMAMUX2_TRG_DMA1_INT_TFR6 6
#define DMAMUX2_TRG_DMA1_INT_TFR7 7

#define DMAMUX2_TRG_DMA2_INT_TFR0 8
#define DMAMUX2_TRG_DMA2_INT_TFR1 9
#define DMAMUX2_TRG_DMA2_INT_TFR2 10
#define DMAMUX2_TRG_DMA2_INT_TFR3 11
#define DMAMUX2_TRG_DMA2_INT_TFR4 12
#define DMAMUX2_TRG_DMA2_INT_TFR5 13
#define DMAMUX2_TRG_DMA2_INT_TFR6 14
#define DMAMUX2_TRG_DMA2_INT_TFR7 15

#define DMAMUX2_TRG_DMA3_INT_TFR0 16
#define DMAMUX2_TRG_DMA3_INT_TFR1 17
#define DMAMUX2_TRG_DMA3_INT_TFR2 18
#define DMAMUX2_TRG_DMA3_INT_TFR3 19
#define DMAMUX2_TRG_DMA3_INT_TFR4 20
#define DMAMUX2_TRG_DMA3_INT_TFR5 21
#define DMAMUX2_TRG_DMA3_INT_TFR6 22
#define DMAMUX2_TRG_DMA3_INT_TFR7 23

#define DMAMUX2_TRG_LCDC_LI_IT   24
#define DMAMUX2_TRG_GPU_SPEC_INT 25
#define DMAMUX2_TRG_JPEG_SGDMA_H2P_INT 26
#define DMAMUX2_TRG_JPEG_SGDMA_P2H_INT 27
#define DMAMUX2_TRG_MIPI_DSI_INT 28
#define DMAMUX2_TRG_USB1_INT     29
#define DMAMUX2_TRG_USB2_INT     30
#define DMAMUX2_TRG_SDMMC1_INT   31
#define DMAMUX2_TRG_SDMMC2_INT   32
#define DMAMUX2_TRG_DVP1_INT     33
#define DMAMUX2_TRG_DVP2_INT     34
#define DMAMUX2_TRG_ETH1_INT     35
#define DMAMUX2_TRG_ETH2_INT     36
#define DMAMUX2_TRG_SDPU_INT     37

/* ==========================================================================
 * DMAMUX2 Synchronization Mapping (SYNC)
 * ==========================================================================
 */

#define DMAMUX2_SYNC_INTERNAL    0

/* ==========================================================================
 * DMAMAP Definitions for DMAMUX1
 * ==========================================================================
 */

/* DMA1 Mappings */
#define DMAMAP_DMA1_1GEN0    DMAMAP_MAP(DMA1, DMAMUX1_REQ_GEN0)
#define DMAMAP_DMA1_1GEN1    DMAMAP_MAP(DMA1, DMAMUX1_REQ_GEN1)
#define DMAMAP_DMA1_1GEN2    DMAMAP_MAP(DMA1, DMAMUX1_REQ_GEN2)
#define DMAMAP_DMA1_1GEN3    DMAMAP_MAP(DMA1, DMAMUX1_REQ_GEN3)
#define DMAMAP_DMA1_1GEN4    DMAMAP_MAP(DMA1, DMAMUX1_REQ_GEN4)
#define DMAMAP_DMA1_1GEN5    DMAMAP_MAP(DMA1, DMAMUX1_REQ_GEN5)
#define DMAMAP_DMA1_1GEN6    DMAMAP_MAP(DMA1, DMAMUX1_REQ_GEN6)
#define DMAMAP_DMA1_1GEN7    DMAMAP_MAP(DMA1, DMAMUX1_REQ_GEN7)

#define DMAMAP_DMA1_ADC1     DMAMAP_MAP(DMA1, DMAMUX1_REQ_ADC1)
#define DMAMAP_DMA1_ADC2     DMAMAP_MAP(DMA1, DMAMUX1_REQ_ADC2)
#define DMAMAP_DMA1_ADC3     DMAMAP_MAP(DMA1, DMAMUX1_REQ_ADC3)

#define DMAMAP_DMA1_SHRTIM1_DMA0 DMAMAP_MAP(DMA1, DMAMUX1_REQ_SHRTIM1_DMA0)
#define DMAMAP_DMA1_SHRTIM1_DMA1 DMAMAP_MAP(DMA1, DMAMUX1_REQ_SHRTIM1_DMA1)
#define DMAMAP_DMA1_SHRTIM1_DMA2 DMAMAP_MAP(DMA1, DMAMUX1_REQ_SHRTIM1_DMA2)
#define DMAMAP_DMA1_SHRTIM1_DMA3 DMAMAP_MAP(DMA1, DMAMUX1_REQ_SHRTIM1_DMA3)
#define DMAMAP_DMA1_SHRTIM1_DMA4 DMAMAP_MAP(DMA1, DMAMUX1_REQ_SHRTIM1_DMA4)
#define DMAMAP_DMA1_SHRTIM1_DMA5 DMAMAP_MAP(DMA1, DMAMUX1_REQ_SHRTIM1_DMA5)
#define DMAMAP_DMA1_SHRTIM1_DMA6 DMAMAP_MAP(DMA1, DMAMUX1_REQ_SHRTIM1_DMA6)

#define DMAMAP_DMA1_SHRTIM2_DMA0 DMAMAP_MAP(DMA1, DMAMUX1_REQ_SHRTIM2_DMA0)
#define DMAMAP_DMA1_SHRTIM2_DMA1 DMAMAP_MAP(DMA1, DMAMUX1_REQ_SHRTIM2_DMA1)
#define DMAMAP_DMA1_SHRTIM2_DMA2 DMAMAP_MAP(DMA1, DMAMUX1_REQ_SHRTIM2_DMA2)
#define DMAMAP_DMA1_SHRTIM2_DMA3 DMAMAP_MAP(DMA1, DMAMUX1_REQ_SHRTIM2_DMA3)
#define DMAMAP_DMA1_SHRTIM2_DMA4 DMAMAP_MAP(DMA1, DMAMUX1_REQ_SHRTIM2_DMA4)
#define DMAMAP_DMA1_SHRTIM2_DMA5 DMAMAP_MAP(DMA1, DMAMUX1_REQ_SHRTIM2_DMA5)
#define DMAMAP_DMA1_SHRTIM2_DMA6 DMAMAP_MAP(DMA1, DMAMUX1_REQ_SHRTIM2_DMA6)

#define DMAMAP_DMA1_ATIM1_UP    DMAMAP_MAP(DMA1, DMAMUX1_REQ_ATIM1_UP)
#define DMAMAP_DMA1_ATIM1_CH1   DMAMAP_MAP(DMA1, DMAMUX1_REQ_ATIM1_CH1)
#define DMAMAP_DMA1_ATIM1_CH2   DMAMAP_MAP(DMA1, DMAMUX1_REQ_ATIM1_CH2)
#define DMAMAP_DMA1_ATIM1_CH3   DMAMAP_MAP(DMA1, DMAMUX1_REQ_ATIM1_CH3)
#define DMAMAP_DMA1_ATIM1_CH4   DMAMAP_MAP(DMA1, DMAMUX1_REQ_ATIM1_CH4)
#define DMAMAP_DMA1_ATIM1_COM   DMAMAP_MAP(DMA1, DMAMUX1_REQ_ATIM1_COM)
#define DMAMAP_DMA1_ATIM1_TRG   DMAMAP_MAP(DMA1, DMAMUX1_REQ_ATIM1_TRG)

#define DMAMAP_DMA1_ATIM2_UP    DMAMAP_MAP(DMA1, DMAMUX1_REQ_ATIM2_UP)
#define DMAMAP_DMA1_ATIM2_CH1   DMAMAP_MAP(DMA1, DMAMUX1_REQ_ATIM2_CH1)
#define DMAMAP_DMA1_ATIM2_CH2   DMAMAP_MAP(DMA1, DMAMUX1_REQ_ATIM2_CH2)
#define DMAMAP_DMA1_ATIM2_CH3   DMAMAP_MAP(DMA1, DMAMUX1_REQ_ATIM2_CH3)
#define DMAMAP_DMA1_ATIM2_CH4   DMAMAP_MAP(DMA1, DMAMUX1_REQ_ATIM2_CH4)
#define DMAMAP_DMA1_ATIM2_COM   DMAMAP_MAP(DMA1, DMAMUX1_REQ_ATIM2_COM)
#define DMAMAP_DMA1_ATIM2_TRG   DMAMAP_MAP(DMA1, DMAMUX1_REQ_ATIM2_TRG)

#define DMAMAP_DMA1_ATIM3_UP    DMAMAP_MAP(DMA1, DMAMUX1_REQ_ATIM3_UP)
#define DMAMAP_DMA1_ATIM3_CH1   DMAMAP_MAP(DMA1, DMAMUX1_REQ_ATIM3_CH1)
#define DMAMAP_DMA1_ATIM3_CH2   DMAMAP_MAP(DMA1, DMAMUX1_REQ_ATIM3_CH2)
#define DMAMAP_DMA1_ATIM3_CH3   DMAMAP_MAP(DMA1, DMAMUX1_REQ_ATIM3_CH3)
#define DMAMAP_DMA1_ATIM3_CH4   DMAMAP_MAP(DMA1, DMAMUX1_REQ_ATIM3_CH4)
#define DMAMAP_DMA1_ATIM3_COM   DMAMAP_MAP(DMA1, DMAMUX1_REQ_ATIM3_COM)
#define DMAMAP_DMA1_ATIM3_TRG   DMAMAP_MAP(DMA1, DMAMUX1_REQ_ATIM3_TRG)

#define DMAMAP_DMA1_ATIM4_UP    DMAMAP_MAP(DMA1, DMAMUX1_REQ_ATIM4_UP)
#define DMAMAP_DMA1_ATIM4_CH1   DMAMAP_MAP(DMA1, DMAMUX1_REQ_ATIM4_CH1)
#define DMAMAP_DMA1_ATIM4_CH2   DMAMAP_MAP(DMA1, DMAMUX1_REQ_ATIM4_CH2)
#define DMAMAP_DMA1_ATIM4_CH3   DMAMAP_MAP(DMA1, DMAMUX1_REQ_ATIM4_CH3)
#define DMAMAP_DMA1_ATIM4_CH4   DMAMAP_MAP(DMA1, DMAMUX1_REQ_ATIM4_CH4)
#define DMAMAP_DMA1_ATIM4_COM   DMAMAP_MAP(DMA1, DMAMUX1_REQ_ATIM4_COM)
#define DMAMAP_DMA1_ATIM4_TRG   DMAMAP_MAP(DMA1, DMAMUX1_REQ_ATIM4_TRG)

#define DMAMAP_DMA1_GTIMA1_CH1  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA1_CH1)
#define DMAMAP_DMA1_GTIMA1_CH2  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA1_CH2)
#define DMAMAP_DMA1_GTIMA1_CH3  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA1_CH3)
#define DMAMAP_DMA1_GTIMA1_CH4  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA1_CH4)
#define DMAMAP_DMA1_GTIMA1_TRG  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA1_TRG)
#define DMAMAP_DMA1_GTIMA1_UP   DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA1_UP)

#define DMAMAP_DMA1_GTIMA2_CH1  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA2_CH1)
#define DMAMAP_DMA1_GTIMA2_CH2  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA2_CH2)
#define DMAMAP_DMA1_GTIMA2_CH3  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA2_CH3)
#define DMAMAP_DMA1_GTIMA2_CH4  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA2_CH4)
#define DMAMAP_DMA1_GTIMA2_TRG  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA2_TRG)
#define DMAMAP_DMA1_GTIMA2_UP   DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA2_UP)

#define DMAMAP_DMA1_GTIMA3_CH1  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA3_CH1)
#define DMAMAP_DMA1_GTIMA3_CH2  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA3_CH2)
#define DMAMAP_DMA1_GTIMA3_CH3  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA3_CH3)
#define DMAMAP_DMA1_GTIMA3_CH4  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA3_CH4)
#define DMAMAP_DMA1_GTIMA3_TRG  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA3_TRG)
#define DMAMAP_DMA1_GTIMA3_UP   DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA3_UP)

#define DMAMAP_DMA1_GTIMA4_CH1  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA4_CH1)
#define DMAMAP_DMA1_GTIMA4_CH2  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA4_CH2)
#define DMAMAP_DMA1_GTIMA4_CH3  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA4_CH3)
#define DMAMAP_DMA1_GTIMA4_CH4  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA4_CH4)
#define DMAMAP_DMA1_GTIMA4_TRG  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA4_TRG)
#define DMAMAP_DMA1_GTIMA4_UP   DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA4_UP)

#define DMAMAP_DMA1_GTIMA5_CH1  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA5_CH1)
#define DMAMAP_DMA1_GTIMA5_CH2  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA5_CH2)
#define DMAMAP_DMA1_GTIMA5_CH3  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA5_CH3)
#define DMAMAP_DMA1_GTIMA5_CH4  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA5_CH4)
#define DMAMAP_DMA1_GTIMA5_TRG  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA5_TRG)
#define DMAMAP_DMA1_GTIMA5_UP   DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA5_UP)

#define DMAMAP_DMA1_GTIMA6_CH1  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA6_CH1)
#define DMAMAP_DMA1_GTIMA6_CH2  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA6_CH2)
#define DMAMAP_DMA1_GTIMA6_CH3  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA6_CH3)
#define DMAMAP_DMA1_GTIMA6_CH4  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA6_CH4)
#define DMAMAP_DMA1_GTIMA6_TRG  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA6_TRG)
#define DMAMAP_DMA1_GTIMA6_UP   DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA6_UP)

#define DMAMAP_DMA1_GTIMA7_CH1  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA7_CH1)
#define DMAMAP_DMA1_GTIMA7_CH2  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA7_CH2)
#define DMAMAP_DMA1_GTIMA7_CH3  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA7_CH3)
#define DMAMAP_DMA1_GTIMA7_CH4  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA7_CH4)
#define DMAMAP_DMA1_GTIMA7_TRG  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA7_TRG)
#define DMAMAP_DMA1_GTIMA7_UP   DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMA7_UP)

#define DMAMAP_DMA1_GTIMB1_CH1  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMB1_CH1)
#define DMAMAP_DMA1_GTIMB1_CH2  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMB1_CH2)
#define DMAMAP_DMA1_GTIMB1_CH3  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMB1_CH3)
#define DMAMAP_DMA1_GTIMB1_CH4  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMB1_CH4)
#define DMAMAP_DMA1_GTIMB1_TRG  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMB1_TRG)
#define DMAMAP_DMA1_GTIMB1_UP   DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMB1_UP)

#define DMAMAP_DMA1_GTIMB2_CH1  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMB2_CH1)
#define DMAMAP_DMA1_GTIMB2_CH2  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMB2_CH2)
#define DMAMAP_DMA1_GTIMB2_CH3  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMB2_CH3)
#define DMAMAP_DMA1_GTIMB2_CH4  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMB2_CH4)
#define DMAMAP_DMA1_GTIMB2_TRG  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMB2_TRG)
#define DMAMAP_DMA1_GTIMB2_UP   DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMB2_UP)

#define DMAMAP_DMA1_GTIMB3_CH1  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMB3_CH1)
#define DMAMAP_DMA1_GTIMB3_CH2  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMB3_CH2)
#define DMAMAP_DMA1_GTIMB3_CH3  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMB3_CH3)
#define DMAMAP_DMA1_GTIMB3_CH4  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMB3_CH4)
#define DMAMAP_DMA1_GTIMB3_TRG  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMB3_TRG)
#define DMAMAP_DMA1_GTIMB3_UP   DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMB3_UP)

#define DMAMAP_DMA1_I2C1_RX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_I2C1_RX)
#define DMAMAP_DMA1_I2C1_TX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_I2C1_TX)
#define DMAMAP_DMA1_I2C2_RX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_I2C2_RX)
#define DMAMAP_DMA1_I2C2_TX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_I2C2_TX)
#define DMAMAP_DMA1_I2C3_RX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_I2C3_RX)
#define DMAMAP_DMA1_I2C3_TX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_I2C3_TX)
#define DMAMAP_DMA1_I2C4_RX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_I2C4_RX)
#define DMAMAP_DMA1_I2C4_TX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_I2C4_TX)
#define DMAMAP_DMA1_I2C5_RX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_I2C5_RX)
#define DMAMAP_DMA1_I2C5_TX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_I2C5_TX)
#define DMAMAP_DMA1_I2C6_RX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_I2C6_RX)
#define DMAMAP_DMA1_I2C6_TX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_I2C6_TX)
#define DMAMAP_DMA1_I2C7_RX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_I2C7_RX)
#define DMAMAP_DMA1_I2C7_TX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_I2C7_TX)
#define DMAMAP_DMA1_I2C8_RX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_I2C8_RX)
#define DMAMAP_DMA1_I2C8_TX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_I2C8_TX)
#define DMAMAP_DMA1_I2C9_RX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_I2C9_RX)
#define DMAMAP_DMA1_I2C9_TX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_I2C9_TX)
#define DMAMAP_DMA1_I2C10_RX    DMAMAP_MAP(DMA1, DMAMUX1_REQ_I2C10_RX)
#define DMAMAP_DMA1_I2C10_TX    DMAMAP_MAP(DMA1, DMAMUX1_REQ_I2C10_TX)

#define DMAMAP_DMA1_USART1_RX   DMAMAP_MAP(DMA1, DMAMUX1_REQ_USART1_RX)
#define DMAMAP_DMA1_USART1_TX   DMAMAP_MAP(DMA1, DMAMUX1_REQ_USART1_TX)
#define DMAMAP_DMA1_USART2_RX   DMAMAP_MAP(DMA1, DMAMUX1_REQ_USART2_RX)
#define DMAMAP_DMA1_USART2_TX   DMAMAP_MAP(DMA1, DMAMUX1_REQ_USART2_TX)
#define DMAMAP_DMA1_USART3_RX   DMAMAP_MAP(DMA1, DMAMUX1_REQ_USART3_RX)
#define DMAMAP_DMA1_USART3_TX   DMAMAP_MAP(DMA1, DMAMUX1_REQ_USART3_TX)
#define DMAMAP_DMA1_USART4_RX   DMAMAP_MAP(DMA1, DMAMUX1_REQ_USART4_RX)
#define DMAMAP_DMA1_USART4_TX   DMAMAP_MAP(DMA1, DMAMUX1_REQ_USART4_TX)
#define DMAMAP_DMA1_USART5_RX   DMAMAP_MAP(DMA1, DMAMUX1_REQ_USART5_RX)
#define DMAMAP_DMA1_USART5_TX   DMAMAP_MAP(DMA1, DMAMUX1_REQ_USART5_TX)
#define DMAMAP_DMA1_USART6_RX   DMAMAP_MAP(DMA1, DMAMUX1_REQ_USART6_RX)
#define DMAMAP_DMA1_USART6_TX   DMAMAP_MAP(DMA1, DMAMUX1_REQ_USART6_TX)
#define DMAMAP_DMA1_USART7_RX   DMAMAP_MAP(DMA1, DMAMUX1_REQ_USART7_RX)
#define DMAMAP_DMA1_USART7_TX   DMAMAP_MAP(DMA1, DMAMUX1_REQ_USART7_TX)
#define DMAMAP_DMA1_USART8_RX   DMAMAP_MAP(DMA1, DMAMUX1_REQ_USART8_RX)
#define DMAMAP_DMA1_USART8_TX   DMAMAP_MAP(DMA1, DMAMUX1_REQ_USART8_TX)

#define DMAMAP_DMA1_UART9_RX    DMAMAP_MAP(DMA1, DMAMUX1_REQ_UART9_RX)
#define DMAMAP_DMA1_UART9_TX    DMAMAP_MAP(DMA1, DMAMUX1_REQ_UART9_TX)
#define DMAMAP_DMA1_UART10_RX   DMAMAP_MAP(DMA1, DMAMUX1_REQ_UART10_RX)
#define DMAMAP_DMA1_UART10_TX   DMAMAP_MAP(DMA1, DMAMUX1_REQ_UART10_TX)
#define DMAMAP_DMA1_UART11_RX   DMAMAP_MAP(DMA1, DMAMUX1_REQ_UART11_RX)
#define DMAMAP_DMA1_UART11_TX   DMAMAP_MAP(DMA1, DMAMUX1_REQ_UART11_TX)
#define DMAMAP_DMA1_UART12_RX   DMAMAP_MAP(DMA1, DMAMUX1_REQ_UART12_RX)
#define DMAMAP_DMA1_UART12_TX   DMAMAP_MAP(DMA1, DMAMUX1_REQ_UART12_TX)
#define DMAMAP_DMA1_UART13_RX   DMAMAP_MAP(DMA1, DMAMUX1_REQ_UART13_RX)
#define DMAMAP_DMA1_UART13_TX   DMAMAP_MAP(DMA1, DMAMUX1_REQ_UART13_TX)
#define DMAMAP_DMA1_UART14_RX   DMAMAP_MAP(DMA1, DMAMUX1_REQ_UART14_RX)
#define DMAMAP_DMA1_UART14_TX   DMAMAP_MAP(DMA1, DMAMUX1_REQ_UART14_TX)
#define DMAMAP_DMA1_UART15_RX   DMAMAP_MAP(DMA1, DMAMUX1_REQ_UART15_RX)
#define DMAMAP_DMA1_UART15_TX   DMAMAP_MAP(DMA1, DMAMUX1_REQ_UART15_TX)

#define DMAMAP_DMA1_SPI1_RX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_SPI1_RX)
#define DMAMAP_DMA1_SPI1_TX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_SPI1_TX)
#define DMAMAP_DMA1_SPI2_RX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_SPI2_RX)
#define DMAMAP_DMA1_SPI2_TX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_SPI2_TX)
#define DMAMAP_DMA1_SPI3_RX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_SPI3_RX)
#define DMAMAP_DMA1_SPI3_TX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_SPI3_TX)
#define DMAMAP_DMA1_SPI4_RX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_SPI4_RX)
#define DMAMAP_DMA1_SPI4_TX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_SPI4_TX)
#define DMAMAP_DMA1_SPI5_RX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_SPI5_RX)
#define DMAMAP_DMA1_SPI5_TX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_SPI5_TX)
#define DMAMAP_DMA1_SPI6_RX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_SPI6_RX)
#define DMAMAP_DMA1_SPI6_TX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_SPI6_TX)
#define DMAMAP_DMA1_SPI7_RX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_SPI7_RX)
#define DMAMAP_DMA1_SPI7_TX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_SPI7_TX)

#define DMAMAP_DMA1_I2S1_RX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_I2S1_RX)
#define DMAMAP_DMA1_I2S1_TX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_I2S1_TX)
#define DMAMAP_DMA1_I2S2_RX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_I2S2_RX)
#define DMAMAP_DMA1_I2S2_TX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_I2S2_TX)
#define DMAMAP_DMA1_I2S3_RX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_I2S3_RX)
#define DMAMAP_DMA1_I2S3_TX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_I2S3_TX)
#define DMAMAP_DMA1_I2S4_RX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_I2S4_RX)
#define DMAMAP_DMA1_I2S4_TX     DMAMAP_MAP(DMA1, DMAMUX1_REQ_I2S4_TX)

#define DMAMAP_DMA1_LPUART1_RX  DMAMAP_MAP(DMA1, DMAMUX1_REQ_LPUART1_RX)
#define DMAMAP_DMA1_LPUART1_TX  DMAMAP_MAP(DMA1, DMAMUX1_REQ_LPUART1_TX)
#define DMAMAP_DMA1_LPUART2_RX  DMAMAP_MAP(DMA1, DMAMUX1_REQ_LPUART2_RX)
#define DMAMAP_DMA1_LPUART2_TX  DMAMAP_MAP(DMA1, DMAMUX1_REQ_LPUART2_TX)

#define DMAMAP_DMA1_DSMU0       DMAMAP_MAP(DMA1, DMAMUX1_REQ_DSMU0)
#define DMAMAP_DMA1_DSMU1       DMAMAP_MAP(DMA1, DMAMUX1_REQ_DSMU1)
#define DMAMAP_DMA1_DSMU2       DMAMAP_MAP(DMA1, DMAMUX1_REQ_DSMU2)
#define DMAMAP_DMA1_DSMU3       DMAMAP_MAP(DMA1, DMAMUX1_REQ_DSMU3)

#define DMAMAP_DMA1_FDCAN1      DMAMAP_MAP(DMA1, DMAMUX1_REQ_FDCAN1)
#define DMAMAP_DMA1_FDCAN2      DMAMAP_MAP(DMA1, DMAMUX1_REQ_FDCAN2)
#define DMAMAP_DMA1_FDCAN3      DMAMAP_MAP(DMA1, DMAMUX1_REQ_FDCAN3)
#define DMAMAP_DMA1_FDCAN4      DMAMAP_MAP(DMA1, DMAMUX1_REQ_FDCAN4)
#define DMAMAP_DMA1_FDCAN5      DMAMAP_MAP(DMA1, DMAMUX1_REQ_FDCAN5)
#define DMAMAP_DMA1_FDCAN6      DMAMAP_MAP(DMA1, DMAMUX1_REQ_FDCAN6)
#define DMAMAP_DMA1_FDCAN7      DMAMAP_MAP(DMA1, DMAMUX1_REQ_FDCAN7)
#define DMAMAP_DMA1_FDCAN8      DMAMAP_MAP(DMA1, DMAMUX1_REQ_FDCAN8)

#define DMAMAP_DMA1_CORDIC_RD   DMAMAP_MAP(DMA1, DMAMUX1_REQ_CORDIC_RD)
#define DMAMAP_DMA1_CORDIC_WR   DMAMAP_MAP(DMA1, DMAMUX1_REQ_CORDIC_WR)

#define DMAMAP_DMA1_FMAU_RD     DMAMAP_MAP(DMA1, DMAMUX1_REQ_FMAU_RD)
#define DMAMAP_DMA1_FMAU_WR     DMAMAP_MAP(DMA1, DMAMUX1_REQ_FMAU_WR)

#define DMAMAP_DMA1_BTIM1       DMAMAP_MAP(DMA1, DMAMUX1_REQ_BTIM1)
#define DMAMAP_DMA1_BTIM2       DMAMAP_MAP(DMA1, DMAMUX1_REQ_BTIM2)
#define DMAMAP_DMA1_BTIM3       DMAMAP_MAP(DMA1, DMAMUX1_REQ_BTIM3)
#define DMAMAP_DMA1_BTIM4       DMAMAP_MAP(DMA1, DMAMUX1_REQ_BTIM4)

#define DMAMAP_DMA1_GTIMB1_COM  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMB1_COM)
#define DMAMAP_DMA1_GTIMB2_COM  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMB2_COM)
#define DMAMAP_DMA1_GTIMB3_COM  DMAMAP_MAP(DMA1, DMAMUX1_REQ_GTIMB3_COM)

#define DMAMAP_DMA1_DAC12_0     DMAMAP_MAP(DMA1, DMAMUX1_REQ_DAC12_0)
#define DMAMAP_DMA1_DAC12_1     DMAMAP_MAP(DMA1, DMAMUX1_REQ_DAC12_1)
#define DMAMAP_DMA1_DAC34_0     DMAMAP_MAP(DMA1, DMAMUX1_REQ_DAC34_0)
#define DMAMAP_DMA1_DAC34_1     DMAMAP_MAP(DMA1, DMAMUX1_REQ_DAC34_1)
#define DMAMAP_DMA1_DAC56_0     DMAMAP_MAP(DMA1, DMAMUX1_REQ_DAC56_0)
#define DMAMAP_DMA1_DAC56_1     DMAMAP_MAP(DMA1, DMAMUX1_REQ_DAC56_1)

/* DMA2 Mappings */
#define DMAMAP_DMA2_2GEN0        DMAMAP_MAP(DMA2, DMAMUX1_REQ_GEN0)
#define DMAMAP_DMA2_2GEN1        DMAMAP_MAP(DMA2, DMAMUX1_REQ_GEN1)
#define DMAMAP_DMA2_2GEN2        DMAMAP_MAP(DMA2, DMAMUX1_REQ_GEN2)
#define DMAMAP_DMA2_2GEN3        DMAMAP_MAP(DMA2, DMAMUX1_REQ_GEN3)
#define DMAMAP_DMA2_2GEN4        DMAMAP_MAP(DMA2, DMAMUX1_REQ_GEN4)
#define DMAMAP_DMA2_2GEN5        DMAMAP_MAP(DMA2, DMAMUX1_REQ_GEN5)
#define DMAMAP_DMA2_2GEN6        DMAMAP_MAP(DMA2, DMAMUX1_REQ_GEN6)
#define DMAMAP_DMA2_2GEN7        DMAMAP_MAP(DMA2, DMAMUX1_REQ_GEN7)

#define DMAMAP_DMA2_ADC1        DMAMAP_MAP(DMA2, DMAMUX1_REQ_ADC1)
#define DMAMAP_DMA2_ADC2        DMAMAP_MAP(DMA2, DMAMUX1_REQ_ADC2)
#define DMAMAP_DMA2_ADC3        DMAMAP_MAP(DMA2, DMAMUX1_REQ_ADC3)

#define DMAMAP_DMA2_SHRTIM1_DMA0 DMAMAP_MAP(DMA2, DMAMUX1_REQ_SHRTIM1_DMA0)
#define DMAMAP_DMA2_SHRTIM1_DMA1 DMAMAP_MAP(DMA2, DMAMUX1_REQ_SHRTIM1_DMA1)
#define DMAMAP_DMA2_SHRTIM1_DMA2 DMAMAP_MAP(DMA2, DMAMUX1_REQ_SHRTIM1_DMA2)
#define DMAMAP_DMA2_SHRTIM1_DMA3 DMAMAP_MAP(DMA2, DMAMUX1_REQ_SHRTIM1_DMA3)
#define DMAMAP_DMA2_SHRTIM1_DMA4 DMAMAP_MAP(DMA2, DMAMUX1_REQ_SHRTIM1_DMA4)
#define DMAMAP_DMA2_SHRTIM1_DMA5 DMAMAP_MAP(DMA2, DMAMUX1_REQ_SHRTIM1_DMA5)
#define DMAMAP_DMA2_SHRTIM1_DMA6 DMAMAP_MAP(DMA2, DMAMUX1_REQ_SHRTIM1_DMA6)

#define DMAMAP_DMA2_SHRTIM2_DMA0 DMAMAP_MAP(DMA2, DMAMUX1_REQ_SHRTIM2_DMA0)
#define DMAMAP_DMA2_SHRTIM2_DMA1 DMAMAP_MAP(DMA2, DMAMUX1_REQ_SHRTIM2_DMA1)
#define DMAMAP_DMA2_SHRTIM2_DMA2 DMAMAP_MAP(DMA2, DMAMUX1_REQ_SHRTIM2_DMA2)
#define DMAMAP_DMA2_SHRTIM2_DMA3 DMAMAP_MAP(DMA2, DMAMUX1_REQ_SHRTIM2_DMA3)
#define DMAMAP_DMA2_SHRTIM2_DMA4 DMAMAP_MAP(DMA2, DMAMUX1_REQ_SHRTIM2_DMA4)
#define DMAMAP_DMA2_SHRTIM2_DMA5 DMAMAP_MAP(DMA2, DMAMUX1_REQ_SHRTIM2_DMA5)
#define DMAMAP_DMA2_SHRTIM2_DMA6 DMAMAP_MAP(DMA2, DMAMUX1_REQ_SHRTIM2_DMA6)

#define DMAMAP_DMA2_ATIM1_UP    DMAMAP_MAP(DMA2, DMAMUX1_REQ_ATIM1_UP)
#define DMAMAP_DMA2_ATIM1_CH1   DMAMAP_MAP(DMA2, DMAMUX1_REQ_ATIM1_CH1)
#define DMAMAP_DMA2_ATIM1_CH2   DMAMAP_MAP(DMA2, DMAMUX1_REQ_ATIM1_CH2)
#define DMAMAP_DMA2_ATIM1_CH3   DMAMAP_MAP(DMA2, DMAMUX1_REQ_ATIM1_CH3)
#define DMAMAP_DMA2_ATIM1_CH4   DMAMAP_MAP(DMA2, DMAMUX1_REQ_ATIM1_CH4)
#define DMAMAP_DMA2_ATIM1_COM   DMAMAP_MAP(DMA2, DMAMUX1_REQ_ATIM1_COM)
#define DMAMAP_DMA2_ATIM1_TRG   DMAMAP_MAP(DMA2, DMAMUX1_REQ_ATIM1_TRG)

#define DMAMAP_DMA2_ATIM2_UP    DMAMAP_MAP(DMA2, DMAMUX1_REQ_ATIM2_UP)
#define DMAMAP_DMA2_ATIM2_CH1   DMAMAP_MAP(DMA2, DMAMUX1_REQ_ATIM2_CH1)
#define DMAMAP_DMA2_ATIM2_CH2   DMAMAP_MAP(DMA2, DMAMUX1_REQ_ATIM2_CH2)
#define DMAMAP_DMA2_ATIM2_CH3   DMAMAP_MAP(DMA2, DMAMUX1_REQ_ATIM2_CH3)
#define DMAMAP_DMA2_ATIM2_CH4   DMAMAP_MAP(DMA2, DMAMUX1_REQ_ATIM2_CH4)
#define DMAMAP_DMA2_ATIM2_COM   DMAMAP_MAP(DMA2, DMAMUX1_REQ_ATIM2_COM)
#define DMAMAP_DMA2_ATIM2_TRG   DMAMAP_MAP(DMA2, DMAMUX1_REQ_ATIM2_TRG)

#define DMAMAP_DMA2_ATIM3_UP    DMAMAP_MAP(DMA2, DMAMUX1_REQ_ATIM3_UP)
#define DMAMAP_DMA2_ATIM3_CH1   DMAMAP_MAP(DMA2, DMAMUX1_REQ_ATIM3_CH1)
#define DMAMAP_DMA2_ATIM3_CH2   DMAMAP_MAP(DMA2, DMAMUX1_REQ_ATIM3_CH2)
#define DMAMAP_DMA2_ATIM3_CH3   DMAMAP_MAP(DMA2, DMAMUX1_REQ_ATIM3_CH3)
#define DMAMAP_DMA2_ATIM3_CH4   DMAMAP_MAP(DMA2, DMAMUX1_REQ_ATIM3_CH4)
#define DMAMAP_DMA2_ATIM3_COM   DMAMAP_MAP(DMA2, DMAMUX1_REQ_ATIM3_COM)
#define DMAMAP_DMA2_ATIM3_TRG   DMAMAP_MAP(DMA2, DMAMUX1_REQ_ATIM3_TRG)

#define DMAMAP_DMA2_ATIM4_UP    DMAMAP_MAP(DMA2, DMAMUX1_REQ_ATIM4_UP)
#define DMAMAP_DMA2_ATIM4_CH1   DMAMAP_MAP(DMA2, DMAMUX1_REQ_ATIM4_CH1)
#define DMAMAP_DMA2_ATIM4_CH2   DMAMAP_MAP(DMA2, DMAMUX1_REQ_ATIM4_CH2)
#define DMAMAP_DMA2_ATIM4_CH3   DMAMAP_MAP(DMA2, DMAMUX1_REQ_ATIM4_CH3)
#define DMAMAP_DMA2_ATIM4_CH4   DMAMAP_MAP(DMA2, DMAMUX1_REQ_ATIM4_CH4)
#define DMAMAP_DMA2_ATIM4_COM   DMAMAP_MAP(DMA2, DMAMUX1_REQ_ATIM4_COM)
#define DMAMAP_DMA2_ATIM4_TRG   DMAMAP_MAP(DMA2, DMAMUX1_REQ_ATIM4_TRG)

#define DMAMAP_DMA2_GTIMA1_CH1  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA1_CH1)
#define DMAMAP_DMA2_GTIMA1_CH2  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA1_CH2)
#define DMAMAP_DMA2_GTIMA1_CH3  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA1_CH3)
#define DMAMAP_DMA2_GTIMA1_CH4  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA1_CH4)
#define DMAMAP_DMA2_GTIMA1_TRG  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA1_TRG)
#define DMAMAP_DMA2_GTIMA1_UP   DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA1_UP)

#define DMAMAP_DMA2_GTIMA2_CH1  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA2_CH1)
#define DMAMAP_DMA2_GTIMA2_CH2  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA2_CH2)
#define DMAMAP_DMA2_GTIMA2_CH3  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA2_CH3)
#define DMAMAP_DMA2_GTIMA2_CH4  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA2_CH4)
#define DMAMAP_DMA2_GTIMA2_TRG  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA2_TRG)
#define DMAMAP_DMA2_GTIMA2_UP   DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA2_UP)

#define DMAMAP_DMA2_GTIMA3_CH1  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA3_CH1)
#define DMAMAP_DMA2_GTIMA3_CH2  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA3_CH2)
#define DMAMAP_DMA2_GTIMA3_CH3  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA3_CH3)
#define DMAMAP_DMA2_GTIMA3_CH4  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA3_CH4)
#define DMAMAP_DMA2_GTIMA3_TRG  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA3_TRG)
#define DMAMAP_DMA2_GTIMA3_UP   DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA3_UP)

#define DMAMAP_DMA2_GTIMA4_CH1  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA4_CH1)
#define DMAMAP_DMA2_GTIMA4_CH2  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA4_CH2)
#define DMAMAP_DMA2_GTIMA4_CH3  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA4_CH3)
#define DMAMAP_DMA2_GTIMA4_CH4  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA4_CH4)
#define DMAMAP_DMA2_GTIMA4_TRG  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA4_TRG)
#define DMAMAP_DMA2_GTIMA4_UP   DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA4_UP)

#define DMAMAP_DMA2_GTIMA5_CH1  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA5_CH1)
#define DMAMAP_DMA2_GTIMA5_CH2  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA5_CH2)
#define DMAMAP_DMA2_GTIMA5_CH3  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA5_CH3)
#define DMAMAP_DMA2_GTIMA5_CH4  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA5_CH4)
#define DMAMAP_DMA2_GTIMA5_TRG  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA5_TRG)
#define DMAMAP_DMA2_GTIMA5_UP   DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA5_UP)

#define DMAMAP_DMA2_GTIMA6_CH1  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA6_CH1)
#define DMAMAP_DMA2_GTIMA6_CH2  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA6_CH2)
#define DMAMAP_DMA2_GTIMA6_CH3  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA6_CH3)
#define DMAMAP_DMA2_GTIMA6_CH4  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA6_CH4)
#define DMAMAP_DMA2_GTIMA6_TRG  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA6_TRG)
#define DMAMAP_DMA2_GTIMA6_UP   DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA6_UP)

#define DMAMAP_DMA2_GTIMA7_CH1  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA7_CH1)
#define DMAMAP_DMA2_GTIMA7_CH2  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA7_CH2)
#define DMAMAP_DMA2_GTIMA7_CH3  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA7_CH3)
#define DMAMAP_DMA2_GTIMA7_CH4  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA7_CH4)
#define DMAMAP_DMA2_GTIMA7_TRG  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA7_TRG)
#define DMAMAP_DMA2_GTIMA7_UP   DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMA7_UP)

#define DMAMAP_DMA2_GTIMB1_CH1  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMB1_CH1)
#define DMAMAP_DMA2_GTIMB1_CH2  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMB1_CH2)
#define DMAMAP_DMA2_GTIMB1_CH3  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMB1_CH3)
#define DMAMAP_DMA2_GTIMB1_CH4  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMB1_CH4)
#define DMAMAP_DMA2_GTIMB1_TRG  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMB1_TRG)
#define DMAMAP_DMA2_GTIMB1_UP   DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMB1_UP)

#define DMAMAP_DMA2_GTIMB2_CH1  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMB2_CH1)
#define DMAMAP_DMA2_GTIMB2_CH2  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMB2_CH2)
#define DMAMAP_DMA2_GTIMB2_CH3  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMB2_CH3)
#define DMAMAP_DMA2_GTIMB2_CH4  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMB2_CH4)
#define DMAMAP_DMA2_GTIMB2_TRG  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMB2_TRG)
#define DMAMAP_DMA2_GTIMB2_UP   DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMB2_UP)

#define DMAMAP_DMA2_GTIMB3_CH1  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMB3_CH1)
#define DMAMAP_DMA2_GTIMB3_CH2  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMB3_CH2)
#define DMAMAP_DMA2_GTIMB3_CH3  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMB3_CH3)
#define DMAMAP_DMA2_GTIMB3_CH4  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMB3_CH4)
#define DMAMAP_DMA2_GTIMB3_TRG  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMB3_TRG)
#define DMAMAP_DMA2_GTIMB3_UP   DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMB3_UP)

#define DMAMAP_DMA2_I2C1_RX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_I2C1_RX)
#define DMAMAP_DMA2_I2C1_TX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_I2C1_TX)
#define DMAMAP_DMA2_I2C2_RX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_I2C2_RX)
#define DMAMAP_DMA2_I2C2_TX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_I2C2_TX)
#define DMAMAP_DMA2_I2C3_RX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_I2C3_RX)
#define DMAMAP_DMA2_I2C3_TX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_I2C3_TX)
#define DMAMAP_DMA2_I2C4_RX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_I2C4_RX)
#define DMAMAP_DMA2_I2C4_TX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_I2C4_TX)
#define DMAMAP_DMA2_I2C5_RX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_I2C5_RX)
#define DMAMAP_DMA2_I2C5_TX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_I2C5_TX)
#define DMAMAP_DMA2_I2C6_RX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_I2C6_RX)
#define DMAMAP_DMA2_I2C6_TX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_I2C6_TX)
#define DMAMAP_DMA2_I2C7_RX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_I2C7_RX)
#define DMAMAP_DMA2_I2C7_TX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_I2C7_TX)
#define DMAMAP_DMA2_I2C8_RX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_I2C8_RX)
#define DMAMAP_DMA2_I2C8_TX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_I2C8_TX)
#define DMAMAP_DMA2_I2C9_RX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_I2C9_RX)
#define DMAMAP_DMA2_I2C9_TX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_I2C9_TX)
#define DMAMAP_DMA2_I2C10_RX    DMAMAP_MAP(DMA2, DMAMUX1_REQ_I2C10_RX)
#define DMAMAP_DMA2_I2C10_TX    DMAMAP_MAP(DMA2, DMAMUX1_REQ_I2C10_TX)

#define DMAMAP_DMA2_USART1_RX   DMAMAP_MAP(DMA2, DMAMUX1_REQ_USART1_RX)
#define DMAMAP_DMA2_USART1_TX   DMAMAP_MAP(DMA2, DMAMUX1_REQ_USART1_TX)
#define DMAMAP_DMA2_USART2_RX   DMAMAP_MAP(DMA2, DMAMUX1_REQ_USART2_RX)
#define DMAMAP_DMA2_USART2_TX   DMAMAP_MAP(DMA2, DMAMUX1_REQ_USART2_TX)
#define DMAMAP_DMA2_USART3_RX   DMAMAP_MAP(DMA2, DMAMUX1_REQ_USART3_RX)
#define DMAMAP_DMA2_USART3_TX   DMAMAP_MAP(DMA2, DMAMUX1_REQ_USART3_TX)
#define DMAMAP_DMA2_USART4_RX   DMAMAP_MAP(DMA2, DMAMUX1_REQ_USART4_RX)
#define DMAMAP_DMA2_USART4_TX   DMAMAP_MAP(DMA2, DMAMUX1_REQ_USART4_TX)
#define DMAMAP_DMA2_USART5_RX   DMAMAP_MAP(DMA2, DMAMUX1_REQ_USART5_RX)
#define DMAMAP_DMA2_USART5_TX   DMAMAP_MAP(DMA2, DMAMUX1_REQ_USART5_TX)
#define DMAMAP_DMA2_USART6_RX   DMAMAP_MAP(DMA2, DMAMUX1_REQ_USART6_RX)
#define DMAMAP_DMA2_USART6_TX   DMAMAP_MAP(DMA2, DMAMUX1_REQ_USART6_TX)
#define DMAMAP_DMA2_USART7_RX   DMAMAP_MAP(DMA2, DMAMUX1_REQ_USART7_RX)
#define DMAMAP_DMA2_USART7_TX   DMAMAP_MAP(DMA2, DMAMUX1_REQ_USART7_TX)
#define DMAMAP_DMA2_USART8_RX   DMAMAP_MAP(DMA2, DMAMUX1_REQ_USART8_RX)
#define DMAMAP_DMA2_USART8_TX   DMAMAP_MAP(DMA2, DMAMUX1_REQ_USART8_TX)

#define DMAMAP_DMA2_UART9_RX    DMAMAP_MAP(DMA2, DMAMUX1_REQ_UART9_RX)
#define DMAMAP_DMA2_UART9_TX    DMAMAP_MAP(DMA2, DMAMUX1_REQ_UART9_TX)
#define DMAMAP_DMA2_UART10_RX   DMAMAP_MAP(DMA2, DMAMUX1_REQ_UART10_RX)
#define DMAMAP_DMA2_UART10_TX   DMAMAP_MAP(DMA2, DMAMUX1_REQ_UART10_TX)
#define DMAMAP_DMA2_UART11_RX   DMAMAP_MAP(DMA2, DMAMUX1_REQ_UART11_RX)
#define DMAMAP_DMA2_UART11_TX   DMAMAP_MAP(DMA2, DMAMUX1_REQ_UART11_TX)
#define DMAMAP_DMA2_UART12_RX   DMAMAP_MAP(DMA2, DMAMUX1_REQ_UART12_RX)
#define DMAMAP_DMA2_UART12_TX   DMAMAP_MAP(DMA2, DMAMUX1_REQ_UART12_TX)
#define DMAMAP_DMA2_UART13_RX   DMAMAP_MAP(DMA2, DMAMUX1_REQ_UART13_RX)
#define DMAMAP_DMA2_UART13_TX   DMAMAP_MAP(DMA2, DMAMUX1_REQ_UART13_TX)
#define DMAMAP_DMA2_UART14_RX   DMAMAP_MAP(DMA2, DMAMUX1_REQ_UART14_RX)
#define DMAMAP_DMA2_UART14_TX   DMAMAP_MAP(DMA2, DMAMUX1_REQ_UART14_TX)
#define DMAMAP_DMA2_UART15_RX   DMAMAP_MAP(DMA2, DMAMUX1_REQ_UART15_RX)
#define DMAMAP_DMA2_UART15_TX   DMAMAP_MAP(DMA2, DMAMUX1_REQ_UART15_TX)

#define DMAMAP_DMA2_SPI1_RX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_SPI1_RX)
#define DMAMAP_DMA2_SPI1_TX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_SPI1_TX)
#define DMAMAP_DMA2_SPI2_RX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_SPI2_RX)
#define DMAMAP_DMA2_SPI2_TX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_SPI2_TX)
#define DMAMAP_DMA2_SPI3_RX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_SPI3_RX)
#define DMAMAP_DMA2_SPI3_TX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_SPI3_TX)
#define DMAMAP_DMA2_SPI4_RX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_SPI4_RX)
#define DMAMAP_DMA2_SPI4_TX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_SPI4_TX)
#define DMAMAP_DMA2_SPI5_RX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_SPI5_RX)
#define DMAMAP_DMA2_SPI5_TX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_SPI5_TX)
#define DMAMAP_DMA2_SPI6_RX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_SPI6_RX)
#define DMAMAP_DMA2_SPI6_TX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_SPI6_TX)
#define DMAMAP_DMA2_SPI7_RX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_SPI7_RX)
#define DMAMAP_DMA2_SPI7_TX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_SPI7_TX)

#define DMAMAP_DMA2_I2S1_RX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_I2S1_RX)
#define DMAMAP_DMA2_I2S1_TX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_I2S1_TX)
#define DMAMAP_DMA2_I2S2_RX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_I2S2_RX)
#define DMAMAP_DMA2_I2S2_TX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_I2S2_TX)
#define DMAMAP_DMA2_I2S3_RX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_I2S3_RX)
#define DMAMAP_DMA2_I2S3_TX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_I2S3_TX)
#define DMAMAP_DMA2_I2S4_RX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_I2S4_RX)
#define DMAMAP_DMA2_I2S4_TX     DMAMAP_MAP(DMA2, DMAMUX1_REQ_I2S4_TX)

#define DMAMAP_DMA2_LPUART1_RX  DMAMAP_MAP(DMA2, DMAMUX1_REQ_LPUART1_RX)
#define DMAMAP_DMA2_LPUART1_TX  DMAMAP_MAP(DMA2, DMAMUX1_REQ_LPUART1_TX)
#define DMAMAP_DMA2_LPUART2_RX  DMAMAP_MAP(DMA2, DMAMUX1_REQ_LPUART2_RX)
#define DMAMAP_DMA2_LPUART2_TX  DMAMAP_MAP(DMA2, DMAMUX1_REQ_LPUART2_TX)

#define DMAMAP_DMA2_DSMU0       DMAMAP_MAP(DMA2, DMAMUX1_REQ_DSMU0)
#define DMAMAP_DMA2_DSMU1       DMAMAP_MAP(DMA2, DMAMUX1_REQ_DSMU1)
#define DMAMAP_DMA2_DSMU2       DMAMAP_MAP(DMA2, DMAMUX1_REQ_DSMU2)
#define DMAMAP_DMA2_DSMU3       DMAMAP_MAP(DMA2, DMAMUX1_REQ_DSMU3)

#define DMAMAP_DMA2_FDCAN1      DMAMAP_MAP(DMA2, DMAMUX1_REQ_FDCAN1)
#define DMAMAP_DMA2_FDCAN2      DMAMAP_MAP(DMA2, DMAMUX1_REQ_FDCAN2)
#define DMAMAP_DMA2_FDCAN3      DMAMAP_MAP(DMA2, DMAMUX1_REQ_FDCAN3)
#define DMAMAP_DMA2_FDCAN4      DMAMAP_MAP(DMA2, DMAMUX1_REQ_FDCAN4)
#define DMAMAP_DMA2_FDCAN5      DMAMAP_MAP(DMA2, DMAMUX1_REQ_FDCAN5)
#define DMAMAP_DMA2_FDCAN6      DMAMAP_MAP(DMA2, DMAMUX1_REQ_FDCAN6)
#define DMAMAP_DMA2_FDCAN7      DMAMAP_MAP(DMA2, DMAMUX1_REQ_FDCAN7)
#define DMAMAP_DMA2_FDCAN8      DMAMAP_MAP(DMA2, DMAMUX1_REQ_FDCAN8)

#define DMAMAP_DMA2_CORDIC_RD   DMAMAP_MAP(DMA2, DMAMUX1_REQ_CORDIC_RD)
#define DMAMAP_DMA2_CORDIC_WR   DMAMAP_MAP(DMA2, DMAMUX1_REQ_CORDIC_WR)

#define DMAMAP_DMA2_FMAU_RD     DMAMAP_MAP(DMA2, DMAMUX1_REQ_FMAU_RD)
#define DMAMAP_DMA2_FMAU_WR     DMAMAP_MAP(DMA2, DMAMUX1_REQ_FMAU_WR)

#define DMAMAP_DMA2_BTIM1       DMAMAP_MAP(DMA2, DMAMUX1_REQ_BTIM1)
#define DMAMAP_DMA2_BTIM2       DMAMAP_MAP(DMA2, DMAMUX1_REQ_BTIM2)
#define DMAMAP_DMA2_BTIM3       DMAMAP_MAP(DMA2, DMAMUX1_REQ_BTIM3)
#define DMAMAP_DMA2_BTIM4       DMAMAP_MAP(DMA2, DMAMUX1_REQ_BTIM4)

#define DMAMAP_DMA2_GTIMB1_COM  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMB1_COM)
#define DMAMAP_DMA2_GTIMB2_COM  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMB2_COM)
#define DMAMAP_DMA2_GTIMB3_COM  DMAMAP_MAP(DMA2, DMAMUX1_REQ_GTIMB3_COM)

#define DMAMAP_DMA2_DAC12_0     DMAMAP_MAP(DMA2, DMAMUX1_REQ_DAC12_0)
#define DMAMAP_DMA2_DAC12_1     DMAMAP_MAP(DMA2, DMAMUX1_REQ_DAC12_1)
#define DMAMAP_DMA2_DAC34_0     DMAMAP_MAP(DMA2, DMAMUX1_REQ_DAC34_0)
#define DMAMAP_DMA2_DAC34_1     DMAMAP_MAP(DMA2, DMAMUX1_REQ_DAC34_1)
#define DMAMAP_DMA2_DAC56_0     DMAMAP_MAP(DMA2, DMAMUX1_REQ_DAC56_0)
#define DMAMAP_DMA2_DAC56_1     DMAMAP_MAP(DMA2, DMAMUX1_REQ_DAC56_1)

/* DMA3 Mappings */
#define DMAMAP_DMA3_GEN0        DMAMAP_MAP(DMA3, DMAMUX1_REQ_GEN0)
#define DMAMAP_DMA3_GEN1        DMAMAP_MAP(DMA3, DMAMUX1_REQ_GEN1)
#define DMAMAP_DMA3_GEN2        DMAMAP_MAP(DMA3, DMAMUX1_REQ_GEN2)
#define DMAMAP_DMA3_GEN3        DMAMAP_MAP(DMA3, DMAMUX1_REQ_GEN3)
#define DMAMAP_DMA3_GEN4        DMAMAP_MAP(DMA3, DMAMUX1_REQ_GEN4)
#define DMAMAP_DMA3_GEN5        DMAMAP_MAP(DMA3, DMAMUX1_REQ_GEN5)
#define DMAMAP_DMA3_GEN6        DMAMAP_MAP(DMA3, DMAMUX1_REQ_GEN6)
#define DMAMAP_DMA3_GEN7        DMAMAP_MAP(DMA3, DMAMUX1_REQ_GEN7)

#define DMAMAP_DMA3_ADC1        DMAMAP_MAP(DMA3, DMAMUX1_REQ_ADC1)
#define DMAMAP_DMA3_ADC2        DMAMAP_MAP(DMA3, DMAMUX1_REQ_ADC2)
#define DMAMAP_DMA3_ADC3        DMAMAP_MAP(DMA3, DMAMUX1_REQ_ADC3)

#define DMAMAP_DMA3_SHRTIM1_DMA0 DMAMAP_MAP(DMA3, DMAMUX1_REQ_SHRTIM1_DMA0)
#define DMAMAP_DMA3_SHRTIM1_DMA1 DMAMAP_MAP(DMA3, DMAMUX1_REQ_SHRTIM1_DMA1)
#define DMAMAP_DMA3_SHRTIM1_DMA2 DMAMAP_MAP(DMA3, DMAMUX1_REQ_SHRTIM1_DMA2)
#define DMAMAP_DMA3_SHRTIM1_DMA3 DMAMAP_MAP(DMA3, DMAMUX1_REQ_SHRTIM1_DMA3)
#define DMAMAP_DMA3_SHRTIM1_DMA4 DMAMAP_MAP(DMA3, DMAMUX1_REQ_SHRTIM1_DMA4)
#define DMAMAP_DMA3_SHRTIM1_DMA5 DMAMAP_MAP(DMA3, DMAMUX1_REQ_SHRTIM1_DMA5)
#define DMAMAP_DMA3_SHRTIM1_DMA6 DMAMAP_MAP(DMA3, DMAMUX1_REQ_SHRTIM1_DMA6)

#define DMAMAP_DMA3_SHRTIM2_DMA0 DMAMAP_MAP(DMA3, DMAMUX1_REQ_SHRTIM2_DMA0)
#define DMAMAP_DMA3_SHRTIM2_DMA1 DMAMAP_MAP(DMA3, DMAMUX1_REQ_SHRTIM2_DMA1)
#define DMAMAP_DMA3_SHRTIM2_DMA2 DMAMAP_MAP(DMA3, DMAMUX1_REQ_SHRTIM2_DMA2)
#define DMAMAP_DMA3_SHRTIM2_DMA3 DMAMAP_MAP(DMA3, DMAMUX1_REQ_SHRTIM2_DMA3)
#define DMAMAP_DMA3_SHRTIM2_DMA4 DMAMAP_MAP(DMA3, DMAMUX1_REQ_SHRTIM2_DMA4)
#define DMAMAP_DMA3_SHRTIM2_DMA5 DMAMAP_MAP(DMA3, DMAMUX1_REQ_SHRTIM2_DMA5)
#define DMAMAP_DMA3_SHRTIM2_DMA6 DMAMAP_MAP(DMA3, DMAMUX1_REQ_SHRTIM2_DMA6)

#define DMAMAP_DMA3_ATIM1_UP    DMAMAP_MAP(DMA3, DMAMUX1_REQ_ATIM1_UP)
#define DMAMAP_DMA3_ATIM1_CH1   DMAMAP_MAP(DMA3, DMAMUX1_REQ_ATIM1_CH1)
#define DMAMAP_DMA3_ATIM1_CH2   DMAMAP_MAP(DMA3, DMAMUX1_REQ_ATIM1_CH2)
#define DMAMAP_DMA3_ATIM1_CH3   DMAMAP_MAP(DMA3, DMAMUX1_REQ_ATIM1_CH3)
#define DMAMAP_DMA3_ATIM1_CH4   DMAMAP_MAP(DMA3, DMAMUX1_REQ_ATIM1_CH4)
#define DMAMAP_DMA3_ATIM1_COM   DMAMAP_MAP(DMA3, DMAMUX1_REQ_ATIM1_COM)
#define DMAMAP_DMA3_ATIM1_TRG   DMAMAP_MAP(DMA3, DMAMUX1_REQ_ATIM1_TRG)

#define DMAMAP_DMA3_ATIM2_UP    DMAMAP_MAP(DMA3, DMAMUX1_REQ_ATIM2_UP)
#define DMAMAP_DMA3_ATIM2_CH1   DMAMAP_MAP(DMA3, DMAMUX1_REQ_ATIM2_CH1)
#define DMAMAP_DMA3_ATIM2_CH2   DMAMAP_MAP(DMA3, DMAMUX1_REQ_ATIM2_CH2)
#define DMAMAP_DMA3_ATIM2_CH3   DMAMAP_MAP(DMA3, DMAMUX1_REQ_ATIM2_CH3)
#define DMAMAP_DMA3_ATIM2_CH4   DMAMAP_MAP(DMA3, DMAMUX1_REQ_ATIM2_CH4)
#define DMAMAP_DMA3_ATIM2_COM   DMAMAP_MAP(DMA3, DMAMUX1_REQ_ATIM2_COM)
#define DMAMAP_DMA3_ATIM2_TRG   DMAMAP_MAP(DMA3, DMAMUX1_REQ_ATIM2_TRG)

#define DMAMAP_DMA3_ATIM3_UP    DMAMAP_MAP(DMA3, DMAMUX1_REQ_ATIM3_UP)
#define DMAMAP_DMA3_ATIM3_CH1   DMAMAP_MAP(DMA3, DMAMUX1_REQ_ATIM3_CH1)
#define DMAMAP_DMA3_ATIM3_CH2   DMAMAP_MAP(DMA3, DMAMUX1_REQ_ATIM3_CH2)
#define DMAMAP_DMA3_ATIM3_CH3   DMAMAP_MAP(DMA3, DMAMUX1_REQ_ATIM3_CH3)
#define DMAMAP_DMA3_ATIM3_CH4   DMAMAP_MAP(DMA3, DMAMUX1_REQ_ATIM3_CH4)
#define DMAMAP_DMA3_ATIM3_COM   DMAMAP_MAP(DMA3, DMAMUX1_REQ_ATIM3_COM)
#define DMAMAP_DMA3_ATIM3_TRG   DMAMAP_MAP(DMA3, DMAMUX1_REQ_ATIM3_TRG)

#define DMAMAP_DMA3_ATIM4_UP    DMAMAP_MAP(DMA3, DMAMUX1_REQ_ATIM4_UP)
#define DMAMAP_DMA3_ATIM4_CH1   DMAMAP_MAP(DMA3, DMAMUX1_REQ_ATIM4_CH1)
#define DMAMAP_DMA3_ATIM4_CH2   DMAMAP_MAP(DMA3, DMAMUX1_REQ_ATIM4_CH2)
#define DMAMAP_DMA3_ATIM4_CH3   DMAMAP_MAP(DMA3, DMAMUX1_REQ_ATIM4_CH3)
#define DMAMAP_DMA3_ATIM4_CH4   DMAMAP_MAP(DMA3, DMAMUX1_REQ_ATIM4_CH4)
#define DMAMAP_DMA3_ATIM4_COM   DMAMAP_MAP(DMA3, DMAMUX1_REQ_ATIM4_COM)
#define DMAMAP_DMA3_ATIM4_TRG   DMAMAP_MAP(DMA3, DMAMUX1_REQ_ATIM4_TRG)

#define DMAMAP_DMA3_GTIMA1_CH1  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA1_CH1)
#define DMAMAP_DMA3_GTIMA1_CH2  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA1_CH2)
#define DMAMAP_DMA3_GTIMA1_CH3  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA1_CH3)
#define DMAMAP_DMA3_GTIMA1_CH4  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA1_CH4)
#define DMAMAP_DMA3_GTIMA1_TRG  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA1_TRG)
#define DMAMAP_DMA3_GTIMA1_UP   DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA1_UP)

#define DMAMAP_DMA3_GTIMA2_CH1  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA2_CH1)
#define DMAMAP_DMA3_GTIMA2_CH2  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA2_CH2)
#define DMAMAP_DMA3_GTIMA2_CH3  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA2_CH3)
#define DMAMAP_DMA3_GTIMA2_CH4  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA2_CH4)
#define DMAMAP_DMA3_GTIMA2_TRG  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA2_TRG)
#define DMAMAP_DMA3_GTIMA2_UP   DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA2_UP)

#define DMAMAP_DMA3_GTIMA3_CH1  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA3_CH1)
#define DMAMAP_DMA3_GTIMA3_CH2  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA3_CH2)
#define DMAMAP_DMA3_GTIMA3_CH3  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA3_CH3)
#define DMAMAP_DMA3_GTIMA3_CH4  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA3_CH4)
#define DMAMAP_DMA3_GTIMA3_TRG  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA3_TRG)
#define DMAMAP_DMA3_GTIMA3_UP   DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA3_UP)

#define DMAMAP_DMA3_GTIMA4_CH1  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA4_CH1)
#define DMAMAP_DMA3_GTIMA4_CH2  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA4_CH2)
#define DMAMAP_DMA3_GTIMA4_CH3  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA4_CH3)
#define DMAMAP_DMA3_GTIMA4_CH4  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA4_CH4)
#define DMAMAP_DMA3_GTIMA4_TRG  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA4_TRG)
#define DMAMAP_DMA3_GTIMA4_UP   DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA4_UP)

#define DMAMAP_DMA3_GTIMA5_CH1  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA5_CH1)
#define DMAMAP_DMA3_GTIMA5_CH2  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA5_CH2)
#define DMAMAP_DMA3_GTIMA5_CH3  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA5_CH3)
#define DMAMAP_DMA3_GTIMA5_CH4  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA5_CH4)
#define DMAMAP_DMA3_GTIMA5_TRG  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA5_TRG)
#define DMAMAP_DMA3_GTIMA5_UP   DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA5_UP)

#define DMAMAP_DMA3_GTIMA6_CH1  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA6_CH1)
#define DMAMAP_DMA3_GTIMA6_CH2  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA6_CH2)
#define DMAMAP_DMA3_GTIMA6_CH3  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA6_CH3)
#define DMAMAP_DMA3_GTIMA6_CH4  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA6_CH4)
#define DMAMAP_DMA3_GTIMA6_TRG  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA6_TRG)
#define DMAMAP_DMA3_GTIMA6_UP   DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA6_UP)

#define DMAMAP_DMA3_GTIMA7_CH1  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA7_CH1)
#define DMAMAP_DMA3_GTIMA7_CH2  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA7_CH2)
#define DMAMAP_DMA3_GTIMA7_CH3  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA7_CH3)
#define DMAMAP_DMA3_GTIMA7_CH4  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA7_CH4)
#define DMAMAP_DMA3_GTIMA7_TRG  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA7_TRG)
#define DMAMAP_DMA3_GTIMA7_UP   DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMA7_UP)

#define DMAMAP_DMA3_GTIMB1_CH1  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMB1_CH1)
#define DMAMAP_DMA3_GTIMB1_CH2  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMB1_CH2)
#define DMAMAP_DMA3_GTIMB1_CH3  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMB1_CH3)
#define DMAMAP_DMA3_GTIMB1_CH4  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMB1_CH4)
#define DMAMAP_DMA3_GTIMB1_TRG  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMB1_TRG)
#define DMAMAP_DMA3_GTIMB1_UP   DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMB1_UP)

#define DMAMAP_DMA3_GTIMB2_CH1  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMB2_CH1)
#define DMAMAP_DMA3_GTIMB2_CH2  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMB2_CH2)
#define DMAMAP_DMA3_GTIMB2_CH3  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMB2_CH3)
#define DMAMAP_DMA3_GTIMB2_CH4  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMB2_CH4)
#define DMAMAP_DMA3_GTIMB2_TRG  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMB2_TRG)
#define DMAMAP_DMA3_GTIMB2_UP   DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMB2_UP)

#define DMAMAP_DMA3_GTIMB3_CH1  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMB3_CH1)
#define DMAMAP_DMA3_GTIMB3_CH2  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMB3_CH2)
#define DMAMAP_DMA3_GTIMB3_CH3  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMB3_CH3)
#define DMAMAP_DMA3_GTIMB3_CH4  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMB3_CH4)
#define DMAMAP_DMA3_GTIMB3_TRG  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMB3_TRG)
#define DMAMAP_DMA3_GTIMB3_UP   DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMB3_UP)

#define DMAMAP_DMA3_I2C1_RX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_I2C1_RX)
#define DMAMAP_DMA3_I2C1_TX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_I2C1_TX)
#define DMAMAP_DMA3_I2C2_RX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_I2C2_RX)
#define DMAMAP_DMA3_I2C2_TX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_I2C2_TX)
#define DMAMAP_DMA3_I2C3_RX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_I2C3_RX)
#define DMAMAP_DMA3_I2C3_TX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_I2C3_TX)
#define DMAMAP_DMA3_I2C4_RX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_I2C4_RX)
#define DMAMAP_DMA3_I2C4_TX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_I2C4_TX)
#define DMAMAP_DMA3_I2C5_RX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_I2C5_RX)
#define DMAMAP_DMA3_I2C5_TX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_I2C5_TX)
#define DMAMAP_DMA3_I2C6_RX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_I2C6_RX)
#define DMAMAP_DMA3_I2C6_TX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_I2C6_TX)
#define DMAMAP_DMA3_I2C7_RX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_I2C7_RX)
#define DMAMAP_DMA3_I2C7_TX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_I2C7_TX)
#define DMAMAP_DMA3_I2C8_RX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_I2C8_RX)
#define DMAMAP_DMA3_I2C8_TX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_I2C8_TX)
#define DMAMAP_DMA3_I2C9_RX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_I2C9_RX)
#define DMAMAP_DMA3_I2C9_TX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_I2C9_TX)
#define DMAMAP_DMA3_I2C10_RX    DMAMAP_MAP(DMA3, DMAMUX1_REQ_I2C10_RX)
#define DMAMAP_DMA3_I2C10_TX    DMAMAP_MAP(DMA3, DMAMUX1_REQ_I2C10_TX)

#define DMAMAP_DMA3_USART1_RX   DMAMAP_MAP(DMA3, DMAMUX1_REQ_USART1_RX)
#define DMAMAP_DMA3_USART1_TX   DMAMAP_MAP(DMA3, DMAMUX1_REQ_USART1_TX)
#define DMAMAP_DMA3_USART2_RX   DMAMAP_MAP(DMA3, DMAMUX1_REQ_USART2_RX)
#define DMAMAP_DMA3_USART2_TX   DMAMAP_MAP(DMA3, DMAMUX1_REQ_USART2_TX)
#define DMAMAP_DMA3_USART3_RX   DMAMAP_MAP(DMA3, DMAMUX1_REQ_USART3_RX)
#define DMAMAP_DMA3_USART3_TX   DMAMAP_MAP(DMA3, DMAMUX1_REQ_USART3_TX)
#define DMAMAP_DMA3_USART4_RX   DMAMAP_MAP(DMA3, DMAMUX1_REQ_USART4_RX)
#define DMAMAP_DMA3_USART4_TX   DMAMAP_MAP(DMA3, DMAMUX1_REQ_USART4_TX)
#define DMAMAP_DMA3_USART5_RX   DMAMAP_MAP(DMA3, DMAMUX1_REQ_USART5_RX)
#define DMAMAP_DMA3_USART5_TX   DMAMAP_MAP(DMA3, DMAMUX1_REQ_USART5_TX)
#define DMAMAP_DMA3_USART6_RX   DMAMAP_MAP(DMA3, DMAMUX1_REQ_USART6_RX)
#define DMAMAP_DMA3_USART6_TX   DMAMAP_MAP(DMA3, DMAMUX1_REQ_USART6_TX)
#define DMAMAP_DMA3_USART7_RX   DMAMAP_MAP(DMA3, DMAMUX1_REQ_USART7_RX)
#define DMAMAP_DMA3_USART7_TX   DMAMAP_MAP(DMA3, DMAMUX1_REQ_USART7_TX)
#define DMAMAP_DMA3_USART8_RX   DMAMAP_MAP(DMA3, DMAMUX1_REQ_USART8_RX)
#define DMAMAP_DMA3_USART8_TX   DMAMAP_MAP(DMA3, DMAMUX1_REQ_USART8_TX)

#define DMAMAP_DMA3_UART9_RX    DMAMAP_MAP(DMA3, DMAMUX1_REQ_UART9_RX)
#define DMAMAP_DMA3_UART9_TX    DMAMAP_MAP(DMA3, DMAMUX1_REQ_UART9_TX)
#define DMAMAP_DMA3_UART10_RX   DMAMAP_MAP(DMA3, DMAMUX1_REQ_UART10_RX)
#define DMAMAP_DMA3_UART10_TX   DMAMAP_MAP(DMA3, DMAMUX1_REQ_UART10_TX)
#define DMAMAP_DMA3_UART11_RX   DMAMAP_MAP(DMA3, DMAMUX1_REQ_UART11_RX)
#define DMAMAP_DMA3_UART11_TX   DMAMAP_MAP(DMA3, DMAMUX1_REQ_UART11_TX)
#define DMAMAP_DMA3_UART12_RX   DMAMAP_MAP(DMA3, DMAMUX1_REQ_UART12_RX)
#define DMAMAP_DMA3_UART12_TX   DMAMAP_MAP(DMA3, DMAMUX1_REQ_UART12_TX)
#define DMAMAP_DMA3_UART13_RX   DMAMAP_MAP(DMA3, DMAMUX1_REQ_UART13_RX)
#define DMAMAP_DMA3_UART13_TX   DMAMAP_MAP(DMA3, DMAMUX1_REQ_UART13_TX)
#define DMAMAP_DMA3_UART14_RX   DMAMAP_MAP(DMA3, DMAMUX1_REQ_UART14_RX)
#define DMAMAP_DMA3_UART14_TX   DMAMAP_MAP(DMA3, DMAMUX1_REQ_UART14_TX)
#define DMAMAP_DMA3_UART15_RX   DMAMAP_MAP(DMA3, DMAMUX1_REQ_UART15_RX)
#define DMAMAP_DMA3_UART15_TX   DMAMAP_MAP(DMA3, DMAMUX1_REQ_UART15_TX)

#define DMAMAP_DMA3_SPI1_RX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_SPI1_RX)
#define DMAMAP_DMA3_SPI1_TX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_SPI1_TX)
#define DMAMAP_DMA3_SPI2_RX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_SPI2_RX)
#define DMAMAP_DMA3_SPI2_TX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_SPI2_TX)
#define DMAMAP_DMA3_SPI3_RX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_SPI3_RX)
#define DMAMAP_DMA3_SPI3_TX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_SPI3_TX)
#define DMAMAP_DMA3_SPI4_RX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_SPI4_RX)
#define DMAMAP_DMA3_SPI4_TX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_SPI4_TX)
#define DMAMAP_DMA3_SPI5_RX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_SPI5_RX)
#define DMAMAP_DMA3_SPI5_TX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_SPI5_TX)
#define DMAMAP_DMA3_SPI6_RX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_SPI6_RX)
#define DMAMAP_DMA3_SPI6_TX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_SPI6_TX)
#define DMAMAP_DMA3_SPI7_RX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_SPI7_RX)
#define DMAMAP_DMA3_SPI7_TX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_SPI7_TX)

#define DMAMAP_DMA3_I2S1_RX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_I2S1_RX)
#define DMAMAP_DMA3_I2S1_TX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_I2S1_TX)
#define DMAMAP_DMA3_I2S2_RX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_I2S2_RX)
#define DMAMAP_DMA3_I2S2_TX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_I2S2_TX)
#define DMAMAP_DMA3_I2S3_RX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_I2S3_RX)
#define DMAMAP_DMA3_I2S3_TX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_I2S3_TX)
#define DMAMAP_DMA3_I2S4_RX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_I2S4_RX)
#define DMAMAP_DMA3_I2S4_TX     DMAMAP_MAP(DMA3, DMAMUX1_REQ_I2S4_TX)

#define DMAMAP_DMA3_LPUART1_RX  DMAMAP_MAP(DMA3, DMAMUX1_REQ_LPUART1_RX)
#define DMAMAP_DMA3_LPUART1_TX  DMAMAP_MAP(DMA3, DMAMUX1_REQ_LPUART1_TX)
#define DMAMAP_DMA3_LPUART2_RX  DMAMAP_MAP(DMA3, DMAMUX1_REQ_LPUART2_RX)
#define DMAMAP_DMA3_LPUART2_TX  DMAMAP_MAP(DMA3, DMAMUX1_REQ_LPUART2_TX)

#define DMAMAP_DMA3_DSMU0       DMAMAP_MAP(DMA3, DMAMUX1_REQ_DSMU0)
#define DMAMAP_DMA3_DSMU1       DMAMAP_MAP(DMA3, DMAMUX1_REQ_DSMU1)
#define DMAMAP_DMA3_DSMU2       DMAMAP_MAP(DMA3, DMAMUX1_REQ_DSMU2)
#define DMAMAP_DMA3_DSMU3       DMAMAP_MAP(DMA3, DMAMUX1_REQ_DSMU3)

#define DMAMAP_DMA3_FDCAN1      DMAMAP_MAP(DMA3, DMAMUX1_REQ_FDCAN1)
#define DMAMAP_DMA3_FDCAN2      DMAMAP_MAP(DMA3, DMAMUX1_REQ_FDCAN2)
#define DMAMAP_DMA3_FDCAN3      DMAMAP_MAP(DMA3, DMAMUX1_REQ_FDCAN3)
#define DMAMAP_DMA3_FDCAN4      DMAMAP_MAP(DMA3, DMAMUX1_REQ_FDCAN4)
#define DMAMAP_DMA3_FDCAN5      DMAMAP_MAP(DMA3, DMAMUX1_REQ_FDCAN5)
#define DMAMAP_DMA3_FDCAN6      DMAMAP_MAP(DMA3, DMAMUX1_REQ_FDCAN6)
#define DMAMAP_DMA3_FDCAN7      DMAMAP_MAP(DMA3, DMAMUX1_REQ_FDCAN7)
#define DMAMAP_DMA3_FDCAN8      DMAMAP_MAP(DMA3, DMAMUX1_REQ_FDCAN8)

#define DMAMAP_DMA3_CORDIC_RD   DMAMAP_MAP(DMA3, DMAMUX1_REQ_CORDIC_RD)
#define DMAMAP_DMA3_CORDIC_WR   DMAMAP_MAP(DMA3, DMAMUX1_REQ_CORDIC_WR)

#define DMAMAP_DMA3_FMAU_RD     DMAMAP_MAP(DMA3, DMAMUX1_REQ_FMAU_RD)
#define DMAMAP_DMA3_FMAU_WR     DMAMAP_MAP(DMA3, DMAMUX1_REQ_FMAU_WR)

#define DMAMAP_DMA3_BTIM1       DMAMAP_MAP(DMA3, DMAMUX1_REQ_BTIM1)
#define DMAMAP_DMA3_BTIM2       DMAMAP_MAP(DMA3, DMAMUX1_REQ_BTIM2)
#define DMAMAP_DMA3_BTIM3       DMAMAP_MAP(DMA3, DMAMUX1_REQ_BTIM3)
#define DMAMAP_DMA3_BTIM4       DMAMAP_MAP(DMA3, DMAMUX1_REQ_BTIM4)

#define DMAMAP_DMA3_GTIMB1_COM  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMB1_COM)
#define DMAMAP_DMA3_GTIMB2_COM  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMB2_COM)
#define DMAMAP_DMA3_GTIMB3_COM  DMAMAP_MAP(DMA3, DMAMUX1_REQ_GTIMB3_COM)

#define DMAMAP_DMA3_DAC12_0     DMAMAP_MAP(DMA3, DMAMUX1_REQ_DAC12_0)
#define DMAMAP_DMA3_DAC12_1     DMAMAP_MAP(DMA3, DMAMUX1_REQ_DAC12_1)
#define DMAMAP_DMA3_DAC34_0     DMAMAP_MAP(DMA3, DMAMUX1_REQ_DAC34_0)
#define DMAMAP_DMA3_DAC34_1     DMAMAP_MAP(DMA3, DMAMUX1_REQ_DAC34_1)
#define DMAMAP_DMA3_DAC56_0     DMAMAP_MAP(DMA3, DMAMUX1_REQ_DAC56_0)
#define DMAMAP_DMA3_DAC56_1     DMAMAP_MAP(DMA3, DMAMUX1_REQ_DAC56_1)

/* ==========================================================================
 * DMAMAP Definitions for DMAMUX2
 * ==========================================================================
 */

/* DMA1 Mappings */
#define DMAMAP_DMA1_GEN0    DMAMAP_MAP(DMA1, DMAMUX2_REQ_GEN0)
#define DMAMAP_DMA1_GEN1    DMAMAP_MAP(DMA1, DMAMUX2_REQ_GEN1)
#define DMAMAP_DMA1_GEN2    DMAMAP_MAP(DMA1, DMAMUX2_REQ_GEN2)
#define DMAMAP_DMA1_GEN3    DMAMAP_MAP(DMA1, DMAMUX2_REQ_GEN3)
#define DMAMAP_DMA1_GEN4    DMAMAP_MAP(DMA1, DMAMUX2_REQ_GEN4)
#define DMAMAP_DMA1_GEN5    DMAMAP_MAP(DMA1, DMAMUX2_REQ_GEN5)
#define DMAMAP_DMA1_GEN6    DMAMAP_MAP(DMA1, DMAMUX2_REQ_GEN6)
#define DMAMAP_DMA1_GEN7    DMAMAP_MAP(DMA1, DMAMUX2_REQ_GEN7)
#define DMAMAP_DMA1_GEN8    DMAMAP_MAP(DMA1, DMAMUX2_REQ_GEN8)
#define DMAMAP_DMA1_GEN9    DMAMAP_MAP(DMA1, DMAMUX2_REQ_GEN9)
#define DMAMAP_DMA1_GEN10   DMAMAP_MAP(DMA1, DMAMUX2_REQ_GEN10)
#define DMAMAP_DMA1_GEN11   DMAMAP_MAP(DMA1, DMAMUX2_REQ_GEN11)
#define DMAMAP_DMA1_GEN12   DMAMAP_MAP(DMA1, DMAMUX2_REQ_GEN12)
#define DMAMAP_DMA1_GEN13   DMAMAP_MAP(DMA1, DMAMUX2_REQ_GEN13)
#define DMAMAP_DMA1_GEN14   DMAMAP_MAP(DMA1, DMAMUX2_REQ_GEN14)
#define DMAMAP_DMA1_GEN15   DMAMAP_MAP(DMA1, DMAMUX2_REQ_GEN15)
#define DMAMAP_DMA1_XSPI1_TX DMAMAP_MAP(DMA1, DMAMUX2_REQ_XSPI1_TX)
#define DMAMAP_DMA1_XSPI1_RX DMAMAP_MAP(DMA1, DMAMUX2_REQ_XSPI1_RX)
#define DMAMAP_DMA1_XSPI2_TX DMAMAP_MAP(DMA1, DMAMUX2_REQ_XSPI2_TX)
#define DMAMAP_DMA1_XSPI2_RX DMAMAP_MAP(DMA1, DMAMUX2_REQ_XSPI2_RX)

/* DMA2 Mappings */
#define DMAMAP_DMA2_GEN0    DMAMAP_MAP(DMA2, DMAMUX2_REQ_GEN0)
#define DMAMAP_DMA2_GEN1    DMAMAP_MAP(DMA2, DMAMUX2_REQ_GEN1)
#define DMAMAP_DMA2_GEN2    DMAMAP_MAP(DMA2, DMAMUX2_REQ_GEN2)
#define DMAMAP_DMA2_GEN3    DMAMAP_MAP(DMA2, DMAMUX2_REQ_GEN3)
#define DMAMAP_DMA2_GEN4    DMAMAP_MAP(DMA2, DMAMUX2_REQ_GEN4)
#define DMAMAP_DMA2_GEN5    DMAMAP_MAP(DMA2, DMAMUX2_REQ_GEN5)
#define DMAMAP_DMA2_GEN6    DMAMAP_MAP(DMA2, DMAMUX2_REQ_GEN6)
#define DMAMAP_DMA2_GEN7    DMAMAP_MAP(DMA2, DMAMUX2_REQ_GEN7)
#define DMAMAP_DMA2_GEN8    DMAMAP_MAP(DMA2, DMAMUX2_REQ_GEN8)
#define DMAMAP_DMA2_GEN9    DMAMAP_MAP(DMA2, DMAMUX2_REQ_GEN9)
#define DMAMAP_DMA2_GEN10   DMAMAP_MAP(DMA2, DMAMUX2_REQ_GEN10)
#define DMAMAP_DMA2_GEN11   DMAMAP_MAP(DMA2, DMAMUX2_REQ_GEN11)
#define DMAMAP_DMA2_GEN12   DMAMAP_MAP(DMA2, DMAMUX2_REQ_GEN12)
#define DMAMAP_DMA2_GEN13   DMAMAP_MAP(DMA2, DMAMUX2_REQ_GEN13)
#define DMAMAP_DMA2_GEN14   DMAMAP_MAP(DMA2, DMAMUX2_REQ_GEN14)
#define DMAMAP_DMA2_GEN15   DMAMAP_MAP(DMA2, DMAMUX2_REQ_GEN15)
#define DMAMAP_DMA2_XSPI1_TX DMAMAP_MAP(DMA2, DMAMUX2_REQ_XSPI1_TX)
#define DMAMAP_DMA2_XSPI1_RX DMAMAP_MAP(DMA2, DMAMUX2_REQ_XSPI1_RX)
#define DMAMAP_DMA2_XSPI2_TX DMAMAP_MAP(DMA2, DMAMUX2_REQ_XSPI2_TX)
#define DMAMAP_DMA2_XSPI2_RX DMAMAP_MAP(DMA2, DMAMUX2_REQ_XSPI2_RX)

/* DMA3 Mappings */
#define DMAMAP_DMA3_2GEN0    DMAMAP_MAP(DMA3, DMAMUX2_REQ_GEN0)
#define DMAMAP_DMA3_2GEN1    DMAMAP_MAP(DMA3, DMAMUX2_REQ_GEN1)
#define DMAMAP_DMA3_2GEN2    DMAMAP_MAP(DMA3, DMAMUX2_REQ_GEN2)
#define DMAMAP_DMA3_2GEN3    DMAMAP_MAP(DMA3, DMAMUX2_REQ_GEN3)
#define DMAMAP_DMA3_2GEN4    DMAMAP_MAP(DMA3, DMAMUX2_REQ_GEN4)
#define DMAMAP_DMA3_2GEN5    DMAMAP_MAP(DMA3, DMAMUX2_REQ_GEN5)
#define DMAMAP_DMA3_2GEN6    DMAMAP_MAP(DMA3, DMAMUX2_REQ_GEN6)
#define DMAMAP_DMA3_2GEN7    DMAMAP_MAP(DMA3, DMAMUX2_REQ_GEN7)
#define DMAMAP_DMA3_2GEN8    DMAMAP_MAP(DMA3, DMAMUX2_REQ_GEN8)
#define DMAMAP_DMA3_2GEN9    DMAMAP_MAP(DMA3, DMAMUX2_REQ_GEN9)
#define DMAMAP_DMA3_2GEN10   DMAMAP_MAP(DMA3, DMAMUX2_REQ_GEN10)
#define DMAMAP_DMA3_2GEN11   DMAMAP_MAP(DMA3, DMAMUX2_REQ_GEN11)
#define DMAMAP_DMA3_2GEN12   DMAMAP_MAP(DMA3, DMAMUX2_REQ_GEN12)
#define DMAMAP_DMA3_2GEN13   DMAMAP_MAP(DMA3, DMAMUX2_REQ_GEN13)
#define DMAMAP_DMA3_2GEN14   DMAMAP_MAP(DMA3, DMAMUX2_REQ_GEN14)
#define DMAMAP_DMA3_2GEN15   DMAMAP_MAP(DMA3, DMAMUX2_REQ_GEN15)
#define DMAMAP_DMA3_XSPI1_TX DMAMAP_MAP(DMA3, DMAMUX2_REQ_XSPI1_TX)
#define DMAMAP_DMA3_XSPI1_RX DMAMAP_MAP(DMA3, DMAMUX2_REQ_XSPI1_RX)
#define DMAMAP_DMA3_XSPI2_TX DMAMAP_MAP(DMA3, DMAMUX2_REQ_XSPI2_TX)
#define DMAMAP_DMA3_XSPI2_RX DMAMAP_MAP(DMA3, DMAMUX2_REQ_XSPI2_RX)

#endif /* __ARCH_ARM_SRC_N32H7_HARDWARE_N32H76X_DMAMUX_H */
