/****************************************************************************
 * arch/arm/src/stm32u0/hardware/stm32u0_dmamux.h
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

#ifndef __ARCH_ARM_SRC_STM32U0_HARDWARE_STM32U0_DMAMUX_H
#define __ARCH_ARM_SRC_STM32U0_HARDWARE_STM32U0_DMAMUX_H

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <nuttx/config.h>
#include "chip.h"

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* DMAMUX1 mapping **********************************************************/

/* Peripheral to DMAMUX request line mappings (RM0503, DMAMUX: assignment
 * of multiplexer inputs to resources)
 */

#define DMAMUX1_REQ_GEN0           1
#define DMAMAP_DMA1_REQ_GEN0       DMAMAP_MAP(DMA1, DMAMUX1_REQ_GEN0)
#define DMAMAP_DMA2_REQ_GEN0       DMAMAP_MAP(DMA2, DMAMUX1_REQ_GEN0)
#define DMAMUX1_REQ_GEN1           2
#define DMAMAP_DMA1_REQ_GEN1       DMAMAP_MAP(DMA1, DMAMUX1_REQ_GEN1)
#define DMAMAP_DMA2_REQ_GEN1       DMAMAP_MAP(DMA2, DMAMUX1_REQ_GEN1)
#define DMAMUX1_REQ_GEN2           3
#define DMAMAP_DMA1_REQ_GEN2       DMAMAP_MAP(DMA1, DMAMUX1_REQ_GEN2)
#define DMAMAP_DMA2_REQ_GEN2       DMAMAP_MAP(DMA2, DMAMUX1_REQ_GEN2)
#define DMAMUX1_REQ_GEN3           4
#define DMAMAP_DMA1_REQ_GEN3       DMAMAP_MAP(DMA1, DMAMUX1_REQ_GEN3)
#define DMAMAP_DMA2_REQ_GEN3       DMAMAP_MAP(DMA2, DMAMUX1_REQ_GEN3)
#define DMAMUX1_ADC1               5
#define DMAMAP_DMA1_ADC1           DMAMAP_MAP(DMA1, DMAMUX1_ADC1)
#define DMAMAP_DMA2_ADC1           DMAMAP_MAP(DMA2, DMAMUX1_ADC1)
#define DMAMUX1_AES_IN             6
#define DMAMAP_DMA1_AES_IN         DMAMAP_MAP(DMA1, DMAMUX1_AES_IN)
#define DMAMAP_DMA2_AES_IN         DMAMAP_MAP(DMA2, DMAMUX1_AES_IN)
#define DMAMUX1_AES_OUT            7
#define DMAMAP_DMA1_AES_OUT        DMAMAP_MAP(DMA1, DMAMUX1_AES_OUT)
#define DMAMAP_DMA2_AES_OUT        DMAMAP_MAP(DMA2, DMAMUX1_AES_OUT)
#define DMAMUX1_DAC_CH1            8
#define DMAMAP_DMA1_DAC_CH1        DMAMAP_MAP(DMA1, DMAMUX1_DAC_CH1)
#define DMAMAP_DMA2_DAC_CH1        DMAMAP_MAP(DMA2, DMAMUX1_DAC_CH1)
#define DMAMUX1_I2C1_RX            9
#define DMAMAP_DMA1_I2C1_RX        DMAMAP_MAP(DMA1, DMAMUX1_I2C1_RX)
#define DMAMAP_DMA2_I2C1_RX        DMAMAP_MAP(DMA2, DMAMUX1_I2C1_RX)
#define DMAMUX1_I2C1_TX            10
#define DMAMAP_DMA1_I2C1_TX        DMAMAP_MAP(DMA1, DMAMUX1_I2C1_TX)
#define DMAMAP_DMA2_I2C1_TX        DMAMAP_MAP(DMA2, DMAMUX1_I2C1_TX)
#define DMAMUX1_I2C2_RX            11
#define DMAMAP_DMA1_I2C2_RX        DMAMAP_MAP(DMA1, DMAMUX1_I2C2_RX)
#define DMAMAP_DMA2_I2C2_RX        DMAMAP_MAP(DMA2, DMAMUX1_I2C2_RX)
#define DMAMUX1_I2C2_TX            12
#define DMAMAP_DMA1_I2C2_TX        DMAMAP_MAP(DMA1, DMAMUX1_I2C2_TX)
#define DMAMAP_DMA2_I2C2_TX        DMAMAP_MAP(DMA2, DMAMUX1_I2C2_TX)
#define DMAMUX1_I2C3_RX            13
#define DMAMAP_DMA1_I2C3_RX        DMAMAP_MAP(DMA1, DMAMUX1_I2C3_RX)
#define DMAMAP_DMA2_I2C3_RX        DMAMAP_MAP(DMA2, DMAMUX1_I2C3_RX)
#define DMAMUX1_I2C3_TX            14
#define DMAMAP_DMA1_I2C3_TX        DMAMAP_MAP(DMA1, DMAMUX1_I2C3_TX)
#define DMAMAP_DMA2_I2C3_TX        DMAMAP_MAP(DMA2, DMAMUX1_I2C3_TX)
#define DMAMUX1_I2C4_RX            15
#define DMAMAP_DMA1_I2C4_RX        DMAMAP_MAP(DMA1, DMAMUX1_I2C4_RX)
#define DMAMAP_DMA2_I2C4_RX        DMAMAP_MAP(DMA2, DMAMUX1_I2C4_RX)
#define DMAMUX1_I2C4_TX            16
#define DMAMAP_DMA1_I2C4_TX        DMAMAP_MAP(DMA1, DMAMUX1_I2C4_TX)
#define DMAMAP_DMA2_I2C4_TX        DMAMAP_MAP(DMA2, DMAMUX1_I2C4_TX)
#define DMAMUX1_LPTIM1_IC1         17
#define DMAMAP_DMA1_LPTIM1_IC1     DMAMAP_MAP(DMA1, DMAMUX1_LPTIM1_IC1)
#define DMAMAP_DMA2_LPTIM1_IC1     DMAMAP_MAP(DMA2, DMAMUX1_LPTIM1_IC1)
#define DMAMUX1_LPTIM1_IC2         18
#define DMAMAP_DMA1_LPTIM1_IC2     DMAMAP_MAP(DMA1, DMAMUX1_LPTIM1_IC2)
#define DMAMAP_DMA2_LPTIM1_IC2     DMAMAP_MAP(DMA2, DMAMUX1_LPTIM1_IC2)
#define DMAMUX1_LPTIM1_IC3         19
#define DMAMAP_DMA1_LPTIM1_IC3     DMAMAP_MAP(DMA1, DMAMUX1_LPTIM1_IC3)
#define DMAMAP_DMA2_LPTIM1_IC3     DMAMAP_MAP(DMA2, DMAMUX1_LPTIM1_IC3)
#define DMAMUX1_LPTIM1_IC4         20
#define DMAMAP_DMA1_LPTIM1_IC4     DMAMAP_MAP(DMA1, DMAMUX1_LPTIM1_IC4)
#define DMAMAP_DMA2_LPTIM1_IC4     DMAMAP_MAP(DMA2, DMAMUX1_LPTIM1_IC4)
#define DMAMUX1_LPTIM1_UE          21
#define DMAMAP_DMA1_LPTIM1_UE      DMAMAP_MAP(DMA1, DMAMUX1_LPTIM1_UE)
#define DMAMAP_DMA2_LPTIM1_UE      DMAMAP_MAP(DMA2, DMAMUX1_LPTIM1_UE)
#define DMAMUX1_LPTIM2_IC1         22
#define DMAMAP_DMA1_LPTIM2_IC1     DMAMAP_MAP(DMA1, DMAMUX1_LPTIM2_IC1)
#define DMAMAP_DMA2_LPTIM2_IC1     DMAMAP_MAP(DMA2, DMAMUX1_LPTIM2_IC1)
#define DMAMUX1_LPTIM2_IC2         23
#define DMAMAP_DMA1_LPTIM2_IC2     DMAMAP_MAP(DMA1, DMAMUX1_LPTIM2_IC2)
#define DMAMAP_DMA2_LPTIM2_IC2     DMAMAP_MAP(DMA2, DMAMUX1_LPTIM2_IC2)
#define DMAMUX1_LPTIM2_UE          24
#define DMAMAP_DMA1_LPTIM2_UE      DMAMAP_MAP(DMA1, DMAMUX1_LPTIM2_UE)
#define DMAMAP_DMA2_LPTIM2_UE      DMAMAP_MAP(DMA2, DMAMUX1_LPTIM2_UE)
#define DMAMUX1_LPTIM3_IC1         25
#define DMAMAP_DMA1_LPTIM3_IC1     DMAMAP_MAP(DMA1, DMAMUX1_LPTIM3_IC1)
#define DMAMAP_DMA2_LPTIM3_IC1     DMAMAP_MAP(DMA2, DMAMUX1_LPTIM3_IC1)
#define DMAMUX1_LPTIM3_IC2         26
#define DMAMAP_DMA1_LPTIM3_IC2     DMAMAP_MAP(DMA1, DMAMUX1_LPTIM3_IC2)
#define DMAMAP_DMA2_LPTIM3_IC2     DMAMAP_MAP(DMA2, DMAMUX1_LPTIM3_IC2)
#define DMAMUX1_LPTIM3_IC3         27
#define DMAMAP_DMA1_LPTIM3_IC3     DMAMAP_MAP(DMA1, DMAMUX1_LPTIM3_IC3)
#define DMAMAP_DMA2_LPTIM3_IC3     DMAMAP_MAP(DMA2, DMAMUX1_LPTIM3_IC3)
#define DMAMUX1_LPTIM3_IC4         28
#define DMAMAP_DMA1_LPTIM3_IC4     DMAMAP_MAP(DMA1, DMAMUX1_LPTIM3_IC4)
#define DMAMAP_DMA2_LPTIM3_IC4     DMAMAP_MAP(DMA2, DMAMUX1_LPTIM3_IC4)
#define DMAMUX1_LPTIM3_UE          29
#define DMAMAP_DMA1_LPTIM3_UE      DMAMAP_MAP(DMA1, DMAMUX1_LPTIM3_UE)
#define DMAMAP_DMA2_LPTIM3_UE      DMAMAP_MAP(DMA2, DMAMUX1_LPTIM3_UE)
#define DMAMUX1_LPUART1_RX         30
#define DMAMAP_DMA1_LPUART1_RX     DMAMAP_MAP(DMA1, DMAMUX1_LPUART1_RX)
#define DMAMAP_DMA2_LPUART1_RX     DMAMAP_MAP(DMA2, DMAMUX1_LPUART1_RX)
#define DMAMUX1_LPUART1_TX         31
#define DMAMAP_DMA1_LPUART1_TX     DMAMAP_MAP(DMA1, DMAMUX1_LPUART1_TX)
#define DMAMAP_DMA2_LPUART1_TX     DMAMAP_MAP(DMA2, DMAMUX1_LPUART1_TX)
#define DMAMUX1_LPUART2_RX         32
#define DMAMAP_DMA1_LPUART2_RX     DMAMAP_MAP(DMA1, DMAMUX1_LPUART2_RX)
#define DMAMAP_DMA2_LPUART2_RX     DMAMAP_MAP(DMA2, DMAMUX1_LPUART2_RX)
#define DMAMUX1_LPUART2_TX         33
#define DMAMAP_DMA1_LPUART2_TX     DMAMAP_MAP(DMA1, DMAMUX1_LPUART2_TX)
#define DMAMAP_DMA2_LPUART2_TX     DMAMAP_MAP(DMA2, DMAMUX1_LPUART2_TX)
#define DMAMUX1_LPUART3_RX         34
#define DMAMAP_DMA1_LPUART3_RX     DMAMAP_MAP(DMA1, DMAMUX1_LPUART3_RX)
#define DMAMAP_DMA2_LPUART3_RX     DMAMAP_MAP(DMA2, DMAMUX1_LPUART3_RX)
#define DMAMUX1_LPUART3_TX         35
#define DMAMAP_DMA1_LPUART3_TX     DMAMAP_MAP(DMA1, DMAMUX1_LPUART3_TX)
#define DMAMAP_DMA2_LPUART3_TX     DMAMAP_MAP(DMA2, DMAMUX1_LPUART3_TX)
#define DMAMUX1_SPI1_RX            36
#define DMAMAP_DMA1_SPI1_RX        DMAMAP_MAP(DMA1, DMAMUX1_SPI1_RX)
#define DMAMAP_DMA2_SPI1_RX        DMAMAP_MAP(DMA2, DMAMUX1_SPI1_RX)
#define DMAMUX1_SPI1_TX            37
#define DMAMAP_DMA1_SPI1_TX        DMAMAP_MAP(DMA1, DMAMUX1_SPI1_TX)
#define DMAMAP_DMA2_SPI1_TX        DMAMAP_MAP(DMA2, DMAMUX1_SPI1_TX)
#define DMAMUX1_SPI2_RX            38
#define DMAMAP_DMA1_SPI2_RX        DMAMAP_MAP(DMA1, DMAMUX1_SPI2_RX)
#define DMAMAP_DMA2_SPI2_RX        DMAMAP_MAP(DMA2, DMAMUX1_SPI2_RX)
#define DMAMUX1_SPI2_TX            39
#define DMAMAP_DMA1_SPI2_TX        DMAMAP_MAP(DMA1, DMAMUX1_SPI2_TX)
#define DMAMAP_DMA2_SPI2_TX        DMAMAP_MAP(DMA2, DMAMUX1_SPI2_TX)
#define DMAMUX1_SPI3_RX            40
#define DMAMAP_DMA1_SPI3_RX        DMAMAP_MAP(DMA1, DMAMUX1_SPI3_RX)
#define DMAMAP_DMA2_SPI3_RX        DMAMAP_MAP(DMA2, DMAMUX1_SPI3_RX)
#define DMAMUX1_SPI3_TX            41
#define DMAMAP_DMA1_SPI3_TX        DMAMAP_MAP(DMA1, DMAMUX1_SPI3_TX)
#define DMAMAP_DMA2_SPI3_TX        DMAMAP_MAP(DMA2, DMAMUX1_SPI3_TX)
#define DMAMUX1_TIM1_CH1           42
#define DMAMAP_DMA1_TIM1_CH1       DMAMAP_MAP(DMA1, DMAMUX1_TIM1_CH1)
#define DMAMAP_DMA2_TIM1_CH1       DMAMAP_MAP(DMA2, DMAMUX1_TIM1_CH1)
#define DMAMUX1_TIM1_CH2           43
#define DMAMAP_DMA1_TIM1_CH2       DMAMAP_MAP(DMA1, DMAMUX1_TIM1_CH2)
#define DMAMAP_DMA2_TIM1_CH2       DMAMAP_MAP(DMA2, DMAMUX1_TIM1_CH2)
#define DMAMUX1_TIM1_CH3           44
#define DMAMAP_DMA1_TIM1_CH3       DMAMAP_MAP(DMA1, DMAMUX1_TIM1_CH3)
#define DMAMAP_DMA2_TIM1_CH3       DMAMAP_MAP(DMA2, DMAMUX1_TIM1_CH3)
#define DMAMUX1_TIM1_CH4           45
#define DMAMAP_DMA1_TIM1_CH4       DMAMAP_MAP(DMA1, DMAMUX1_TIM1_CH4)
#define DMAMAP_DMA2_TIM1_CH4       DMAMAP_MAP(DMA2, DMAMUX1_TIM1_CH4)
#define DMAMUX1_TIM1_TRIG_COM      46
#define DMAMAP_DMA1_TIM1_TRIG_COM  DMAMAP_MAP(DMA1, DMAMUX1_TIM1_TRIG_COM)
#define DMAMAP_DMA2_TIM1_TRIG_COM  DMAMAP_MAP(DMA2, DMAMUX1_TIM1_TRIG_COM)
#define DMAMUX1_TIM1_UP            47
#define DMAMAP_DMA1_TIM1_UP        DMAMAP_MAP(DMA1, DMAMUX1_TIM1_UP)
#define DMAMAP_DMA2_TIM1_UP        DMAMAP_MAP(DMA2, DMAMUX1_TIM1_UP)
#define DMAMUX1_TIM2_CH1           48
#define DMAMAP_DMA1_TIM2_CH1       DMAMAP_MAP(DMA1, DMAMUX1_TIM2_CH1)
#define DMAMAP_DMA2_TIM2_CH1       DMAMAP_MAP(DMA2, DMAMUX1_TIM2_CH1)
#define DMAMUX1_TIM2_CH2           49
#define DMAMAP_DMA1_TIM2_CH2       DMAMAP_MAP(DMA1, DMAMUX1_TIM2_CH2)
#define DMAMAP_DMA2_TIM2_CH2       DMAMAP_MAP(DMA2, DMAMUX1_TIM2_CH2)
#define DMAMUX1_TIM2_CH3           50
#define DMAMAP_DMA1_TIM2_CH3       DMAMAP_MAP(DMA1, DMAMUX1_TIM2_CH3)
#define DMAMAP_DMA2_TIM2_CH3       DMAMAP_MAP(DMA2, DMAMUX1_TIM2_CH3)
#define DMAMUX1_TIM2_CH4           51
#define DMAMAP_DMA1_TIM2_CH4       DMAMAP_MAP(DMA1, DMAMUX1_TIM2_CH4)
#define DMAMAP_DMA2_TIM2_CH4       DMAMAP_MAP(DMA2, DMAMUX1_TIM2_CH4)
#define DMAMUX1_TIM2_TRIG          52
#define DMAMAP_DMA1_TIM2_TRIG      DMAMAP_MAP(DMA1, DMAMUX1_TIM2_TRIG)
#define DMAMAP_DMA2_TIM2_TRIG      DMAMAP_MAP(DMA2, DMAMUX1_TIM2_TRIG)
#define DMAMUX1_TIM2_UP            53
#define DMAMAP_DMA1_TIM2_UP        DMAMAP_MAP(DMA1, DMAMUX1_TIM2_UP)
#define DMAMAP_DMA2_TIM2_UP        DMAMAP_MAP(DMA2, DMAMUX1_TIM2_UP)
#define DMAMUX1_TIM3_CH1           54
#define DMAMAP_DMA1_TIM3_CH1       DMAMAP_MAP(DMA1, DMAMUX1_TIM3_CH1)
#define DMAMAP_DMA2_TIM3_CH1       DMAMAP_MAP(DMA2, DMAMUX1_TIM3_CH1)
#define DMAMUX1_TIM3_CH2           55
#define DMAMAP_DMA1_TIM3_CH2       DMAMAP_MAP(DMA1, DMAMUX1_TIM3_CH2)
#define DMAMAP_DMA2_TIM3_CH2       DMAMAP_MAP(DMA2, DMAMUX1_TIM3_CH2)
#define DMAMUX1_TIM3_CH3           56
#define DMAMAP_DMA1_TIM3_CH3       DMAMAP_MAP(DMA1, DMAMUX1_TIM3_CH3)
#define DMAMAP_DMA2_TIM3_CH3       DMAMAP_MAP(DMA2, DMAMUX1_TIM3_CH3)
#define DMAMUX1_TIM3_CH4           57
#define DMAMAP_DMA1_TIM3_CH4       DMAMAP_MAP(DMA1, DMAMUX1_TIM3_CH4)
#define DMAMAP_DMA2_TIM3_CH4       DMAMAP_MAP(DMA2, DMAMUX1_TIM3_CH4)
#define DMAMUX1_TIM3_TRIG          58
#define DMAMAP_DMA1_TIM3_TRIG      DMAMAP_MAP(DMA1, DMAMUX1_TIM3_TRIG)
#define DMAMAP_DMA2_TIM3_TRIG      DMAMAP_MAP(DMA2, DMAMUX1_TIM3_TRIG)
#define DMAMUX1_TIM3_UP            59
#define DMAMAP_DMA1_TIM3_UP        DMAMAP_MAP(DMA1, DMAMUX1_TIM3_UP)
#define DMAMAP_DMA2_TIM3_UP        DMAMAP_MAP(DMA2, DMAMUX1_TIM3_UP)
#define DMAMUX1_TIM6_UP            60
#define DMAMAP_DMA1_TIM6_UP        DMAMAP_MAP(DMA1, DMAMUX1_TIM6_UP)
#define DMAMAP_DMA2_TIM6_UP        DMAMAP_MAP(DMA2, DMAMUX1_TIM6_UP)
#define DMAMUX1_TIM7_UP            61
#define DMAMAP_DMA1_TIM7_UP        DMAMAP_MAP(DMA1, DMAMUX1_TIM7_UP)
#define DMAMAP_DMA2_TIM7_UP        DMAMAP_MAP(DMA2, DMAMUX1_TIM7_UP)
#define DMAMUX1_TIM15_CH1          62
#define DMAMAP_DMA1_TIM15_CH1      DMAMAP_MAP(DMA1, DMAMUX1_TIM15_CH1)
#define DMAMAP_DMA2_TIM15_CH1      DMAMAP_MAP(DMA2, DMAMUX1_TIM15_CH1)
#define DMAMUX1_TIM15_CH2          63
#define DMAMAP_DMA1_TIM15_CH2      DMAMAP_MAP(DMA1, DMAMUX1_TIM15_CH2)
#define DMAMAP_DMA2_TIM15_CH2      DMAMAP_MAP(DMA2, DMAMUX1_TIM15_CH2)
#define DMAMUX1_TIM15_TRIG_COM     64
#define DMAMAP_DMA1_TIM15_TRIG_COM DMAMAP_MAP(DMA1, DMAMUX1_TIM15_TRIG_COM)
#define DMAMAP_DMA2_TIM15_TRIG_COM DMAMAP_MAP(DMA2, DMAMUX1_TIM15_TRIG_COM)
#define DMAMUX1_TIM15_UP           65
#define DMAMAP_DMA1_TIM15_UP       DMAMAP_MAP(DMA1, DMAMUX1_TIM15_UP)
#define DMAMAP_DMA2_TIM15_UP       DMAMAP_MAP(DMA2, DMAMUX1_TIM15_UP)
#define DMAMUX1_TIM16_CH1          66
#define DMAMAP_DMA1_TIM16_CH1      DMAMAP_MAP(DMA1, DMAMUX1_TIM16_CH1)
#define DMAMAP_DMA2_TIM16_CH1      DMAMAP_MAP(DMA2, DMAMUX1_TIM16_CH1)
#define DMAMUX1_TIM16_COM          67
#define DMAMAP_DMA1_TIM16_COM      DMAMAP_MAP(DMA1, DMAMUX1_TIM16_COM)
#define DMAMAP_DMA2_TIM16_COM      DMAMAP_MAP(DMA2, DMAMUX1_TIM16_COM)
#define DMAMUX1_TIM16_UP           68
#define DMAMAP_DMA1_TIM16_UP       DMAMAP_MAP(DMA1, DMAMUX1_TIM16_UP)
#define DMAMAP_DMA2_TIM16_UP       DMAMAP_MAP(DMA2, DMAMUX1_TIM16_UP)
#define DMAMUX1_USART1_RX          69
#define DMAMAP_DMA1_USART1_RX      DMAMAP_MAP(DMA1, DMAMUX1_USART1_RX)
#define DMAMAP_DMA2_USART1_RX      DMAMAP_MAP(DMA2, DMAMUX1_USART1_RX)
#define DMAMUX1_USART1_TX          70
#define DMAMAP_DMA1_USART1_TX      DMAMAP_MAP(DMA1, DMAMUX1_USART1_TX)
#define DMAMAP_DMA2_USART1_TX      DMAMAP_MAP(DMA2, DMAMUX1_USART1_TX)
#define DMAMUX1_USART2_RX          71
#define DMAMAP_DMA1_USART2_RX      DMAMAP_MAP(DMA1, DMAMUX1_USART2_RX)
#define DMAMAP_DMA2_USART2_RX      DMAMAP_MAP(DMA2, DMAMUX1_USART2_RX)
#define DMAMUX1_USART2_TX          72
#define DMAMAP_DMA1_USART2_TX      DMAMAP_MAP(DMA1, DMAMUX1_USART2_TX)
#define DMAMAP_DMA2_USART2_TX      DMAMAP_MAP(DMA2, DMAMUX1_USART2_TX)
#define DMAMUX1_USART3_RX          73
#define DMAMAP_DMA1_USART3_RX      DMAMAP_MAP(DMA1, DMAMUX1_USART3_RX)
#define DMAMAP_DMA2_USART3_RX      DMAMAP_MAP(DMA2, DMAMUX1_USART3_RX)
#define DMAMUX1_USART3_TX          74
#define DMAMAP_DMA1_USART3_TX      DMAMAP_MAP(DMA1, DMAMUX1_USART3_TX)
#define DMAMAP_DMA2_USART3_TX      DMAMAP_MAP(DMA2, DMAMUX1_USART3_TX)
#define DMAMUX1_USART4_RX          75
#define DMAMAP_DMA1_USART4_RX      DMAMAP_MAP(DMA1, DMAMUX1_USART4_RX)
#define DMAMAP_DMA2_USART4_RX      DMAMAP_MAP(DMA2, DMAMUX1_USART4_RX)
#define DMAMUX1_USART4_TX          76
#define DMAMAP_DMA1_USART4_TX      DMAMAP_MAP(DMA1, DMAMUX1_USART4_TX)
#define DMAMAP_DMA2_USART4_TX      DMAMAP_MAP(DMA2, DMAMUX1_USART4_TX)

/* DMAMUX trigger input sources (RM0503, DMAMUX: trigger inputs) */

#define DMAMUX_TRIG_EXTI0          0
#define DMAMUX_TRIG_EXTI1          1
#define DMAMUX_TRIG_EXTI2          2
#define DMAMUX_TRIG_EXTI3          3
#define DMAMUX_TRIG_EXTI4          4
#define DMAMUX_TRIG_EXTI5          5
#define DMAMUX_TRIG_EXTI6          6
#define DMAMUX_TRIG_EXTI7          7
#define DMAMUX_TRIG_EXTI8          8
#define DMAMUX_TRIG_EXTI9          9
#define DMAMUX_TRIG_EXTI10         10
#define DMAMUX_TRIG_EXTI11         11
#define DMAMUX_TRIG_EXTI12         12
#define DMAMUX_TRIG_EXTI13         13
#define DMAMUX_TRIG_EXTI14         14
#define DMAMUX_TRIG_EXTI15         15
#define DMAMUX_TRIG_EVT0           16
#define DMAMUX_TRIG_EVT1           17
#define DMAMUX_TRIG_EVT2           18
#define DMAMUX_TRIG_EVT3           19
#define DMAMUX_TRIG_LPTIM1_OUT     20
#define DMAMUX_TRIG_LPTIM2_OUT     21
#define DMAMUX_TRIG_LPTIM3_OUT     22

/* Sync inputs use the same values as trigger inputs (RM0503, DMAMUX:
 * synchronization inputs)
 */

#define DMAMUX_SYNC_EXTI0          0
#define DMAMUX_SYNC_EXTI1          1
#define DMAMUX_SYNC_EXTI2          2
#define DMAMUX_SYNC_EXTI3          3
#define DMAMUX_SYNC_EXTI4          4
#define DMAMUX_SYNC_EXTI5          5
#define DMAMUX_SYNC_EXTI6          6
#define DMAMUX_SYNC_EXTI7          7
#define DMAMUX_SYNC_EXTI8          8
#define DMAMUX_SYNC_EXTI9          9
#define DMAMUX_SYNC_EXTI10         10
#define DMAMUX_SYNC_EXTI11         11
#define DMAMUX_SYNC_EXTI12         12
#define DMAMUX_SYNC_EXTI13         13
#define DMAMUX_SYNC_EXTI14         14
#define DMAMUX_SYNC_EXTI15         15
#define DMAMUX_SYNC_EVT0           16
#define DMAMUX_SYNC_EVT1           17
#define DMAMUX_SYNC_EVT2           18
#define DMAMUX_SYNC_EVT3           19
#define DMAMUX_SYNC_LPTIM1_OUT     20
#define DMAMUX_SYNC_LPTIM2_OUT     21
#define DMAMUX_SYNC_LPTIM3_OUT     22

#endif /* __ARCH_ARM_SRC_STM32U0_HARDWARE_STM32U0_DMAMUX_H */
