############################################################################
# boards/risc-v/allwinner-d1/lichee-rv-86-panel/src/Makefile
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(TOPDIR)/Make.defs

CSRCS = allwinner_d1_boardinit.c

include $(TOPDIR)/boards/Board.mk
