/****************************************************************************
 * boards/tricore/tc397/a2g-tc397-5v-tft/include/board_memorymap.h
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

#ifndef __BOARDS_TRICORE_TC397_A2G_TC397_5V_TFT_INCLUDE_BOARD_MEMORYMAP_H
#define __BOARDS_TRICORE_TC397_A2G_TC397_5V_TFT_INCLUDE_BOARD_MEMORYMAP_H

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <nuttx/config.h>

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

#define BANKA_CORE0_PFLASH_KERNEL_START 0x80000000
#define BANKA_CORE0_PFLASH_KERNEL_SIZE 0x180000 /* 1536KB */
#define BANKA_CORE0_PFLASH_USER_START 0x80180000
#define BANKA_CORE0_PFLASH_USER_SIZE 0x180000 /* 1536KB */
#define BANKA_CORE1_PFLASH_KERNEL_START 0x80300000
#define BANKA_CORE1_PFLASH_KERNEL_SIZE 0x180000 /* 1536KB */
#define BANKA_CORE1_PFLASH_USER_START 0x80480000
#define BANKA_CORE1_PFLASH_USER_SIZE 0x180000 /* 1536KB */
#define BANKA_CORE2_PFLASH_KERNEL_START 0x80600000
#define BANKA_CORE2_PFLASH_KERNEL_SIZE 0x180000 /* 1536KB */
#define BANKA_CORE2_PFLASH_USER_START 0x80780000
#define BANKA_CORE2_PFLASH_USER_SIZE 0x180000 /* 1536KB */
#define BANKA_CORE3_PFLASH_KERNEL_START 0x80900000
#define BANKA_CORE3_PFLASH_KERNEL_SIZE 0x180000 /* 1536KB */
#define BANKA_CORE3_PFLASH_USER_START 0x80A80000
#define BANKA_CORE3_PFLASH_USER_SIZE 0x180000 /* 1536KB */
#define BANKA_CORE4_PFLASH_KERNEL_START 0x80C00000
#define BANKA_CORE4_PFLASH_KERNEL_SIZE 0x180000 /* 1536KB */
#define BANKA_CORE4_PFLASH_USER_START 0x80D80000
#define BANKA_CORE4_PFLASH_USER_SIZE 0x180000 /* 1536KB */
#define BANKA_CORE5_PFLASH_KERNEL_START 0x80F00000
#define BANKA_CORE5_PFLASH_KERNEL_SIZE 0x80000 /* 512KB */
#define BANKA_CORE5_PFLASH_USER_START 0x80F80000
#define BANKA_CORE5_PFLASH_USER_SIZE 0x80000 /* 512KB */
#define CORE0_STACK_KERNEL_START 0x70000000
#define CORE0_STACK_KERNEL_SIZE 0x8000 /* 32KB */
#define CORE0_STACK_USER_START 0x70008000
#define CORE0_STACK_USER_SIZE 0x8000 /* 32KB */
#define CORE0_DSPR_KERNEL_START 0x70010000
#define CORE0_DSPR_KERNEL_SIZE 0x2C000 /* 176KB */
#define CORE0_DSPR_USER_START 0x7003C000
#define CORE0_DSPR_USER_SIZE 0x0 /* 0KB */
#define CORE0_PSPR_KERNEL_START 0x70100000
#define CORE0_PSPR_KERNEL_SIZE 0x8000 /* 32KB */
#define CORE0_PSPR_USER_START 0x70108000
#define CORE0_PSPR_USER_SIZE 0x8000 /* 32KB */
#define CORE0_DLMU_KERNEL_START 0x90000000
#define CORE0_DLMU_KERNEL_SIZE 0x0 /* 0KB */
#define CORE0_DLMU_USER_START 0x90000000
#define CORE0_DLMU_USER_SIZE 0x10000 /* 64KB */
#define CORE1_STACK_KERNEL_START 0x60000000
#define CORE1_STACK_KERNEL_SIZE 0x8000 /* 32KB */
#define CORE1_STACK_USER_START 0x60008000
#define CORE1_STACK_USER_SIZE 0x8000 /* 32KB */
#define CORE1_DSPR_KERNEL_START 0x60010000
#define CORE1_DSPR_KERNEL_SIZE 0x2C000 /* 176KB */
#define CORE1_DSPR_USER_START 0x6003C000
#define CORE1_DSPR_USER_SIZE 0x0 /* 0KB */
#define CORE1_PSPR_KERNEL_START 0x60100000
#define CORE1_PSPR_KERNEL_SIZE 0x8000 /* 32KB */
#define CORE1_PSPR_USER_START 0x60108000
#define CORE1_PSPR_USER_SIZE 0x8000 /* 32KB */
#define CORE1_DLMU_KERNEL_START 0x90010000
#define CORE1_DLMU_KERNEL_SIZE 0x0 /* 0KB */
#define CORE1_DLMU_USER_START 0x90010000
#define CORE1_DLMU_USER_SIZE 0x10000 /* 64KB */
#define CORE2_STACK_KERNEL_START 0x50000000
#define CORE2_STACK_KERNEL_SIZE 0x6000 /* 24KB */
#define CORE2_STACK_USER_START 0x50006000
#define CORE2_STACK_USER_SIZE 0x5000 /* 20KB */
#define CORE2_DSPR_KERNEL_START 0x5000B000
#define CORE2_DSPR_KERNEL_SIZE 0xD000 /* 52KB */
#define CORE2_DSPR_USER_START 0x50018000
#define CORE2_DSPR_USER_SIZE 0x0 /* 0KB */
#define CORE2_PSPR_KERNEL_START 0x50100000
#define CORE2_PSPR_KERNEL_SIZE 0x8000 /* 32KB */
#define CORE2_PSPR_USER_START 0x50108000
#define CORE2_PSPR_USER_SIZE 0x8000 /* 32KB */
#define CORE2_DLMU_KERNEL_START 0x90020000
#define CORE2_DLMU_KERNEL_SIZE 0x0 /* 0KB */
#define CORE2_DLMU_USER_START 0x90020000
#define CORE2_DLMU_USER_SIZE 0x10000 /* 64KB */
#define CORE3_STACK_KERNEL_START 0x40000000
#define CORE3_STACK_KERNEL_SIZE 0x6000 /* 24KB */
#define CORE3_STACK_USER_START 0x40006000
#define CORE3_STACK_USER_SIZE 0x5000 /* 20KB */
#define CORE3_DSPR_KERNEL_START 0x4000B000
#define CORE3_DSPR_KERNEL_SIZE 0xD000 /* 52KB */
#define CORE3_DSPR_USER_START 0x40018000
#define CORE3_DSPR_USER_SIZE 0x0 /* 0KB */
#define CORE3_PSPR_KERNEL_START 0x40100000
#define CORE3_PSPR_KERNEL_SIZE 0x8000 /* 32KB */
#define CORE3_PSPR_USER_START 0x40108000
#define CORE3_PSPR_USER_SIZE 0x8000 /* 32KB */
#define CORE3_DLMU_KERNEL_START 0x90030000
#define CORE3_DLMU_KERNEL_SIZE 0x0 /* 0KB */
#define CORE3_DLMU_USER_START 0x90030000
#define CORE3_DLMU_USER_SIZE 0x10000 /* 64KB */
#define CORE4_STACK_KERNEL_START 0x30000000
#define CORE4_STACK_KERNEL_SIZE 0x6000 /* 24KB */
#define CORE4_STACK_USER_START 0x30006000
#define CORE4_STACK_USER_SIZE 0x5000 /* 20KB */
#define CORE4_DSPR_KERNEL_START 0x3000B000
#define CORE4_DSPR_KERNEL_SIZE 0xD000 /* 52KB */
#define CORE4_DSPR_USER_START 0x30018000
#define CORE4_DSPR_USER_SIZE 0x0 /* 0KB */
#define CORE4_PSPR_KERNEL_START 0x30100000
#define CORE4_PSPR_KERNEL_SIZE 0x8000 /* 32KB */
#define CORE4_PSPR_USER_START 0x30108000
#define CORE4_PSPR_USER_SIZE 0x8000 /* 32KB */
#define CORE4_DLMU_KERNEL_START 0x90100000
#define CORE4_DLMU_KERNEL_SIZE 0x0 /* 0KB */
#define CORE4_DLMU_USER_START 0x90100000
#define CORE4_DLMU_USER_SIZE 0x10000 /* 64KB */
#define CORE5_STACK_KERNEL_START 0x10000000
#define CORE5_STACK_KERNEL_SIZE 0x6000 /* 24KB */
#define CORE5_STACK_USER_START 0x10006000
#define CORE5_STACK_USER_SIZE 0x5000 /* 20KB */
#define CORE5_DSPR_KERNEL_START 0x1000B000
#define CORE5_DSPR_KERNEL_SIZE 0xD000 /* 52KB */
#define CORE5_DSPR_USER_START 0x10018000
#define CORE5_DSPR_USER_SIZE 0x0 /* 0KB */
#define CORE5_PSPR_KERNEL_START 0x10100000
#define CORE5_PSPR_KERNEL_SIZE 0x8000 /* 32KB */
#define CORE5_PSPR_USER_START 0x10108000
#define CORE5_PSPR_USER_SIZE 0x8000 /* 32KB */
#define CORE5_DLMU_KERNEL_START 0x90110000
#define CORE5_DLMU_KERNEL_SIZE 0x0 /* 0KB */
#define CORE5_DLMU_USER_START 0x90110000
#define CORE5_DLMU_USER_SIZE 0x10000 /* 64KB */
#define LMU0_UNUSED_START 0xB0040000
#define LMU0_UNUSED_SIZE 0x40000 /* 256KB */
#define LMU1_UNUSED_START 0xB0080000
#define LMU1_UNUSED_SIZE 0x40000 /* 256KB */
#define LMU2_UNUSED_START 0xB00C0000
#define LMU2_UNUSED_SIZE 0x40000 /* 256KB */
#define DFLASH0_NVM_START 0xAF000000
#define DFLASH0_NVM_SIZE 0x40000 /* 256KB */
#define DFLASH0_MANUFACTURY_START 0xAF040000
#define DFLASH0_MANUFACTURY_SIZE 0x2800 /* 10K */
#define DFLASH0_BSWLOG_START 0xAF042800
#define DFLASH0_BSWLOG_SIZE 0x10000 /* 64K */
#define DFLASH0_TRAPINFO_START 0xAF052800
#define DFLASH0_TRAPINFO_SIZE 0x4000 /* 16K */
#define DFLASH0_DFXLOG_START 0xAF056800
#define DFLASH0_DFXLOG_SIZE 0x4000 /* 16K */
#define DFLASH0_UNUSED_START 0xAF05A800
#define DFLASH0_UNUSED_SIZE 0xA5800 /* 662K */
#define UCB0_START 0xAF400000
#define UCB0_SIZE 0x6000 /* 24K */
#define PERIPHERALS_START 0xF0000000
#define PERIPHERALS_SIZE 0xB720000 /* 187520K */
#define CORE0_DCACHE_START 0x7003C000
#define CORE0_DCACHE_SIZE 0x4000 /* 16K */
#define CORE1_DCACHE_START 0x6003C000
#define CORE1_DCACHE_SIZE 0x4000 /* 16K */
#define CORE2_DCACHE_START 0x50018000
#define CORE2_DCACHE_SIZE 0x4000 /* 16K */
#define CORE3_DCACHE_START 0x40018000
#define CORE3_DCACHE_SIZE 0x4000 /* 16K */
#define CORE4_DCACHE_START 0x30018000
#define CORE4_DCACHE_SIZE 0x4000 /* 16K */
#define CORE5_DCACHE_START 0x10018000
#define CORE5_DCACHE_SIZE 0x4000 /* 16K */

/****************************************************************************
 * Common macros
 *
 ****************************************************************************/

#ifdef CONFIG_BUILD_FLAT

#  define CORE0_PFLASH_KERNEL_START  BANKA_CORE0_PFLASH_KERNEL_START
#  define CORE0_PFLASH_KERNEL_SIZE   BANKA_CORE0_PFLASH_KERNEL_SIZE
#  define CORE1_PFLASH_KERNEL_START  BANKA_CORE1_PFLASH_KERNEL_START
#  define CORE1_PFLASH_KERNEL_SIZE   BANKA_CORE1_PFLASH_KERNEL_SIZE
#  define CORE2_PFLASH_KERNEL_START  BANKA_CORE2_PFLASH_KERNEL_START
#  define CORE2_PFLASH_KERNEL_SIZE   BANKA_CORE2_PFLASH_KERNEL_SIZE
#  define CORE3_PFLASH_KERNEL_START  BANKA_CORE3_PFLASH_KERNEL_START
#  define CORE3_PFLASH_KERNEL_SIZE   BANKA_CORE3_PFLASH_KERNEL_SIZE
#  define CORE4_PFLASH_KERNEL_START  BANKA_CORE4_PFLASH_KERNEL_START
#  define CORE4_PFLASH_KERNEL_SIZE   BANKA_CORE4_PFLASH_KERNEL_SIZE
#  define CORE5_PFLASH_KERNEL_START  BANKA_CORE5_PFLASH_KERNEL_START
#  define CORE5_PFLASH_KERNEL_SIZE   BANKA_CORE5_PFLASH_KERNEL_SIZE

#else

#  define CORE0_PFLASH_KERNEL_START  BANKA_CORE0_PFLASH_KERNEL_START
#  define CORE0_PFLASH_KERNEL_SIZE   BANKA_CORE0_PFLASH_KERNEL_SIZE
#  define CORE0_PFLASH_USER_START    BANKA_CORE0_PFLASH_USER_START
#  define CORE0_PFLASH_USER_SIZE     BANKA_CORE0_PFLASH_USER_SIZE

#  define CORE1_PFLASH_KERNEL_START  BANKA_CORE1_PFLASH_KERNEL_START
#  define CORE1_PFLASH_KERNEL_SIZE   BANKA_CORE1_PFLASH_KERNEL_SIZE
#  define CORE1_PFLASH_USER_START    BANKA_CORE1_PFLASH_USER_START
#  define CORE1_PFLASH_USER_SIZE     BANKA_CORE1_PFLASH_USER_SIZE

#  define CORE2_PFLASH_KERNEL_START  BANKA_CORE2_PFLASH_KERNEL_START
#  define CORE2_PFLASH_KERNEL_SIZE   BANKA_CORE2_PFLASH_KERNEL_SIZE
#  define CORE2_PFLASH_USER_START    BANKA_CORE2_PFLASH_USER_START
#  define CORE2_PFLASH_USER_SIZE     BANKA_CORE2_PFLASH_USER_SIZE

#  define CORE3_PFLASH_KERNEL_START  BANKA_CORE3_PFLASH_KERNEL_START
#  define CORE3_PFLASH_KERNEL_SIZE   BANKA_CORE3_PFLASH_KERNEL_SIZE
#  define CORE3_PFLASH_USER_START    BANKA_CORE3_PFLASH_USER_START
#  define CORE3_PFLASH_USER_SIZE     BANKA_CORE3_PFLASH_USER_SIZE

#  define CORE4_PFLASH_KERNEL_START  BANKA_CORE4_PFLASH_KERNEL_START
#  define CORE4_PFLASH_KERNEL_SIZE   BANKA_CORE4_PFLASH_KERNEL_SIZE
#  define CORE4_PFLASH_USER_START    BANKA_CORE4_PFLASH_USER_START
#  define CORE4_PFLASH_USER_SIZE     BANKA_CORE4_PFLASH_USER_SIZE

#  define CORE5_PFLASH_KERNEL_START  BANKA_CORE5_PFLASH_KERNEL_START
#  define CORE5_PFLASH_KERNEL_SIZE   BANKA_CORE5_PFLASH_KERNEL_SIZE
#  define CORE5_PFLASH_USER_START    BANKA_CORE5_PFLASH_USER_START
#  define CORE5_PFLASH_USER_SIZE     BANKA_CORE5_PFLASH_USER_SIZE

#endif

#define BL_PFLASH_START             BANKA_BL_PFLASH_START
#define BL_PFLASH_SIZE              BANKA_BL_PFLASH_SIZE
#define BL_DLMU_START               CORE0_DLMU_KERNEL_START
#define BL_DLMU_SIZE                CORE0_DLMU_KERNEL_SIZE
#define BL_DSPR_START               CORE0_DSPR_KERNEL_START
#define BL_DSPR_SIZE                CORE0_DSPR_KERNEL_SIZE
#define BL_PSPR_START               CORE0_PSPR_KERNEL_START
#define BL_PSPR_SIZE                CORE0_PSPR_KERNEL_SIZE
#define MBF_HASH_START              BANKA_MBF_HASH_START
#define MBF_HASH_SIZE               BANKA_MBF_HASH_SIZE

#define NC_START(addr)    \
  ((addr) >= 0x80000000 && (addr) <= 0x9FFFFFFF ? (addr) + 0x20000000 : (addr))

#define AURIX_PERIPHERAL_BASE_ADDR   0xF0000000
#define AURIX_PERIPHERAL_SIZE        0x0B720000

#define DSPR_LOCAL_START             0xD0000000
#define PSPR_LOCAL_START             0xC0000000

#define BACKGROUND_START             0x0
#define BACKGROUND_SIZE              0xFFFFFFFF

#define CORE0_DCACHE_KERNEL_START    0x7003C000
#define CORE0_DCACHE_KERNEL_SIZE     0x4000
#define CORE1_DCACHE_KERNEL_START    0x6003C000
#define CORE1_DCACHE_KERNEL_SIZE     0x4000
#define CORE2_DCACHE_KERNEL_START    0x50018000
#define CORE2_DCACHE_KERNEL_SIZE     0x4000
#define CORE3_DCACHE_KERNEL_START    0x40018000
#define CORE3_DCACHE_KERNEL_SIZE     0x4000
#define CORE4_DCACHE_KERNEL_START    0x30018000
#define CORE4_DCACHE_KERNEL_SIZE     0x4000
#define CORE5_DCACHE_KERNEL_START    0x10018000
#define CORE5_DCACHE_KERNEL_SIZE     0x4000

#define CORE_PFLASH_KERNEL_START(COREID)           CORE##COREID##_PFLASH_KERNEL_START
#define CORE_PFLASH_KERNEL_SIZE(COREID)            CORE##COREID##_PFLASH_KERNEL_SIZE
#define GENERATE_CORE_PFLASH_KERNEL_START(COREID)  CORE_PFLASH_KERNEL_START(COREID)
#define GENERATE_CORE_PFLASH_KERNEL_SIZE(COREID)   CORE_PFLASH_KERNEL_SIZE(COREID)

#define CORE_STACK_KERNEL_START(COREID)            CORE##COREID##_STACK_KERNEL_START
#define CORE_STACK_KERNEL_SIZE(COREID)             CORE##COREID##_STACK_KERNEL_SIZE
#define GENERATE_CORE_STACK_KERNEL_START(COREID)   CORE_STACK_KERNEL_START(COREID)
#define GENERATE_CORE_STACK_KERNEL_SIZE(COREID)    CORE_STACK_KERNEL_SIZE(COREID)

#define CORE_DSPR_KERNEL_START(COREID)             CORE##COREID##_DSPR_KERNEL_START
#define CORE_DSPR_KERNEL_SIZE(COREID)              CORE##COREID##_DSPR_KERNEL_SIZE
#define GENERATE_CORE_DSPR_KERNEL_START(COREID)    CORE_DSPR_KERNEL_START(COREID)
#define GENERATE_CORE_DSPR_KERNEL_SIZE(COREID)     CORE_DSPR_KERNEL_SIZE(COREID)

#define CORE_PSPR_KERNEL_START(COREID)             CORE##COREID##_PSPR_KERNEL_START
#define CORE_PSPR_KERNEL_SIZE(COREID)              CORE##COREID##_PSPR_KERNEL_SIZE
#define GENERATE_CORE_PSPR_KERNEL_START(COREID)    CORE_PSPR_KERNEL_START(COREID)
#define GENERATE_CORE_PSPR_KERNEL_SIZE(COREID)     CORE_PSPR_KERNEL_SIZE(COREID)

#define CORE_DLMU_KERNEL_START(COREID)             CORE##COREID##_DLMU_KERNEL_START
#define CORE_DLMU_KERNEL_SIZE(COREID)              CORE##COREID##_DLMU_KERNEL_SIZE
#define GENERATE_CORE_DLMU_KERNEL_START(COREID)    CORE_DLMU_KERNEL_START(COREID)
#define GENERATE_CORE_DLMU_KERNEL_SIZE(COREID)     CORE_DLMU_KERNEL_SIZE(COREID)

#define CORE_DCACHE_KERNEL_START(COREID)           CORE##COREID##_DCACHE_KERNEL_START
#define CORE_DCACHE_KERNEL_SIZE(COREID)            CORE##COREID##_DCACHE_KERNEL_SIZE
#define GENERATE_CORE_DCACHE_KERNEL_START(COREID)  CORE_DCACHE_KERNEL_START(COREID)
#define GENERATE_CORE_DCACHE_KERNEL_SIZE(COREID)   CORE_DCACHE_KERNEL_SIZE(COREID)

#ifndef CONFIG_BUILD_FLAT

#define CORE_PFLASH_USER_START(COREID)             CORE##COREID##_PFLASH_USER_START
#define CORE_PFLASH_USER_SIZE(COREID)              CORE##COREID##_PFLASH_USER_SIZE
#define GENERATE_CORE_PFLASH_USER_START(COREID)    CORE_PFLASH_USER_START(COREID)
#define GENERATE_CORE_PFLASH_USER_SIZE(COREID)     CORE_PFLASH_USER_SIZE(COREID)

#define CORE_STACK_USER_START(COREID)              CORE##COREID##_STACK_USER_START
#define CORE_STACK_USER_SIZE(COREID)               CORE##COREID##_STACK_USER_SIZE
#define GENERATE_CORE_STACK_USER_START(COREID)     CORE_STACK_USER_START(COREID)
#define GENERATE_CORE_STACK_USER_SIZE(COREID)      CORE_STACK_USER_SIZE(COREID)

#define CORE_DSPR_USER_START(COREID)               CORE##COREID##_DSPR_USER_START
#define CORE_DSPR_USER_SIZE(COREID)                CORE##COREID##_DSPR_USER_SIZE
#define GENERATE_CORE_DSPR_USER_START(COREID)      CORE_DSPR_USER_START(COREID)
#define GENERATE_CORE_DSPR_USER_SIZE(COREID)       CORE_DSPR_USER_SIZE(COREID)

#define CORE_PSPR_USER_START(COREID)               CORE##COREID##_PSPR_USER_START
#define CORE_PSPR_USER_SIZE(COREID)                CORE##COREID##_PSPR_USER_SIZE
#define GENERATE_CORE_PSPR_USER_START(COREID)      CORE_PSPR_USER_START(COREID)
#define GENERATE_CORE_PSPR_USER_SIZE(COREID)       CORE_PSPR_USER_SIZE(COREID)

#define CORE_DLMU_USER_START(COREID)               CORE##COREID##_DLMU_USER_START
#define CORE_DLMU_USER_SIZE(COREID)                CORE##COREID##_DLMU_USER_SIZE
#define GENERATE_CORE_DLMU_USER_START(COREID)      CORE_DLMU_USER_START(COREID)
#define GENERATE_CORE_DLMU_USER_SIZE(COREID)       CORE_DLMU_USER_SIZE(COREID)

#endif

/****************************************************************************
 * Public Data
 ****************************************************************************/

#ifndef __ASSEMBLY__

#undef EXTERN
#if defined(__cplusplus)
#define EXTERN extern "C"
extern "C"
{
#else
#define EXTERN extern
#endif

/****************************************************************************
 * Public Function Prototypes
 ****************************************************************************/

#undef EXTERN
#if defined(__cplusplus)
}
#endif

#endif /* __ASSEMBLY__ */

#endif /* __BOARDS_TRICORE_TC397_A2G_TC397_5V_TFT_INCLUDE_BOARD_MEMORYMAP_H */
