# This file is generated automatically by : python menuconfig.py -s /home/raul_chen/nuttx/nuttx/boards/arm/rtl8721dx/pke8721daf/ameba_sdk.conf
CONFIG_SHELL=n
CONFIG_SUPPORT_ATCMD=n
CONFIG_ATCMD_NETWORK=n
CONFIG_LOGUART_AGG_EN=y
