/**
 * @copyright (c) 2003 - 2021, Goodix Co., Ltd. All rights reserved.
 *
 * @file    gh3x2x_demo_algorithm.c
 *
 * @brief   gh3x2x driver lib demo code for algorithm
 *
 * @author  Gooidx Iot Team
 *
 */

#include "gh3x2x_inner.h"


#if (__DRIVER_LIB_MODE__ == __DRV_LIB_WITH_ALGO__)








#if (__ALGO_RUN_SIMULTANEOUSLY_SUPPORT__)
#define   GH3X2X_ALGORITHMS_MEMORY_RESIDENT    ((__USE_GOODIX_HR_ALGORITHM__ * GH3X2X_ALGORITHM_HR_MEMORY_RESIDENT) + \
                                            (__USE_GOODIX_SPO2_ALGORITHM__ * GH3X2X_ALGORITHM_SPO2_MEMORY_RESIDENT) + \
                                            (__USE_GOODIX_ECG_ALGORITHM__ * GH3X2X_ALGORITHM_ECG_MEMORY_RESIDENT) + \
                                            (__USE_GOODIX_HRV_ALGORITHM__ * GH3X2X_ALGORITHM_HRV_MEMORY_RESIDENT) + \
                                            (__USE_GOODIX_HSM_ALGORITHM__ * GH3X2X_ALGORITHM_HSM_MEMORY_RESIDENT) + \
                                            (__USE_GOODIX_BT_ALGORITHM__ * GH3X2X_ALGORITHM_BT_MEMORY_RESIDENT) + \
                                            (__USE_GOODIX_RESP_ALGORITHM__ * GH3X2X_ALGORITHM_RESP_MEMORY_RESIDENT) + \
                                            (__USE_GOODIX_AF_ALGORITHM__ * GH3X2X_ALGORITHM_AF_MEMORY_RESIDENT) + \
                                            (__USE_GOODIX_SOFT_ADT_ALGORITHM__ * GH3X2X_ALGORITHM_SOFT_ADT_MEMORY_RESIDENT) + \
                                            (__USE_GOODIX_BP_ALGORITHM__ * GH3X2X_ALGORITHM_BP_MEMORY_RESIDENT))
//resident
#define GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT  (0)
#if GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT < GH3X2X_ALGORITHM_HR_MEMORY_PEAK_WITHOUT_RESIDENT
#undef GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT
#define GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT GH3X2X_ALGORITHM_HR_MEMORY_PEAK_WITHOUT_RESIDENT
#endif
#if GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT < GH3X2X_ALGORITHM_SPO2_MEMORY_PEAK_WITHOUT_RESIDENT
#undef GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT
#define GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT GH3X2X_ALGORITHM_SPO2_MEMORY_PEAK_WITHOUT_RESIDENT
#endif
#if GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT < GH3X2X_ALGORITHM_ECG_MEMORY_PEAK_WITHOUT_RESIDENT
#undef GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT
#define GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT GH3X2X_ALGORITHM_ECG_MEMORY_PEAK_WITHOUT_RESIDENT
#endif
#if GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT < GH3X2X_ALGORITHM_HRV_MEMORY_PEAK_WITHOUT_RESIDENT
#undef GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT
#define GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT GH3X2X_ALGORITHM_HRV_MEMORY_PEAK_WITHOUT_RESIDENT
#endif
#if GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT < GH3X2X_ALGORITHM_HSM_MEMORY_PEAK_WITHOUT_RESIDENT
#undef GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT
#define GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT GH3X2X_ALGORITHM_HSM_MEMORY_PEAK_WITHOUT_RESIDENT
#endif
#if GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT < GH3X2X_ALGORITHM_BT_MEMORY_PEAK_WITHOUT_RESIDENT
#undef GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT
#define GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT GH3X2X_ALGORITHM_BT_MEMORY_PEAK_WITHOUT_RESIDENT
#endif
#if GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT < GH3X2X_ALGORITHM_RESP_MEMORY_PEAK_WITHOUT_RESIDENT
#undef GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT
#define GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT GH3X2X_ALGORITHM_RESP_MEMORY_PEAK_WITHOUT_RESIDENT
#endif
#if GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT < GH3X2X_ALGORITHM_AF_MEMORY_PEAK_WITHOUT_RESIDENT
#undef GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT
#define GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT GH3X2X_ALGORITHM_AF_MEMORY_PEAK_WITHOUT_RESIDENT
#endif
#if GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT < GH3X2X_ALGORITHM_SOFT_ADT_MEMORY_PEAK_WITHOUT_RESIDENT
#undef GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT
#define GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT GH3X2X_ALGORITHM_SOFT_ADT_MEMORY_PEAK_WITHOUT_RESIDENT
#endif
//redundancy
#if GH3X2X_ALGORITHMS_MEMORY_REDUNDANCY < GH3X2X_ALGORITHM_HR_MEMORY_REDUNDANCY
#undef GH3X2X_ALGORITHMS_MEMORY_REDUNDANCY
#define GH3X2X_ALGORITHMS_MEMORY_REDUNDANCY GH3X2X_ALGORITHM_HR_MEMORY_REDUNDANCY
#endif
#if GH3X2X_ALGORITHMS_MEMORY_REDUNDANCY < GH3X2X_ALGORITHM_SPO2_MEMORY_REDUNDANCY
#undef GH3X2X_ALGORITHMS_MEMORY_REDUNDANCY
#define GH3X2X_ALGORITHMS_MEMORY_REDUNDANCY GH3X2X_ALGORITHM_SPO2_MEMORY_REDUNDANCY
#endif
#if GH3X2X_ALGORITHMS_MEMORY_REDUNDANCY < GH3X2X_ALGORITHM_ECG_MEMORY_REDUNDANCY
#undef GH3X2X_ALGORITHMS_MEMORY_REDUNDANCY
#define GH3X2X_ALGORITHMS_MEMORY_REDUNDANCY GH3X2X_ALGORITHM_ECG_MEMORY_REDUNDANCY
#endif
#if GH3X2X_ALGORITHMS_MEMORY_REDUNDANCY < GH3X2X_ALGORITHM_HRV_MEMORY_REDUNDANCY
#undef GH3X2X_ALGORITHMS_MEMORY_REDUNDANCY
#define GH3X2X_ALGORITHMS_MEMORY_REDUNDANCY GH3X2X_ALGORITHM_HRV_MEMORY_REDUNDANCY
#endif
#if GH3X2X_ALGORITHMS_MEMORY_REDUNDANCY < GH3X2X_ALGORITHM_HSM_MEMORY_REDUNDANCY
#undef GH3X2X_ALGORITHMS_MEMORY_REDUNDANCY
#define GH3X2X_ALGORITHMS_MEMORY_REDUNDANCY GH3X2X_ALGORITHM_HSM_MEMORY_REDUNDANCY
#endif
#if GH3X2X_ALGORITHMS_MEMORY_REDUNDANCY < GH3X2X_ALGORITHM_BT_MEMORY_REDUNDANCY
#undef GH3X2X_ALGORITHMS_MEMORY_REDUNDANCY
#define GH3X2X_ALGORITHMS_MEMORY_REDUNDANCY GH3X2X_ALGORITHM_BT_MEMORY_REDUNDANCY
#endif
#if GH3X2X_ALGORITHMS_MEMORY_REDUNDANCY < GH3X2X_ALGORITHM_RESP_MEMORY_REDUNDANCY
#undef GH3X2X_ALGORITHMS_MEMORY_REDUNDANCY
#define GH3X2X_ALGORITHMS_MEMORY_REDUNDANCY GH3X2X_ALGORITHM_RESP_MEMORY_REDUNDANCY
#endif
#if GH3X2X_ALGORITHMS_MEMORY_REDUNDANCY < GH3X2X_ALGORITHM_AF_MEMORY_REDUNDANCY
#undef GH3X2X_ALGORITHMS_MEMORY_REDUNDANCY
#define GH3X2X_ALGORITHMS_MEMORY_REDUNDANCY GH3X2X_ALGORITHM_AF_MEMORY_REDUNDANCY
#endif
#if GH3X2X_ALGORITHMS_MEMORY_REDUNDANCY < GH3X2X_ALGORITHM_SOFT_ADT_MEMORY_REDUNDANCY
#undef GH3X2X_ALGORITHMS_MEMORY_REDUNDANCY
#define GH3X2X_ALGORITHMS_MEMORY_REDUNDANCY GH3X2X_ALGORITHM_SOFT_ADT_MEMORY_REDUNDANCY
#endif

//final size
#define GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL  ( ((GU32)((GH3X2X_ALGORITHMS_MEMORY_RESIDENT + GH3X2X_ALGORITHMS_MEMORY_PEAK_WITHOUT_RESIDENT + GH3X2X_ALGORITHMS_MEMORY_REDUNDANCY + 3)/4))*4)



#else  //__ALGO_RUN_SIMULTANEOUSLY_SUPPORT__



#define GH3X2X_ALGORITHMS_MEMORY_SIZE (0)
#if __USE_GOODIX_HR_ALGORITHM__
#if (GH3X2X_ALGORITHM_HR_MEMORY_RESIDENT + GH3X2X_ALGORITHM_HR_MEMORY_PEAK_WITHOUT_RESIDENT + GH3X2X_ALGORITHM_HR_MEMORY_REDUNDANCY) > GH3X2X_ALGORITHMS_MEMORY_SIZE
#undef GH3X2X_ALGORITHMS_MEMORY_SIZE
#define GH3X2X_ALGORITHMS_MEMORY_SIZE (GH3X2X_ALGORITHM_HR_MEMORY_RESIDENT + GH3X2X_ALGORITHM_HR_MEMORY_PEAK_WITHOUT_RESIDENT + GH3X2X_ALGORITHM_HR_MEMORY_REDUNDANCY)
#endif
#endif
#if __USE_GOODIX_SOFT_ADT_ALGORITHM__     //hr and soft is running at same time
#undef GH3X2X_ALGORITHMS_MEMORY_SIZE
#define GH3x2x_TEMP_PEAK_WITHOUT_RESIDENT GH3X2X_ALGORITHM_HR_MEMORY_PEAK_WITHOUT_RESIDENT
#if GH3x2x_TEMP_PEAK_WITHOUT_RESIDENT < GH3X2X_ALGORITHM_SOFT_ADT_MEMORY_PEAK_WITHOUT_RESIDENT
#undef GH3x2x_TEMP_PEAK_WITHOUT_RESIDENT
#define GH3x2x_TEMP_PEAK_WITHOUT_RESIDENT GH3X2X_ALGORITHM_SOFT_ADT_MEMORY_PEAK_WITHOUT_RESIDENT
#endif
#define GH3x2x_TEMP_REDUNDANCY GH3X2X_ALGORITHM_HR_MEMORY_REDUNDANCY
#if GH3x2x_TEMP_REDUNDANCY < GH3X2X_ALGORITHM_SOFT_ADT_MEMORY_REDUNDANCY
#undef GH3x2x_TEMP_REDUNDANCY
#define GH3x2x_TEMP_REDUNDANCY GH3X2X_ALGORITHM_SOFT_ADT_MEMORY_REDUNDANCY
#endif
#define GH3X2X_ALGORITHMS_MEMORY_SIZE (GH3X2X_ALGORITHM_HR_MEMORY_RESIDENT + GH3X2X_ALGORITHM_SOFT_ADT_MEMORY_RESIDENT + GH3x2x_TEMP_PEAK_WITHOUT_RESIDENT + GH3x2x_TEMP_REDUNDANCY)
#endif
#if __USE_GOODIX_SPO2_ALGORITHM__
#if (GH3X2X_ALGORITHM_SPO2_MEMORY_RESIDENT + GH3X2X_ALGORITHM_SPO2_MEMORY_PEAK_WITHOUT_RESIDENT + GH3X2X_ALGORITHM_SPO2_MEMORY_REDUNDANCY) > GH3X2X_ALGORITHMS_MEMORY_SIZE
#undef GH3X2X_ALGORITHMS_MEMORY_SIZE
#define GH3X2X_ALGORITHMS_MEMORY_SIZE (GH3X2X_ALGORITHM_SPO2_MEMORY_RESIDENT + GH3X2X_ALGORITHM_SPO2_MEMORY_PEAK_WITHOUT_RESIDENT + GH3X2X_ALGORITHM_SPO2_MEMORY_REDUNDANCY)
#endif
#endif

#if __USE_GOODIX_HRV_ALGORITHM__
#if (GH3X2X_ALGORITHM_HRV_MEMORY_RESIDENT + GH3X2X_ALGORITHM_HRV_MEMORY_PEAK_WITHOUT_RESIDENT + GH3X2X_ALGORITHM_HRV_MEMORY_REDUNDANCY) > GH3X2X_ALGORITHMS_MEMORY_SIZE
#undef GH3X2X_ALGORITHMS_MEMORY_SIZE
#define GH3X2X_ALGORITHMS_MEMORY_SIZE (GH3X2X_ALGORITHM_HRV_MEMORY_RESIDENT + GH3X2X_ALGORITHM_HRV_MEMORY_PEAK_WITHOUT_RESIDENT + GH3X2X_ALGORITHM_HRV_MEMORY_REDUNDANCY)
#endif
#endif
#if __USE_GOODIX_ECG_ALGORITHM__
#if (GH3X2X_ALGORITHM_ECG_MEMORY_RESIDENT + GH3X2X_ALGORITHM_ECG_MEMORY_PEAK_WITHOUT_RESIDENT + GH3X2X_ALGORITHM_ECG_MEMORY_REDUNDANCY) > GH3X2X_ALGORITHMS_MEMORY_SIZE
#undef GH3X2X_ALGORITHMS_MEMORY_SIZE
#define GH3X2X_ALGORITHMS_MEMORY_SIZE (GH3X2X_ALGORITHM_ECG_MEMORY_RESIDENT + GH3X2X_ALGORITHM_ECG_MEMORY_PEAK_WITHOUT_RESIDENT + GH3X2X_ALGORITHM_ECG_MEMORY_REDUNDANCY)
#endif
#endif
#if __USE_GOODIX_HSM_ALGORITHM__
#if (GH3X2X_ALGORITHM_HSM_MEMORY_RESIDENT + GH3X2X_ALGORITHM_HSM_MEMORY_PEAK_WITHOUT_RESIDENT + GH3X2X_ALGORITHM_HSM_MEMORY_REDUNDANCY) > GH3X2X_ALGORITHMS_MEMORY_SIZE
#undef GH3X2X_ALGORITHMS_MEMORY_SIZE
#define GH3X2X_ALGORITHMS_MEMORY_SIZE (GH3X2X_ALGORITHM_HSM_MEMORY_RESIDENT + GH3X2X_ALGORITHM_HSM_MEMORY_PEAK_WITHOUT_RESIDENT + GH3X2X_ALGORITHM_HSM_MEMORY_REDUNDANCY)
#endif
#endif
#if __USE_GOODIX_BT_ALGORITHM__
#if (GH3X2X_ALGORITHM_BT_MEMORY_RESIDENT + GH3X2X_ALGORITHM_BT_MEMORY_PEAK_WITHOUT_RESIDENT + GH3X2X_ALGORITHM_BT_MEMORY_REDUNDANCY) > GH3X2X_ALGORITHMS_MEMORY_SIZE
#undef GH3X2X_ALGORITHMS_MEMORY_SIZE
#define GH3X2X_ALGORITHMS_MEMORY_SIZE (GH3X2X_ALGORITHM_BT_MEMORY_RESIDENT + GH3X2X_ALGORITHM_BT_MEMORY_PEAK_WITHOUT_RESIDENT + GH3X2X_ALGORITHM_BT_MEMORY_REDUNDANCY)
#endif
#endif
#if __USE_GOODIX_RESP_ALGORITHM__
#if (GH3X2X_ALGORITHM_RESP_MEMORY_RESIDENT + GH3X2X_ALGORITHM_RESP_MEMORY_PEAK_WITHOUT_RESIDENT + GH3X2X_ALGORITHM_RESP_MEMORY_REDUNDANCY) > GH3X2X_ALGORITHMS_MEMORY_SIZE
#undef GH3X2X_ALGORITHMS_MEMORY_SIZE
#define GH3X2X_ALGORITHMS_MEMORY_SIZE (GH3X2X_ALGORITHM_RESP_MEMORY_RESIDENT + GH3X2X_ALGORITHM_RESP_MEMORY_PEAK_WITHOUT_RESIDENT + GH3X2X_ALGORITHM_RESP_MEMORY_REDUNDANCY)
#endif
#endif
#if __USE_GOODIX_AF_ALGORITHM__
#if (GH3X2X_ALGORITHM_AF_MEMORY_RESIDENT + GH3X2X_ALGORITHM_AF_MEMORY_PEAK_WITHOUT_RESIDENT + GH3X2X_ALGORITHM_AF_MEMORY_REDUNDANCY) > GH3X2X_ALGORITHMS_MEMORY_SIZE
#undef GH3X2X_ALGORITHMS_MEMORY_SIZE
#define GH3X2X_ALGORITHMS_MEMORY_SIZE (GH3X2X_ALGORITHM_AF_MEMORY_RESIDENT + GH3X2X_ALGORITHM_AF_MEMORY_PEAK_WITHOUT_RESIDENT + GH3X2X_ALGORITHM_AF_MEMORY_REDUNDANCY)
#endif
#endif
#if __USE_GOODIX_SOFT_ADT_ALGORITHM__
#if (GH3X2X_ALGORITHM_SOFT_ADT_MEMORY_RESIDENT + GH3X2X_ALGORITHM_SOFT_ADT_MEMORY_PEAK_WITHOUT_RESIDENT + GH3X2X_ALGORITHM_SOFT_ADT_MEMORY_REDUNDANCY) > GH3X2X_ALGORITHMS_MEMORY_SIZE
#undef GH3X2X_ALGORITHMS_MEMORY_SIZE
#define GH3X2X_ALGORITHMS_MEMORY_SIZE (GH3X2X_ALGORITHM_SOFT_ADT_MEMORY_RESIDENT + GH3X2X_ALGORITHM_SOFT_ADT_MEMORY_PEAK_WITHOUT_RESIDENT + GH3X2X_ALGORITHM_SOFT_ADT_MEMORY_REDUNDANCY)
#endif
#endif
#if __USE_GOODIX_BP_ALGORITHM__
#if (GH3X2X_ALGORITHM_BP_MEMORY_RESIDENT + GH3X2X_ALGORITHM_BP_MEMORY_PEAK_WITHOUT_RESIDENT + GH3X2X_ALGORITHM_BP_MEMORY_REDUNDANCY) > GH3X2X_ALGORITHMS_MEMORY_SIZE
#undef GH3X2X_ALGORITHMS_MEMORY_SIZE
#define GH3X2X_ALGORITHMS_MEMORY_SIZE (GH3X2X_ALGORITHM_BP_MEMORY_RESIDENT + GH3X2X_ALGORITHM_BP_MEMORY_PEAK_WITHOUT_RESIDENT + GH3X2X_ALGORITHM_BP_MEMORY_REDUNDANCY)
#endif
#endif

#define GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL  ( ((GU32)((GH3X2X_ALGORITHMS_MEMORY_SIZE  + 3)/4))*4)

#endif  //__ALGO_RUN_SIMULTANEOUSLY_SUPPORT__


#if __USER_DYNAMIC_ALGO_MEM_EN__
GU32 *g_punGh3x2xAlgoMemBufferPointer = 0;
#else
GU32 g_punGh3x2xAlgoMemBuffer[GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL/4] = {0};
GU32 *g_punGh3x2xAlgoMemBufferPointer = g_punGh3x2xAlgoMemBuffer;
#endif

#else  //without algorithm

#if (__USE_GOODIX_SOFT_ADT_ALGORITHM__)
#define   GH3X2X_ALGORITHMS_MEMORY_SIZE  (GH3X2X_ALGORITHM_SOFT_ADT_MEMORY_RESIDENT + GH3X2X_ALGORITHM_SOFT_ADT_MEMORY_PEAK_WITHOUT_RESIDENT + GH3X2X_ALGORITHM_SOFT_ADT_MEMORY_REDUNDANCY)
#define GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL  (((GU32)((GH3X2X_ALGORITHMS_MEMORY_SIZE + 3)/4))*4)
#if __USER_DYNAMIC_ALGO_MEM_EN__
GU32 *g_punGh3x2xAlgoMemBufferPointer = 0;
#else
GU32 g_punGh3x2xAlgoMemBuffer[GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL/4] = {0};
GU32 *g_punGh3x2xAlgoMemBufferPointer = g_punGh3x2xAlgoMemBuffer;
#endif
#endif
#endif






#if __GH3X2X_MEM_POOL_CHECK_EN__

const GU32 g_unGh3z2xMemCheckAreaStart[17] =
{
    0,
    GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*1/16,
    GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*2/16,
    GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*3/16,
    GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*4/16,
    GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*5/16,
    GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*6/16,
    GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*7/16,
    GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*8/16,
    GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*9/16,
    GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*10/16,
    GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*11/16,
    GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*12/16,
    GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*13/16,
    GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*14/16,
    GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*15/16,
    GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL,
};

GU32 g_unGh3x2xLastMemPoolCheckSumArea[16];



GU8  g_uchGh3x2xMemPollHaveGetCheckSum = 0;
GU16 g_usGh3x2xMemPollErrorFlag = 0;
GU32 Gh3x2xGetMemPoolCheckSum(GU8 *lunMemPool, GU32 lunByteSize)
{
    GU32 lunCheckSum = 0;
    for(GU32 lunByteCnt = 0; lunByteCnt < lunByteSize; lunByteCnt += 4)
    {
        lunCheckSum += *((GU32*)(lunMemPool+lunByteCnt));
    }

    return lunCheckSum;
}


void Gh3x2xMemPoolCheckSumWrite(GU8 *lunMemPool)
{
    for(GU8 uchAreaCnt = 0; uchAreaCnt < 16; uchAreaCnt ++)
    {
        g_unGh3x2xLastMemPoolCheckSumArea[uchAreaCnt] = Gh3x2xGetMemPoolCheckSum(lunMemPool + ((g_unGh3z2xMemCheckAreaStart[uchAreaCnt]/4)*4), (g_unGh3z2xMemCheckAreaStart[uchAreaCnt + 1]/4)*4 - (g_unGh3z2xMemCheckAreaStart[uchAreaCnt]/4)*4);
    }
    g_uchGh3x2xMemPollHaveGetCheckSum = 1;
}


GU16 Gh3x2xMemPoolCheckSumCheck(GU8 *lunMemPool)
{
    GU16 usErrorFlag = 0;

    if(0 == g_usGh3x2xMemPollErrorFlag)
    {
        for(GU8 uchAreaCnt = 0; uchAreaCnt < 16; uchAreaCnt ++)
        {
            if(g_unGh3x2xLastMemPoolCheckSumArea[uchAreaCnt] != Gh3x2xGetMemPoolCheckSum(lunMemPool + ((g_unGh3z2xMemCheckAreaStart[uchAreaCnt]/4)*4), (g_unGh3z2xMemCheckAreaStart[uchAreaCnt + 1]/4)*4 - (g_unGh3z2xMemCheckAreaStart[uchAreaCnt]/4)*4))
            {
                usErrorFlag |= (((GU16)1) << uchAreaCnt);
            }
        }
    }

    g_usGh3x2xMemPollErrorFlag = usErrorFlag;
    return usErrorFlag;
}


void Gh3x2xCheckMemPollBeforeAlgoCal(void)
{
    if(g_uchGh3x2xMemPollHaveGetCheckSum)
    {
        if(Gh3x2xMemPoolCheckSumCheck((GU8*)g_punGh3x2xAlgoMemBuffer))
        {
            EXAMPLE_LOG("Gh3x2x mem check error!!!  error flag = 0x%X\r\n", g_usGh3x2xMemPollErrorFlag);
            while(1);  //error !!!  mem pool is be destroy
        }
        EXAMPLE_LOG("Gh3x2x mem check ok, check sum 0  = 0x%X\r\n",g_unGh3x2xLastMemPoolCheckSumArea[0]);
        EXAMPLE_LOG("Gh3x2x mem check ok, check sum 1  = 0x%X\r\n",g_unGh3x2xLastMemPoolCheckSumArea[1]);
        EXAMPLE_LOG("Gh3x2x mem check ok, check sum 2  = 0x%X\r\n",g_unGh3x2xLastMemPoolCheckSumArea[2]);
        EXAMPLE_LOG("Gh3x2x mem check ok, check sum 3  = 0x%X\r\n",g_unGh3x2xLastMemPoolCheckSumArea[3]);
        EXAMPLE_LOG("Gh3x2x mem check ok, check sum 4  = 0x%X\r\n",g_unGh3x2xLastMemPoolCheckSumArea[4]);
        EXAMPLE_LOG("Gh3x2x mem check ok, check sum 5  = 0x%X\r\n",g_unGh3x2xLastMemPoolCheckSumArea[5]);
        EXAMPLE_LOG("Gh3x2x mem check ok, check sum 6  = 0x%X\r\n",g_unGh3x2xLastMemPoolCheckSumArea[6]);
        EXAMPLE_LOG("Gh3x2x mem check ok, check sum 7  = 0x%X\r\n",g_unGh3x2xLastMemPoolCheckSumArea[7]);
        EXAMPLE_LOG("Gh3x2x mem check ok, check sum 8  = 0x%X\r\n",g_unGh3x2xLastMemPoolCheckSumArea[8]);
        EXAMPLE_LOG("Gh3x2x mem check ok, check sum 9  = 0x%X\r\n",g_unGh3x2xLastMemPoolCheckSumArea[9]);
        EXAMPLE_LOG("Gh3x2x mem check ok, check sum 10  = 0x%X\r\n",g_unGh3x2xLastMemPoolCheckSumArea[10]);
        EXAMPLE_LOG("Gh3x2x mem check ok, check sum 11  = 0x%X\r\n",g_unGh3x2xLastMemPoolCheckSumArea[11]);
        EXAMPLE_LOG("Gh3x2x mem check ok, check sum 12  = 0x%X\r\n",g_unGh3x2xLastMemPoolCheckSumArea[12]);
        EXAMPLE_LOG("Gh3x2x mem check ok, check sum 13  = 0x%X\r\n",g_unGh3x2xLastMemPoolCheckSumArea[13]);
        EXAMPLE_LOG("Gh3x2x mem check ok, check sum 14  = 0x%X\r\n",g_unGh3x2xLastMemPoolCheckSumArea[14]);
        EXAMPLE_LOG("Gh3x2x mem check ok, check sum 15  = 0x%X\r\n",g_unGh3x2xLastMemPoolCheckSumArea[15]);
    }

}

void Gh3x2xUpdataMemPollChkSumAfterAlgoCal(void)
{

    Gh3x2xMemPoolCheckSumWrite((GU8*)g_punGh3x2xAlgoMemBuffer);


    //g_punGh3x2xAlgoMemBuffer[(GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*1/16)/4 - 1] = 0x3333;   //test
    //g_punGh3x2xAlgoMemBuffer[(GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*2/16)/4 - 1] = 0x3333;   //test
    //g_punGh3x2xAlgoMemBuffer[(GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*3/16)/4 - 1] = 0x3333;   //test
    //g_punGh3x2xAlgoMemBuffer[(GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*4/16)/4 - 1] = 0x3333;   //test
    //g_punGh3x2xAlgoMemBuffer[(GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*5/16)/4 - 1] = 0x3333;   //test
    //g_punGh3x2xAlgoMemBuffer[(GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*6/16)/4 - 1] = 0x3333;   //test
    //g_punGh3x2xAlgoMemBuffer[(GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*7/16)/4 - 1] = 0x3333;   //test
    //g_punGh3x2xAlgoMemBuffer[(GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*8/16)/4 - 1] = 0x3333;   //test
    //g_punGh3x2xAlgoMemBuffer[(GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*9/16)/4 - 1] = 0x3333;   //test
    //g_punGh3x2xAlgoMemBuffer[(GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*10/16)/4 - 1] = 0x3333;   //test
    //g_punGh3x2xAlgoMemBuffer[(GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*11/16)/4 - 1] = 0x3333;   //test
    //g_punGh3x2xAlgoMemBuffer[(GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*12/16)/4 - 1] = 0x3333;   //test
    //g_punGh3x2xAlgoMemBuffer[(GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*13/16)/4 - 1] = 0x3333;   //test
    //g_punGh3x2xAlgoMemBuffer[(GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*14/16)/4 - 1] = 0x3333;   //test
    //g_punGh3x2xAlgoMemBuffer[(GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*15/16)/4 - 1] = 0x3333;   //test
    //g_punGh3x2xAlgoMemBuffer[(GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL*16/16)/4 - 1] = 0x3333;   //test

}
#endif








#if ((__DRIVER_LIB_MODE__ == __DRV_LIB_WITH_ALGO__) || __USE_GOODIX_SOFT_ADT_ALGORITHM__)
/**
 * @fn     void Gh3x2x_DemoAlgorithmMemConfig(void)
 *
 * @brief  Config memory for algorithm
 *
 * @attention   None
 *
 * @param[in]   None
 * @param[out]  None
 *
 * @return  None
 */
void Gh3x2x_DemoAlgorithmMemConfig(void)
{
    GH3X2X_AlgoMemConfig(GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL);
    EXAMPLE_LOG("Algorithm mem size = %d\r\n",(int)GH3X2X_ALGORITHMS_MEMORY_SIZE_FINAL);
}
#endif


/**
 * @fn     void Gh3x2xDemoAlgorithmCalculate(GU8* puchReadFifoBuffer, STGsensorRawdata *pstGsAxisValueArr,
 *                                              GU16 usGsDataNum, EMGsensorSensitivity emGsSensitivity)
 *
 * @brief  Algorithm calculate.This function will be called in Gh3x2xDemoInterruptProcess()
 *
 * @attention   None
 *
 * @param[in]   puchReadFifoBuffer      point to gh3x2x fifo data buffer
 * @param[in]   pstGsAxisValueArr       point to gsensor data buffer
 * @param[in]   usGsDataNum             gsensor data cnt
 * @param[in]   emGsSensitivity         sensitivity of gsensor
 * @param[out]  None
 *
 * @return  None
 */
void Gh3x2x_DemoAlgorithmCalculate(GU8* puchReadFifoBuffer, GU16 usFifoBuffLen,STGsensorRawdata *pstGsAxisValueArr, GU16 usGsDataNum,
                                   STCapRawdata* pstCapValueArr,GU16 usCapDataNum,STTempRawdata* pstTempValueArr,GU16 usTempDataNum)
{
    for(GU8 uchFunCnt = 0; uchFunCnt < GH3X2X_FUNC_OFFSET_MAX; uchFunCnt ++)
    {
        if(g_pstGh3x2xFrameInfo[uchFunCnt])
        {

            if(g_unDemoFuncMode & (((GU32)1)<< uchFunCnt))
            {
                GH3x2xFunctionProcess(puchReadFifoBuffer,usFifoBuffLen,(GS16*)pstGsAxisValueArr,usGsDataNum,
                                        pstCapValueArr,usCapDataNum,pstTempValueArr,usTempDataNum,
                                        g_pstGh3x2xFrameInfo[uchFunCnt]);
            }
        }
    }
}



GU8 Gh3x2xGetHrAlgoSupportChnl(void)
{
    return __HR_ALGORITHM_SUPPORT_CHNL_NUM__;
}

GU8 Gh3x2xGetSpo2AlgoSupportChnl(void)
{
    return __SPO2_ALGORITHM_SUPPORT_CHNL_NUM__;
}

#if (__SUPPORT_ALGO_INPUT_OUTPUT_DATA_HOOK_CONFIG__ == 0 || __DRIVER_LIB_MODE__ == __DRV_LIB_WITHOUT_ALGO__)
void GH3x2xAlgoInfoRecordInputData(GS32 *snRawdataArray,GU8 uchChannelMapCnt ,GU32 unTimeStamp ,GU8 *uchChannelMapArr ,GU32 unFunctionID){}
void GH3x2xAlgoInfoRecordOutputData(GS32 *psnAlgoResult, GU8 uchResultNum){}
#endif











