/****************************************************************************
 * arch/arm/src/nrf54l/hardware/nrf54l_clock.h
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

#ifndef __ARCH_ARM_SRC_NRF54L_HARDWARE_NRF54L_CLOCK_H
#define __ARCH_ARM_SRC_NRF54L_HARDWARE_NRF54L_CLOCK_H

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <nuttx/config.h>

#include "nrf54l_memorymap.h"

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* Register offsets *********************************************************/

#define NRF54L_CLOCK_TASKS_XOSTART_OFFSET         0x0000 /* Start HFXO */
#define NRF54L_CLOCK_TASKS_XOSTOP_OFFSET          0x0004 /* Release HFXO request */
#define NRF54L_CLOCK_TASKS_PLLSTART_OFFSET        0x0008 /* Start PLL */
#define NRF54L_CLOCK_TASKS_PLLSTOP_OFFSET         0x000c /* Release PLL request */
#define NRF54L_CLOCK_TASKS_LFCLKSTART_OFFSET      0x0010 /* Start LFCLK */
#define NRF54L_CLOCK_TASKS_LFCLKSTOP_OFFSET       0x0014 /* Stop LFCLK */
#define NRF54L_CLOCK_TASKS_CAL_OFFSET             0x0018 /* Calibrate LFRC */
#define NRF54L_CLOCK_TASKS_XOTUNE_OFFSET          0x001c /* Tune HFXO */
#define NRF54L_CLOCK_TASKS_XOTUNEABORT_OFFSET     0x0020 /* Abort HFXO tuning */
#define NRF54L_CLOCK_TASKS_XO24MSTART_OFFSET      0x0024 /* Start 24 MHz clock */
#define NRF54L_CLOCK_TASKS_XO24MSTOP_OFFSET       0x0028 /* Stop 24 MHz clock */
#define NRF54L_CLOCK_SUBSCRIBE_XOSTART_OFFSET     0x0080 /* Subscribe to XOSTART task */
#define NRF54L_CLOCK_SUBSCRIBE_XOSTOP_OFFSET      0x0084 /* Subscribe to XOSTOP task */
#define NRF54L_CLOCK_SUBSCRIBE_PLLSTART_OFFSET    0x0088 /* Subscribe to PLLSTART task */
#define NRF54L_CLOCK_SUBSCRIBE_PLLSTOP_OFFSET     0x008c /* Subscribe to PLLSTOP task */
#define NRF54L_CLOCK_SUBSCRIBE_LFCLKSTART_OFFSET  0x0090 /* Subscribe to LFCLKSTART task */
#define NRF54L_CLOCK_SUBSCRIBE_LFCLKSTOP_OFFSET   0x0094 /* Subscribe to LFCLKSTOP task */
#define NRF54L_CLOCK_SUBSCRIBE_CAL_OFFSET         0x0098 /* Subscribe to CAL task */
#define NRF54L_CLOCK_SUBSCRIBE_XOTUNE_OFFSET      0x009c /* Subscribe to XOTUNE task */
#define NRF54L_CLOCK_SUBSCRIBE_XOTUNEABORT_OFFSET 0x00a0 /* Subscribe to XOTUNEABORT task */
#define NRF54L_CLOCK_SUBSCRIBE_XO24MSTART_OFFSET  0x00a4 /* Subscribe to XO24MSTART task */
#define NRF54L_CLOCK_SUBSCRIBE_XO24MSTOP_OFFSET   0x00a8 /* Subscribe to XO24MSTOP task */
#define NRF54L_CLOCK_EVENTS_XOSTARTED_OFFSET      0x0100 /* HFXO started */
#define NRF54L_CLOCK_EVENTS_PLLSTARTED_OFFSET     0x0104 /* PLL started */
#define NRF54L_CLOCK_EVENTS_LFCLKSTARTED_OFFSET   0x0108 /* LFCLK started */
#define NRF54L_CLOCK_EVENTS_DONE_OFFSET           0x010c /* LFRC calibration completed */
#define NRF54L_CLOCK_EVENTS_XOTUNED_OFFSET        0x0110 /* HFXO tuning completed */
#define NRF54L_CLOCK_EVENTS_XOTUNEERROR_OFFSET    0x0114 /* HFXO requires tuning */
#define NRF54L_CLOCK_EVENTS_XOTUNEFAILED_OFFSET   0x0118 /* HFXO tuning failed */
#define NRF54L_CLOCK_EVENTS_XO24MSTARTED_OFFSET   0x011c /* 24 MHz clock started */
#define NRF54L_CLOCK_PUBLISH_XOSTARTED_OFFSET     0x0180 /* Publish XOSTARTED event */
#define NRF54L_CLOCK_PUBLISH_PLLSTARTED_OFFSET    0x0184 /* Publish PLLSTARTED event */
#define NRF54L_CLOCK_PUBLISH_LFCLKSTARTED_OFFSET  0x0188 /* Publish LFCLKSTARTED event */
#define NRF54L_CLOCK_PUBLISH_DONE_OFFSET          0x018c /* Publish DONE event */
#define NRF54L_CLOCK_PUBLISH_XOTUNED_OFFSET       0x0190 /* Publish XOTUNED event */
#define NRF54L_CLOCK_PUBLISH_XOTUNEERROR_OFFSET   0x0194 /* Publish XOTUNEERROR event */
#define NRF54L_CLOCK_PUBLISH_XOTUNEFAILED_OFFSET  0x0198 /* Publish XOTUNEFAILED event */
#define NRF54L_CLOCK_PUBLISH_XO24MSTARTED_OFFSET  0x019c /* Publish XO24MSTARTED event */
#define NRF54L_CLOCK_INTEN_OFFSET                 0x0300 /* Enable or disable interrupts */
#define NRF54L_CLOCK_INTENSET_OFFSET              0x0304 /* Enable interrupts */
#define NRF54L_CLOCK_INTENCLR_OFFSET              0x0308 /* Disable interrupts */
#define NRF54L_CLOCK_INTPEND_OFFSET               0x030c /* Pending interrupts */
#define NRF54L_CLOCK_XO_RUN_OFFSET                0x0408 /* HFXO start request status */
#define NRF54L_CLOCK_XO_STAT_OFFSET               0x040c /* HFXO clock status */
#define NRF54L_CLOCK_PLL_RUN_OFFSET               0x0428 /* PLL start request status */
#define NRF54L_CLOCK_PLL_STAT_OFFSET              0x042c /* PLL clock status */
#define NRF54L_CLOCK_LFCLK_SRC_OFFSET             0x0440 /* LFCLK source selection */
#define NRF54L_CLOCK_LFCLK_RUN_OFFSET             0x0448 /* LFCLK start request status */
#define NRF54L_CLOCK_LFCLK_STAT_OFFSET            0x044c /* LFCLK clock status */
#define NRF54L_CLOCK_LFCLK_SRCCOPY_OFFSET         0x0450 /* LFCLK source latched at start */
#define NRF54L_CLOCK_PLL24M_RUN_OFFSET            0x0468 /* 24 MHz clock start request status */
#define NRF54L_CLOCK_PLL24M_STAT_OFFSET           0x046c /* 24 MHz clock status */

/* Register addresses *******************************************************/

#define NRF54L_CLOCK_TASKS_XOSTART         (NRF54L_CLOCK_BASE + NRF54L_CLOCK_TASKS_XOSTART_OFFSET)
#define NRF54L_CLOCK_TASKS_XOSTOP          (NRF54L_CLOCK_BASE + NRF54L_CLOCK_TASKS_XOSTOP_OFFSET)
#define NRF54L_CLOCK_TASKS_PLLSTART        (NRF54L_CLOCK_BASE + NRF54L_CLOCK_TASKS_PLLSTART_OFFSET)
#define NRF54L_CLOCK_TASKS_PLLSTOP         (NRF54L_CLOCK_BASE + NRF54L_CLOCK_TASKS_PLLSTOP_OFFSET)
#define NRF54L_CLOCK_TASKS_LFCLKSTART      (NRF54L_CLOCK_BASE + NRF54L_CLOCK_TASKS_LFCLKSTART_OFFSET)
#define NRF54L_CLOCK_TASKS_LFCLKSTOP       (NRF54L_CLOCK_BASE + NRF54L_CLOCK_TASKS_LFCLKSTOP_OFFSET)
#define NRF54L_CLOCK_TASKS_CAL             (NRF54L_CLOCK_BASE + NRF54L_CLOCK_TASKS_CAL_OFFSET)
#define NRF54L_CLOCK_TASKS_XOTUNE          (NRF54L_CLOCK_BASE + NRF54L_CLOCK_TASKS_XOTUNE_OFFSET)
#define NRF54L_CLOCK_TASKS_XOTUNEABORT     (NRF54L_CLOCK_BASE + NRF54L_CLOCK_TASKS_XOTUNEABORT_OFFSET)
#define NRF54L_CLOCK_TASKS_XO24MSTART      (NRF54L_CLOCK_BASE + NRF54L_CLOCK_TASKS_XO24MSTART_OFFSET)
#define NRF54L_CLOCK_TASKS_XO24MSTOP       (NRF54L_CLOCK_BASE + NRF54L_CLOCK_TASKS_XO24MSTOP_OFFSET)
#define NRF54L_CLOCK_SUBSCRIBE_XOSTART     (NRF54L_CLOCK_BASE + NRF54L_CLOCK_SUBSCRIBE_XOSTART_OFFSET)
#define NRF54L_CLOCK_SUBSCRIBE_XOSTOP      (NRF54L_CLOCK_BASE + NRF54L_CLOCK_SUBSCRIBE_XOSTOP_OFFSET)
#define NRF54L_CLOCK_SUBSCRIBE_PLLSTART    (NRF54L_CLOCK_BASE + NRF54L_CLOCK_SUBSCRIBE_PLLSTART_OFFSET)
#define NRF54L_CLOCK_SUBSCRIBE_PLLSTOP     (NRF54L_CLOCK_BASE + NRF54L_CLOCK_SUBSCRIBE_PLLSTOP_OFFSET)
#define NRF54L_CLOCK_SUBSCRIBE_LFCLKSTART  (NRF54L_CLOCK_BASE + NRF54L_CLOCK_SUBSCRIBE_LFCLKSTART_OFFSET)
#define NRF54L_CLOCK_SUBSCRIBE_LFCLKSTOP   (NRF54L_CLOCK_BASE + NRF54L_CLOCK_SUBSCRIBE_LFCLKSTOP_OFFSET)
#define NRF54L_CLOCK_SUBSCRIBE_CAL         (NRF54L_CLOCK_BASE + NRF54L_CLOCK_SUBSCRIBE_CAL_OFFSET)
#define NRF54L_CLOCK_SUBSCRIBE_XOTUNE      (NRF54L_CLOCK_BASE + NRF54L_CLOCK_SUBSCRIBE_XOTUNE_OFFSET)
#define NRF54L_CLOCK_SUBSCRIBE_XOTUNEABORT (NRF54L_CLOCK_BASE + NRF54L_CLOCK_SUBSCRIBE_XOTUNEABORT_OFFSET)
#define NRF54L_CLOCK_SUBSCRIBE_XO24MSTART  (NRF54L_CLOCK_BASE + NRF54L_CLOCK_SUBSCRIBE_XO24MSTART_OFFSET)
#define NRF54L_CLOCK_SUBSCRIBE_XO24MSTOP   (NRF54L_CLOCK_BASE + NRF54L_CLOCK_SUBSCRIBE_XO24MSTOP_OFFSET)
#define NRF54L_CLOCK_EVENTS_XOSTARTED      (NRF54L_CLOCK_BASE + NRF54L_CLOCK_EVENTS_XOSTARTED_OFFSET)
#define NRF54L_CLOCK_EVENTS_PLLSTARTED     (NRF54L_CLOCK_BASE + NRF54L_CLOCK_EVENTS_PLLSTARTED_OFFSET)
#define NRF54L_CLOCK_EVENTS_LFCLKSTARTED   (NRF54L_CLOCK_BASE + NRF54L_CLOCK_EVENTS_LFCLKSTARTED_OFFSET)
#define NRF54L_CLOCK_EVENTS_DONE           (NRF54L_CLOCK_BASE + NRF54L_CLOCK_EVENTS_DONE_OFFSET)
#define NRF54L_CLOCK_EVENTS_XOTUNED        (NRF54L_CLOCK_BASE + NRF54L_CLOCK_EVENTS_XOTUNED_OFFSET)
#define NRF54L_CLOCK_EVENTS_XOTUNEERROR    (NRF54L_CLOCK_BASE + NRF54L_CLOCK_EVENTS_XOTUNEERROR_OFFSET)
#define NRF54L_CLOCK_EVENTS_XOTUNEFAILED   (NRF54L_CLOCK_BASE + NRF54L_CLOCK_EVENTS_XOTUNEFAILED_OFFSET)
#define NRF54L_CLOCK_EVENTS_XO24MSTARTED   (NRF54L_CLOCK_BASE + NRF54L_CLOCK_EVENTS_XO24MSTARTED_OFFSET)
#define NRF54L_CLOCK_PUBLISH_XOSTARTED     (NRF54L_CLOCK_BASE + NRF54L_CLOCK_PUBLISH_XOSTARTED_OFFSET)
#define NRF54L_CLOCK_PUBLISH_PLLSTARTED    (NRF54L_CLOCK_BASE + NRF54L_CLOCK_PUBLISH_PLLSTARTED_OFFSET)
#define NRF54L_CLOCK_PUBLISH_LFCLKSTARTED  (NRF54L_CLOCK_BASE + NRF54L_CLOCK_PUBLISH_LFCLKSTARTED_OFFSET)
#define NRF54L_CLOCK_PUBLISH_DONE          (NRF54L_CLOCK_BASE + NRF54L_CLOCK_PUBLISH_DONE_OFFSET)
#define NRF54L_CLOCK_PUBLISH_XOTUNED       (NRF54L_CLOCK_BASE + NRF54L_CLOCK_PUBLISH_XOTUNED_OFFSET)
#define NRF54L_CLOCK_PUBLISH_XOTUNEERROR   (NRF54L_CLOCK_BASE + NRF54L_CLOCK_PUBLISH_XOTUNEERROR_OFFSET)
#define NRF54L_CLOCK_PUBLISH_XOTUNEFAILED  (NRF54L_CLOCK_BASE + NRF54L_CLOCK_PUBLISH_XOTUNEFAILED_OFFSET)
#define NRF54L_CLOCK_PUBLISH_XO24MSTARTED  (NRF54L_CLOCK_BASE + NRF54L_CLOCK_PUBLISH_XO24MSTARTED_OFFSET)
#define NRF54L_CLOCK_INTEN                 (NRF54L_CLOCK_BASE + NRF54L_CLOCK_INTEN_OFFSET)
#define NRF54L_CLOCK_INTENSET              (NRF54L_CLOCK_BASE + NRF54L_CLOCK_INTENSET_OFFSET)
#define NRF54L_CLOCK_INTENCLR              (NRF54L_CLOCK_BASE + NRF54L_CLOCK_INTENCLR_OFFSET)
#define NRF54L_CLOCK_INTPEND               (NRF54L_CLOCK_BASE + NRF54L_CLOCK_INTPEND_OFFSET)
#define NRF54L_CLOCK_XO_RUN                (NRF54L_CLOCK_BASE + NRF54L_CLOCK_XO_RUN_OFFSET)
#define NRF54L_CLOCK_XO_STAT               (NRF54L_CLOCK_BASE + NRF54L_CLOCK_XO_STAT_OFFSET)
#define NRF54L_CLOCK_PLL_RUN               (NRF54L_CLOCK_BASE + NRF54L_CLOCK_PLL_RUN_OFFSET)
#define NRF54L_CLOCK_PLL_STAT              (NRF54L_CLOCK_BASE + NRF54L_CLOCK_PLL_STAT_OFFSET)
#define NRF54L_CLOCK_LFCLK_SRC             (NRF54L_CLOCK_BASE + NRF54L_CLOCK_LFCLK_SRC_OFFSET)
#define NRF54L_CLOCK_LFCLK_RUN             (NRF54L_CLOCK_BASE + NRF54L_CLOCK_LFCLK_RUN_OFFSET)
#define NRF54L_CLOCK_LFCLK_STAT            (NRF54L_CLOCK_BASE + NRF54L_CLOCK_LFCLK_STAT_OFFSET)
#define NRF54L_CLOCK_LFCLK_SRCCOPY         (NRF54L_CLOCK_BASE + NRF54L_CLOCK_LFCLK_SRCCOPY_OFFSET)
#define NRF54L_CLOCK_PLL24M_RUN            (NRF54L_CLOCK_BASE + NRF54L_CLOCK_PLL24M_RUN_OFFSET)
#define NRF54L_CLOCK_PLL24M_STAT           (NRF54L_CLOCK_BASE + NRF54L_CLOCK_PLL24M_STAT_OFFSET)

/* Register bit definitions *************************************************/

/* INTEN/INTENSET/INTENCLR/INTPEND Registers */

#define CLOCK_INT_XOSTARTED    (1 << 0)
#define CLOCK_INT_PLLSTARTED   (1 << 1)
#define CLOCK_INT_LFCLKSTARTED (1 << 2)
#define CLOCK_INT_DONE         (1 << 3)
#define CLOCK_INT_XOTUNED      (1 << 4)
#define CLOCK_INT_XOTUNEERROR  (1 << 5)
#define CLOCK_INT_XOTUNEFAILED (1 << 6)
#define CLOCK_INT_XO24MSTARTED (1 << 7)

/* XO_RUN Register */

#define CLOCK_XO_RUN_STATUS (1 << 0)

/* XO_STAT Register */

#define CLOCK_XO_STAT_STATE (1 << 16)

/* PLL_RUN Register */

#define CLOCK_PLL_RUN_STATUS (1 << 0)

/* PLL_STAT Register */

#define CLOCK_PLL_STAT_STATE (1 << 16)

/* LFCLK_SRC Register */

#define CLOCK_LFCLK_SRC_SRC_SHIFT    (0)
#define CLOCK_LFCLK_SRC_SRC_MASK     (0x3 << CLOCK_LFCLK_SRC_SRC_SHIFT)
#  define CLOCK_LFCLK_SRC_SRC_LFRC   (0 << CLOCK_LFCLK_SRC_SRC_SHIFT)
#  define CLOCK_LFCLK_SRC_SRC_LFXO   (1 << CLOCK_LFCLK_SRC_SRC_SHIFT)
#  define CLOCK_LFCLK_SRC_SRC_LFSYNT (2 << CLOCK_LFCLK_SRC_SRC_SHIFT)

/* LFCLK_RUN Register */

#define CLOCK_LFCLK_RUN_STATUS (1 << 0)

/* LFCLK_STAT Register */

#define CLOCK_LFCLK_STAT_SRC_SHIFT     (0)
#define CLOCK_LFCLK_STAT_SRC_MASK      (0x3 << CLOCK_LFCLK_STAT_SRC_SHIFT)
#  define CLOCK_LFCLK_STAT_SRC_LFRC    (0 << CLOCK_LFCLK_STAT_SRC_SHIFT)
#  define CLOCK_LFCLK_STAT_SRC_LFXO    (1 << CLOCK_LFCLK_STAT_SRC_SHIFT)
#  define CLOCK_LFCLK_STAT_SRC_LFSYNT  (2 << CLOCK_LFCLK_STAT_SRC_SHIFT)
#define CLOCK_LFCLK_STAT_ALWAYSRUNNING (1 << 4)
#define CLOCK_LFCLK_STAT_STATE         (1 << 16)

/* LFCLK_SRCCOPY Register */

#define CLOCK_LFCLK_SRCCOPY_SRC_SHIFT    (0)
#define CLOCK_LFCLK_SRCCOPY_SRC_MASK     (0x3 << CLOCK_LFCLK_SRCCOPY_SRC_SHIFT)
#  define CLOCK_LFCLK_SRCCOPY_SRC_LFRC   (0 << CLOCK_LFCLK_SRCCOPY_SRC_SHIFT)
#  define CLOCK_LFCLK_SRCCOPY_SRC_LFXO   (1 << CLOCK_LFCLK_SRCCOPY_SRC_SHIFT)
#  define CLOCK_LFCLK_SRCCOPY_SRC_LFSYNT (2 << CLOCK_LFCLK_SRCCOPY_SRC_SHIFT)

/* PLL24M_RUN Register */

#define CLOCK_PLL24M_RUN_STATUS (1 << 0)

/* PLL24M_STAT Register */

#define CLOCK_PLL24M_STAT_STATE (1 << 16)

/* SUBSCRIBE/PUBLISH Registers */

#define CLOCK_DPPI_CHIDX_SHIFT (0)
#define CLOCK_DPPI_CHIDX_MASK  (0xff << CLOCK_DPPI_CHIDX_SHIFT)
#define CLOCK_DPPI_ENABLE      (1 << 31)

#endif /* __ARCH_ARM_SRC_NRF54L_HARDWARE_NRF54L_CLOCK_H */
