#!/usr/bin/env python3
#
# SPDX-License-Identifier: Apache-2.0

"""Register NuttX/apps repositories for out-of-tree CMake discovery.

Examples:
  python tools/register-nuttx.py nuttx_v1 --kind nuttx --path E:/nuttx_workspace/nuttx
  python tools/register-nuttx.py apps_v1 --kind apps --path E:/nuttx_workspace/apps

After registration, external projects can use:
  find_package(<name> REQUIRED CONFIG)
"""

from __future__ import annotations

import argparse
import hashlib
import os
from pathlib import Path
import sys
import subprocess


def _default_package_root() -> Path:
    if os.name == "nt":
        local_app_data = os.environ.get("LOCALAPPDATA")
        if local_app_data:
            return Path(local_app_data) / "NuttX" / "cmake-packages"

    xdg_data_home = os.environ.get("XDG_DATA_HOME")
    if xdg_data_home:
        return Path(xdg_data_home) / "nuttx" / "cmake-packages"

    return Path.home() / ".local" / "share" / "nuttx" / "cmake-packages"


def _cmake_escape(path_text: str) -> str:
    return path_text.replace("\\", "/")


def _package_config_text(name: str, kind: str, repo_path: Path, label: str) -> str:
    repo = _cmake_escape(str(repo_path))
    out = [
        "# Auto-generated by tools/register-nuttx.py",
        "# SPDX-License-Identifier: Apache-2.0",
    ]

    if kind == "nuttx":
        out.append(f'set(NUTTX_BASE "{repo}")')
    elif kind == "apps":
        out.append(f'set(NUTTX_APPS_BASE "{repo}")')

    out.append("")
    return "\n".join(out)


def _register_cmake_user_registry(package_name: str, package_dir: Path) -> None:
    package_dir = package_dir.resolve()

    if os.name == "nt":
        # Windows CMake user package registry in HKCU.
        import winreg  # type: ignore

        key_path = fr"Software\Kitware\CMake\Packages\{package_name}"
        value_name = "nuttx_registry"
        with winreg.CreateKey(winreg.HKEY_CURRENT_USER, key_path) as key:
            winreg.SetValueEx(key, value_name, 0, winreg.REG_SZ, str(package_dir))
        return

    # Unix-like CMake user package registry under ~/.cmake/packages/<Pkg>/<id>
    reg_root = Path.home() / ".cmake" / "packages" / package_name
    reg_root.mkdir(parents=True, exist_ok=True)
    digest = hashlib.sha1(str(package_dir).encode("utf-8")).hexdigest()
    (reg_root / digest).write_text(str(package_dir), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Register a NuttX/apps repository by local path only."
    )
    parser.add_argument("name", help="Registration identifier, e.g. nuttx_v1")
    parser.add_argument("--path", required=True, help="Repository path")
    parser.add_argument(
        "--kind",
        required=True,
        choices=["nuttx", "apps"],
        help="Repository type (required): nuttx or apps",
    )
    parser.add_argument("--label", default="", help="Optional free-form label")
    parser.add_argument(
        "--registry-root",
        default="",
        help="Override package root for generated <name>Config.cmake files.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing registration with the same name",
    )
    parser.add_argument(
        "--skip-cmake-user-registry",
        action="store_true",
        help="Do not write CMake user package registry entry",
    )

    args = parser.parse_args()

    repo_path = Path(args.path).expanduser().resolve()
    if not repo_path.exists():
        print(f"error: path does not exist: {repo_path}", file=sys.stderr)
        return 2

    package_root = (
        Path(args.registry_root).expanduser().resolve()
        if args.registry_root
        else _default_package_root()
    )

    package_dir = package_root / args.name
    config_file = package_dir / f"{args.name}Config.cmake"

    if config_file.exists() and not args.force:
        print(
            f"error: registration '{args.name}' already exists. Use --force to overwrite.",
            file=sys.stderr,
        )
        return 3

    package_dir.mkdir(parents=True, exist_ok=True)
    config_file.write_text(
        _package_config_text(args.name, args.kind, repo_path, args.label),
        encoding="utf-8",
    )

    if not args.skip_cmake_user_registry:
        _register_cmake_user_registry(args.name, package_dir)

    print(f"registered: {args.name}")
    print(f"  kind:          {args.kind}")
    print(f"  path:          {repo_path}")
    print(f"  package config:{config_file}")
    print("  CMake usage:   find_package({} REQUIRED CONFIG)".format(args.name))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
