function(nuttx_generate_outputs target)
  if (CONFIG_INTELHEX_BINARY)
    add_custom_command(OUTPUT ${target}.hex COMMAND ${CMAKE_OBJCOPY} -O ihex ${target} ${target}.hex DEPENDS ${target})
    add_custom_target(${target}-hex ALL DEPENDS ${target}.hex)
    file(APPEND ${CMAKE_BINARY_DIR}/nuttx.manifest "${target}.hex\n")
  endif()

  if (CONFIG_MOTOROLA_SREC)
    add_custom_command(OUTPUT ${target}.srec COMMAND ${CMAKE_OBJCOPY} -O srec ${target} ${target}.srec DEPENDS ${target})
    add_custom_target(${target}-srec ALL DEPENDS ${target}.srec)
    file(APPEND ${CMAKE_BINARY_DIR}/nuttx.manifest "${target}.srec\n")
  endif()

  if (CONFIG_RAW_BINARY)
    add_custom_command(OUTPUT ${target}.bin COMMAND ${CMAKE_OBJCOPY} -O binary ${target} ${target}.bin DEPENDS ${target})
    add_custom_target(${target}-bin ALL DEPENDS ${target}.bin)
    file(APPEND ${CMAKE_BINARY_DIR}/nuttx.manifest "${target}.bin\n")
  endif()
endfunction(nuttx_generate_outputs)
