/****************************************************************************
 * arch/arm/src/imxrt/hardware/rt118x/imxrt118x_dmamux.h
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

#ifndef __ARCH_ARM_SRC_IMXRT_HARDWARE_RT118X_IMXRT118X_DMAMUX_H
#define __ARCH_ARM_SRC_IMXRT_HARDWARE_RT118X_IMXRT118X_DMAMUX_H

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <stdint.h>

#include "hardware/imxrt_memorymap.h"

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* eDMA3/eDMA4 request source constants (IMXRT1180RM Ch. 5) */

#define IMXRT_DMA_ENGINE_EDMA3       (0)
#define IMXRT_DMA_ENGINE_EDMA4       (1)

#define IMXRT_DMA_SRC_ENGINE_SHIFT   (8)
#define IMXRT_DMA_SRC_ENGINE_MASK    (0xff << IMXRT_DMA_SRC_ENGINE_SHIFT)
#define IMXRT_DMA_SRC_MUX_SHIFT      (0)
#define IMXRT_DMA_SRC_MUX_MASK       (0xff << IMXRT_DMA_SRC_MUX_SHIFT)
#define EDMA_MUX_MASK                IMXRT_DMA_SRC_MUX_MASK

#define IMXRT_DMA_SRC(_engine, _mux) \
  (((_engine) << IMXRT_DMA_SRC_ENGINE_SHIFT) | \
   ((_mux) << IMXRT_DMA_SRC_MUX_SHIFT))

#define IMXRT_DMA_SRC_ENGINE(_v) \
  (((_v) & IMXRT_DMA_SRC_ENGINE_MASK) >> IMXRT_DMA_SRC_ENGINE_SHIFT)
#define IMXRT_DMA_SRC_MUX(_v) \
  (((_v) & IMXRT_DMA_SRC_MUX_MASK) >> IMXRT_DMA_SRC_MUX_SHIFT)

/****************************************************************************
 * Inline Functions
 ****************************************************************************/

#ifndef __ASSEMBLY__

static inline uintptr_t imxrt_dmamux_get_dmabase(uint16_t dmamux)
{
  return (IMXRT_DMA_SRC_ENGINE(dmamux) == IMXRT_DMA_ENGINE_EDMA3) ?
         IMXRT_DMA3_BASE : IMXRT_DMA4_BASE;
}

#endif /* __ASSEMBLY__ */

/* eDMA3 (AONMIX) request sources */

#define IMXRT_DMACHAN_CAN1                            IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 1)
#define IMXRT_DMACHAN_GPIO1_REQUEST0                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 3)
#define IMXRT_DMACHAN_GPIO1_REQUEST1                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 4)
#define IMXRT_DMACHAN_I3_C1_TO_BUS_REQUEST            IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 5)
#define IMXRT_DMACHAN_I3_C1_FROM_BUS_REQUEST          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 6)
#define IMXRT_DMACHAN_LPI2_C1_TX                      IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 7)
#define IMXRT_DMACHAN_LPI2_C1_RX                      IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 8)
#define IMXRT_DMACHAN_LPI2_C2_TX                      IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 9)
#define IMXRT_DMACHAN_LPI2_C2_RX                      IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 10)
#define IMXRT_DMACHAN_LPSPI1_TX                       IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 11)
#define IMXRT_DMACHAN_LPSPI1_RX                       IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 12)
#define IMXRT_DMACHAN_LPSPI2_TX                       IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 13)
#define IMXRT_DMACHAN_LPSPI2_RX                       IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 14)
#define IMXRT_DMACHAN_LPTMR1_REQUEST                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 15)
#define IMXRT_DMACHAN_LPUART1_TX                      IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 16)
#define IMXRT_DMACHAN_LPUART1_RX                      IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 17)
#define IMXRT_DMACHAN_LPUART2_TX                      IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 18)
#define IMXRT_DMACHAN_LPUART2_RX                      IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 19)
#define IMXRT_DMACHAN_EDGELOCK_REQUEST                IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 20)
#define IMXRT_DMACHAN_SAI1_TX                         IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 21)
#define IMXRT_DMACHAN_SAI1_RX                         IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 22)
#define IMXRT_DMACHAN_TPM1_REQUEST0_REQUEST2          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 23)
#define IMXRT_DMACHAN_TPM1_REQUEST1_REQUEST3          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 24)
#define IMXRT_DMACHAN_TPM1_OVERFLOW_REQUEST           IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 25)
#define IMXRT_DMACHAN_TPM2_REQUEST0_REQUEST2          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 26)
#define IMXRT_DMACHAN_TPM2_REQUEST1_REQUEST3          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 27)
#define IMXRT_DMACHAN_TPM2_OVERFLOW_REQUEST           IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 28)
#define IMXRT_DMACHAN_LPUART7_TX                      IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 29)
#define IMXRT_DMACHAN_LPUART7_RX                      IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 30)
#define IMXRT_DMACHAN_FLEX_SPI2_TX                    IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 33)
#define IMXRT_DMACHAN_FLEX_SPI2_RX                    IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 34)
#define IMXRT_DMACHAN_CAN3                            IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 38)
#define IMXRT_DMACHAN_LPUART12_TX                     IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 31)
#define IMXRT_DMACHAN_LPUART12_RX                     IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA3, 32)

/* eDMA4 (WAKEUPMIX / MEGAMIX) request sources */

#define IMXRT_DMACHAN_GPIO2_REQUEST0                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 2)
#define IMXRT_DMACHAN_GPIO2_REQUEST1                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 3)
#define IMXRT_DMACHAN_GPIO3_REQUEST0                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 4)
#define IMXRT_DMACHAN_GPIO3_REQUEST1                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 5)
#define IMXRT_DMACHAN_I3_C2_TO_BUS_REQUEST            IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 6)
#define IMXRT_DMACHAN_I3_C2_FROM_BUS_REQUEST          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 7)
#define IMXRT_DMACHAN_LPI2_C3_TX                      IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 8)
#define IMXRT_DMACHAN_LPI2_C3_RX                      IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 9)
#define IMXRT_DMACHAN_LPSPI3_TX                       IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 12)
#define IMXRT_DMACHAN_LPSPI3_RX                       IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 13)
#define IMXRT_DMACHAN_LPSPI4_TX                       IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 14)
#define IMXRT_DMACHAN_LPSPI4_RX                       IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 15)
#define IMXRT_DMACHAN_LPUART3_TX                      IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 17)
#define IMXRT_DMACHAN_LPUART3_RX                      IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 18)
#define IMXRT_DMACHAN_LPUART4_TX                      IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 19)
#define IMXRT_DMACHAN_LPUART4_RX                      IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 20)
#define IMXRT_DMACHAN_LPUART5_TX                      IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 21)
#define IMXRT_DMACHAN_LPUART5_RX                      IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 22)
#define IMXRT_DMACHAN_LPUART6_TX                      IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 23)
#define IMXRT_DMACHAN_LPUART6_RX                      IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 24)
#define IMXRT_DMACHAN_TPM3_REQUEST0_REQUEST2          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 25)
#define IMXRT_DMACHAN_TPM3_REQUEST1_REQUEST3          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 26)
#define IMXRT_DMACHAN_TPM3_OVERFLOW_REQUEST           IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 27)
#define IMXRT_DMACHAN_FLEX_IO1_REQUEST0               IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 37)
#define IMXRT_DMACHAN_FLEX_IO1_REQUEST1               IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 38)
#define IMXRT_DMACHAN_FLEX_IO1_REQUEST2               IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 39)
#define IMXRT_DMACHAN_FLEX_IO1_REQUEST3               IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 40)
#define IMXRT_DMACHAN_FLEX_IO1_REQUEST4               IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 41)
#define IMXRT_DMACHAN_FLEX_IO1_REQUEST5               IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 42)
#define IMXRT_DMACHAN_FLEX_IO1_REQUEST6               IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 43)
#define IMXRT_DMACHAN_FLEX_IO1_REQUEST7               IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 44)
#define IMXRT_DMACHAN_FLEX_IO2_REQUEST0               IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 45)
#define IMXRT_DMACHAN_FLEX_IO2_REQUEST1               IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 46)
#define IMXRT_DMACHAN_FLEX_IO2_REQUEST2               IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 47)
#define IMXRT_DMACHAN_FLEX_IO2_REQUEST3               IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 48)
#define IMXRT_DMACHAN_FLEX_IO2_REQUEST4               IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 49)
#define IMXRT_DMACHAN_FLEX_IO2_REQUEST5               IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 50)
#define IMXRT_DMACHAN_FLEX_IO2_REQUEST6               IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 51)
#define IMXRT_DMACHAN_FLEX_IO2_REQUEST7               IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 52)
#define IMXRT_DMACHAN_FLEX_SPI1_TX                    IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 53)
#define IMXRT_DMACHAN_FLEX_SPI1_RX                    IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 54)
#define IMXRT_DMACHAN_ADC1_REQUEST0                   IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 57)
#define IMXRT_DMACHAN_FLEX_PWM3_CAPTURE_SUB0          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 74)
#define IMXRT_DMACHAN_FLEX_PWM3_CAPTURE_SUB1          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 75)
#define IMXRT_DMACHAN_FLEX_PWM3_CAPTURE_SUB2          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 76)
#define IMXRT_DMACHAN_FLEX_PWM3_CAPTURE_SUB3          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 77)
#define IMXRT_DMACHAN_FLEX_PWM3_VALUE_SUB0            IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 78)
#define IMXRT_DMACHAN_FLEX_PWM3_VALUE_SUB1            IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 79)
#define IMXRT_DMACHAN_FLEX_PWM3_VALUE_SUB2            IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 80)
#define IMXRT_DMACHAN_FLEX_PWM3_VALUE_SUB3            IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 81)
#define IMXRT_DMACHAN_FLEX_PWM4_CAPTURE_SUB0          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 82)
#define IMXRT_DMACHAN_FLEX_PWM4_CAPTURE_SUB1          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 83)
#define IMXRT_DMACHAN_FLEX_PWM4_CAPTURE_SUB2          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 84)
#define IMXRT_DMACHAN_FLEX_PWM4_CAPTURE_SUB3          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 85)
#define IMXRT_DMACHAN_FLEX_PWM4_VALUE_SUB0            IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 86)
#define IMXRT_DMACHAN_FLEX_PWM4_VALUE_SUB1            IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 87)
#define IMXRT_DMACHAN_FLEX_PWM4_VALUE_SUB2            IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 88)
#define IMXRT_DMACHAN_FLEX_PWM4_VALUE_SUB3            IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 89)
#define IMXRT_DMACHAN_QTIMER1_CAPT_TIMER0             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 90)
#define IMXRT_DMACHAN_QTIMER1_CAPT_TIMER1             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 91)
#define IMXRT_DMACHAN_QTIMER1_CAPT_TIMER2             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 92)
#define IMXRT_DMACHAN_QTIMER1_CAPT_TIMER3             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 93)
#define IMXRT_DMACHAN_QTIMER1_CMPLD1_TIMER0_CMPLD2_TIMER1 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 94)
#define IMXRT_DMACHAN_QTIMER1_CMPLD1_TIMER1_CMPLD2_TIMER0 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 95)
#define IMXRT_DMACHAN_QTIMER1_CMPLD1_TIMER2_CMPLD2_TIMER3 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 96)
#define IMXRT_DMACHAN_QTIMER1_CMPLD1_TIMER3_CMPLD2_TIMER2 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 97)
#define IMXRT_DMACHAN_QTIMER2_CAPT_TIMER0             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 98)
#define IMXRT_DMACHAN_QTIMER2_CAPT_TIMER1             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 99)
#define IMXRT_DMACHAN_QTIMER2_CAPT_TIMER2             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 100)
#define IMXRT_DMACHAN_QTIMER2_CAPT_TIMER3             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 101)
#define IMXRT_DMACHAN_QTIMER2_CMPLD1_TIMER0_CMPLD2_TIMER1 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 102)
#define IMXRT_DMACHAN_QTIMER2_CMPLD1_TIMER1_CMPLD2_TIMER0 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 103)
#define IMXRT_DMACHAN_QTIMER2_CMPLD1_TIMER2_CMPLD2_TIMER3 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 104)
#define IMXRT_DMACHAN_QTIMER2_CMPLD1_TIMER3_CMPLD2_TIMER2 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 105)
#define IMXRT_DMACHAN_QTIMER3_CAPT_TIMER0             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 106)
#define IMXRT_DMACHAN_QTIMER3_CAPT_TIMER1             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 107)
#define IMXRT_DMACHAN_QTIMER3_CAPT_TIMER2             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 108)
#define IMXRT_DMACHAN_QTIMER3_CAPT_TIMER3             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 109)
#define IMXRT_DMACHAN_QTIMER3_CMPLD1_TIMER0_CMPLD2_TIMER1 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 110)
#define IMXRT_DMACHAN_QTIMER3_CMPLD1_TIMER1_CMPLD2_TIMER0 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 111)
#define IMXRT_DMACHAN_QTIMER3_CMPLD1_TIMER2_CMPLD2_TIMER3 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 112)
#define IMXRT_DMACHAN_QTIMER3_CMPLD1_TIMER3_CMPLD2_TIMER2 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 113)
#define IMXRT_DMACHAN_QTIMER4_CAPT_TIMER0             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 114)
#define IMXRT_DMACHAN_QTIMER4_CAPT_TIMER1             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 115)
#define IMXRT_DMACHAN_QTIMER4_CAPT_TIMER2             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 116)
#define IMXRT_DMACHAN_QTIMER4_CAPT_TIMER3             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 117)
#define IMXRT_DMACHAN_QTIMER4_CMPLD1_TIMER0_CMPLD2_TIMER1 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 118)
#define IMXRT_DMACHAN_QTIMER4_CMPLD1_TIMER1_CMPLD2_TIMER0 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 119)
#define IMXRT_DMACHAN_QTIMER4_CMPLD1_TIMER2_CMPLD2_TIMER3 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 120)
#define IMXRT_DMACHAN_QTIMER4_CMPLD1_TIMER3_CMPLD2_TIMER2 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 121)
#define IMXRT_DMACHAN_XBAR1_REQUEST0                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 154)
#define IMXRT_DMACHAN_XBAR1_REQUEST1                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 155)
#define IMXRT_DMACHAN_XBAR1_REQUEST2                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 156)
#define IMXRT_DMACHAN_XBAR1_REQUEST3                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 157)
#define IMXRT_DMACHAN_ADC2_REQUEST0                   IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 158)
#define IMXRT_DMACHAN_EQDC1                           IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 159)
#define IMXRT_DMACHAN_EQDC2                           IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 160)
#define IMXRT_DMACHAN_EQDC3                           IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 161)
#define IMXRT_DMACHAN_EQDC4                           IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 162)
#define IMXRT_DMACHAN_LPSPI5_TX                       IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 167)
#define IMXRT_DMACHAN_LPSPI5_RX                       IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 168)
#define IMXRT_DMACHAN_LPSPI6_TX                       IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 169)
#define IMXRT_DMACHAN_LPSPI6_RX                       IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 170)
#define IMXRT_DMACHAN_LPUART8_TX                      IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 178)
#define IMXRT_DMACHAN_LPUART8_RX                      IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 179)
#define IMXRT_DMACHAN_DAC                             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 186)
#define IMXRT_DMACHAN_CMP3                            IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 189)
#define IMXRT_DMACHAN_ASRC_REQUEST1                   IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 191)
#define IMXRT_DMACHAN_ASRC_REQUEST2                   IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 192)
#define IMXRT_DMACHAN_ASRC_REQUEST3                   IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 193)
#define IMXRT_DMACHAN_ASRC_REQUEST4                   IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 194)
#define IMXRT_DMACHAN_ASRC_REQUEST5                   IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 195)
#define IMXRT_DMACHAN_ASRC_REQUEST6                   IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 196)
#define IMXRT_DMACHAN_SPDIF_RX                        IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 197)
#define IMXRT_DMACHAN_SPDIF_TX                        IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 198)
#define IMXRT_DMACHAN_PDM_RX                          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 199)
#define IMXRT_DMACHAN_GPIO4_REQUEST0                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 200)
#define IMXRT_DMACHAN_GPIO4_REQUEST1                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 201)
#define IMXRT_DMACHAN_GPIO5_REQUEST0                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 202)
#define IMXRT_DMACHAN_GPIO5_REQUEST1                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 203)
#define IMXRT_DMACHAN_GPIO6_REQUEST0                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 204)
#define IMXRT_DMACHAN_GPIO6_REQUEST1                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 205)
#define IMXRT_DMACHAN_SINC3_REQUEST0                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 216)
#define IMXRT_DMACHAN_SINC3_REQUEST1                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 217)
#define IMXRT_DMACHAN_SINC3_REQUEST2                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 218)
#define IMXRT_DMACHAN_SINC3_REQUEST3                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 219)
#define IMXRT_DMACHAN_ADC1_REQUEST1                   IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 220)
#define IMXRT_DMACHAN_ADC2_REQUEST1                   IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 221)
#define IMXRT_DMACHAN_LPTMR2_REQUEST                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 16)
#define IMXRT_DMACHAN_TPM4_REQUEST0_REQUEST2          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 28)
#define IMXRT_DMACHAN_TPM4_REQUEST1_REQUEST3          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 29)
#define IMXRT_DMACHAN_TPM4_OVERFLOW_REQUEST           IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 30)
#define IMXRT_DMACHAN_FLEX_PWM1_CAPTURE_SUB0          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 58)
#define IMXRT_DMACHAN_FLEX_PWM1_CAPTURE_SUB1          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 59)
#define IMXRT_DMACHAN_FLEX_PWM1_CAPTURE_SUB2          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 60)
#define IMXRT_DMACHAN_FLEX_PWM1_CAPTURE_SUB3          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 61)
#define IMXRT_DMACHAN_FLEX_PWM1_VALUE_SUB0            IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 62)
#define IMXRT_DMACHAN_FLEX_PWM1_VALUE_SUB1            IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 63)
#define IMXRT_DMACHAN_FLEX_PWM1_VALUE_SUB2            IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 64)
#define IMXRT_DMACHAN_FLEX_PWM1_VALUE_SUB3            IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 65)
#define IMXRT_DMACHAN_FLEX_PWM2_CAPTURE_SUB0          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 66)
#define IMXRT_DMACHAN_FLEX_PWM2_CAPTURE_SUB1          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 67)
#define IMXRT_DMACHAN_FLEX_PWM2_CAPTURE_SUB2          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 68)
#define IMXRT_DMACHAN_FLEX_PWM2_CAPTURE_SUB3          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 69)
#define IMXRT_DMACHAN_FLEX_PWM2_VALUE_SUB0            IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 70)
#define IMXRT_DMACHAN_FLEX_PWM2_VALUE_SUB1            IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 71)
#define IMXRT_DMACHAN_FLEX_PWM2_VALUE_SUB2            IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 72)
#define IMXRT_DMACHAN_FLEX_PWM2_VALUE_SUB3            IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 73)
#define IMXRT_DMACHAN_QTIMER5_CAPT_TIMER0             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 122)
#define IMXRT_DMACHAN_QTIMER5_CAPT_TIMER1             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 123)
#define IMXRT_DMACHAN_QTIMER5_CAPT_TIMER2             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 124)
#define IMXRT_DMACHAN_QTIMER5_CAPT_TIMER3             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 125)
#define IMXRT_DMACHAN_QTIMER5_CMPLD1_TIMER0_CMPLD2_TIMER1 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 126)
#define IMXRT_DMACHAN_QTIMER5_CMPLD1_TIMER1_CMPLD2_TIMER0 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 127)
#define IMXRT_DMACHAN_QTIMER5_CMPLD1_TIMER2_CMPLD2_TIMER3 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 128)
#define IMXRT_DMACHAN_QTIMER5_CMPLD1_TIMER3_CMPLD2_TIMER2 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 129)
#define IMXRT_DMACHAN_QTIMER6_CAPT_TIMER0             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 130)
#define IMXRT_DMACHAN_QTIMER6_CAPT_TIMER1             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 131)
#define IMXRT_DMACHAN_QTIMER6_CAPT_TIMER2             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 132)
#define IMXRT_DMACHAN_QTIMER6_CAPT_TIMER3             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 133)
#define IMXRT_DMACHAN_QTIMER6_CMPLD1_TIMER0_CMPLD2_TIMER1 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 134)
#define IMXRT_DMACHAN_QTIMER6_CMPLD1_TIMER1_CMPLD2_TIMER0 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 135)
#define IMXRT_DMACHAN_QTIMER6_CMPLD1_TIMER2_CMPLD2_TIMER3 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 136)
#define IMXRT_DMACHAN_QTIMER6_CMPLD1_TIMER3_CMPLD2_TIMER2 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 137)
#define IMXRT_DMACHAN_QTIMER7_CAPT_TIMER0             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 138)
#define IMXRT_DMACHAN_QTIMER7_CAPT_TIMER1             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 139)
#define IMXRT_DMACHAN_QTIMER7_CAPT_TIMER2             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 140)
#define IMXRT_DMACHAN_QTIMER7_CAPT_TIMER3             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 141)
#define IMXRT_DMACHAN_QTIMER7_CMPLD1_TIMER0_CMPLD2_TIMER1 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 142)
#define IMXRT_DMACHAN_QTIMER7_CMPLD1_TIMER1_CMPLD2_TIMER0 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 143)
#define IMXRT_DMACHAN_QTIMER7_CMPLD1_TIMER2_CMPLD2_TIMER3 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 144)
#define IMXRT_DMACHAN_QTIMER7_CMPLD1_TIMER3_CMPLD2_TIMER2 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 145)
#define IMXRT_DMACHAN_QTIMER8_CAPT_TIMER0             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 146)
#define IMXRT_DMACHAN_QTIMER8_CAPT_TIMER1             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 147)
#define IMXRT_DMACHAN_QTIMER8_CAPT_TIMER2             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 148)
#define IMXRT_DMACHAN_QTIMER8_CAPT_TIMER3             IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 149)
#define IMXRT_DMACHAN_QTIMER8_CMPLD1_TIMER0_CMPLD2_TIMER1 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 150)
#define IMXRT_DMACHAN_QTIMER8_CMPLD1_TIMER1_CMPLD2_TIMER0 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 151)
#define IMXRT_DMACHAN_QTIMER8_CMPLD1_TIMER2_CMPLD2_TIMER3 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 152)
#define IMXRT_DMACHAN_QTIMER8_CMPLD1_TIMER3_CMPLD2_TIMER2 IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 153)
#define IMXRT_DMACHAN_LPI2_C6_TX                      IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 165)
#define IMXRT_DMACHAN_LPI2_C6_RX                      IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 166)
#define IMXRT_DMACHAN_LPTMR3_REQUEST                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 171)
#define IMXRT_DMACHAN_SAI2_TX                         IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 180)
#define IMXRT_DMACHAN_SAI2_RX                         IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 181)
#define IMXRT_DMACHAN_SAI4_TX                         IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 184)
#define IMXRT_DMACHAN_SAI4_RX                         IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 185)
#define IMXRT_DMACHAN_SINC1_REQUEST0                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 208)
#define IMXRT_DMACHAN_SINC1_REQUEST1                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 209)
#define IMXRT_DMACHAN_SINC1_REQUEST2                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 210)
#define IMXRT_DMACHAN_SINC1_REQUEST3                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 211)
#define IMXRT_DMACHAN_SINC2_REQUEST0                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 212)
#define IMXRT_DMACHAN_SINC2_REQUEST1                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 213)
#define IMXRT_DMACHAN_SINC2_REQUEST2                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 214)
#define IMXRT_DMACHAN_SINC2_REQUEST3                  IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 215)
#define IMXRT_DMACHAN_CAN2                            IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 1)
#define IMXRT_DMACHAN_TPM5_REQUEST0_REQUEST2          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 31)
#define IMXRT_DMACHAN_TPM5_REQUEST1_REQUEST3          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 32)
#define IMXRT_DMACHAN_TPM5_OVERFLOW_REQUEST           IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 33)
#define IMXRT_DMACHAN_TPM6_REQUEST0_REQUEST2          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 34)
#define IMXRT_DMACHAN_TPM6_REQUEST1_REQUEST3          IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 35)
#define IMXRT_DMACHAN_TPM6_OVERFLOW_REQUEST           IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 36)
#define IMXRT_DMACHAN_LPUART9_TX                      IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 172)
#define IMXRT_DMACHAN_LPUART9_RX                      IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 173)
#define IMXRT_DMACHAN_LPUART10_TX                     IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 174)
#define IMXRT_DMACHAN_LPUART10_RX                     IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 175)
#define IMXRT_DMACHAN_LPUART11_TX                     IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 176)
#define IMXRT_DMACHAN_LPUART11_RX                     IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 177)
#define IMXRT_DMACHAN_SAI3_TX                         IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 182)
#define IMXRT_DMACHAN_SAI3_RX                         IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 183)
#define IMXRT_DMACHAN_CMP1                            IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 187)
#define IMXRT_DMACHAN_CMP2                            IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 188)
#define IMXRT_DMACHAN_CMP4                            IMXRT_DMA_SRC(IMXRT_DMA_ENGINE_EDMA4, 190)

#endif /* __ARCH_ARM_SRC_IMXRT_HARDWARE_RT118X_IMXRT118X_DMAMUX_H */
